// Code generated by hertz generator.

package api

import (
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/pax-beehive/pax-manager/internal/transport/http/handler"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _healthMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _agentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _pullmailboxMw() []app.HandlerFunc {
	return []app.HandlerFunc{handler.AgentAuth()}
}

func _registeragentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _reportagentstatusMw() []app.HandlerFunc {
	return []app.HandlerFunc{handler.AgentAuth()}
}

func _messagesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatemailboxoffsetMw() []app.HandlerFunc {
	return []app.HandlerFunc{handler.AgentAuth()}
}

func _messageidMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _reportmessageresultMw() []app.HandlerFunc {
	return []app.HandlerFunc{handler.AgentAuth()}
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createagentregistrationtokenMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listagentsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listuserapikeysMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createuserapikeyMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listmailboxMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createmailboxmessageMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _agentsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _agentidMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listagentsessionsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _api_keysMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _revokeuserapikeyMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _sessionsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getsessionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _sessionidMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listsessionmessagesMw() []app.HandlerFunc {
	// your code...
	return nil
}
