// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	paxmanager_api "github.com/pax-beehive/pax-manager/internal/transport/http/router/paxmanager/api"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	paxmanager_api.Register(r)
}
