version: "2"

run:
  timeout: 5m
  tests: true

linters:
  default: standard
  enable:
    - gocyclo
  settings:
    gocyclo:
      min-complexity: 21
  exclusions:
    generated: strict
    paths:
      - internal/manager/openapi_generated.go
      - internal/manager/.*/mocks/.*
      - internal/transport/http/handler/mocks/.*
      - internal/transport/http/handler/.*
      - internal/transport/http/model/.*
      - internal/transport/http/router/.*

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/pax-beehive/pax-manager
  exclusions:
    generated: strict
    paths:
      - internal/manager/openapi_generated.go
      - internal/manager/.*/mocks/.*
      - internal/transport/http/handler/mocks/.*
      - internal/transport/http/handler/.*
      - internal/transport/http/model/.*
      - internal/transport/http/router/.*
