// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	auth "github.com/pax-beehive/pax-manager/internal/manager/auth"
	domain "github.com/pax-beehive/pax-manager/internal/manager/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockPrincipalResolver is an autogenerated mock type for the PrincipalResolver type
type MockPrincipalResolver struct {
	mock.Mock
}

type MockPrincipalResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPrincipalResolver) EXPECT() *MockPrincipalResolver_Expecter {
	return &MockPrincipalResolver_Expecter{mock: &_m.Mock}
}

// Principal provides a mock function with given fields: _a0, _a1
func (_m *MockPrincipalResolver) Principal(_a0 context.Context, _a1 auth.RequestMetadata) (domain.UserPrincipal, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Principal")
	}

	var r0 domain.UserPrincipal
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, auth.RequestMetadata) (domain.UserPrincipal, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, auth.RequestMetadata) domain.UserPrincipal); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(domain.UserPrincipal)
	}

	if rf, ok := ret.Get(1).(func(context.Context, auth.RequestMetadata) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPrincipalResolver_Principal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Principal'
type MockPrincipalResolver_Principal_Call struct {
	*mock.Call
}

// Principal is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 auth.RequestMetadata
func (_e *MockPrincipalResolver_Expecter) Principal(_a0 interface{}, _a1 interface{}) *MockPrincipalResolver_Principal_Call {
	return &MockPrincipalResolver_Principal_Call{Call: _e.mock.On("Principal", _a0, _a1)}
}

func (_c *MockPrincipalResolver_Principal_Call) Run(run func(_a0 context.Context, _a1 auth.RequestMetadata)) *MockPrincipalResolver_Principal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(auth.RequestMetadata))
	})
	return _c
}

func (_c *MockPrincipalResolver_Principal_Call) Return(_a0 domain.UserPrincipal, _a1 error) *MockPrincipalResolver_Principal_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPrincipalResolver_Principal_Call) RunAndReturn(run func(context.Context, auth.RequestMetadata) (domain.UserPrincipal, error)) *MockPrincipalResolver_Principal_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPrincipalResolver creates a new instance of MockPrincipalResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPrincipalResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPrincipalResolver {
	mock := &MockPrincipalResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
