// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	time "time"

	domain "github.com/pax-beehive/pax-manager/internal/manager/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

type MockStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStore) EXPECT() *MockStore_Expecter {
	return &MockStore_Expecter{mock: &_m.Mock}
}

// CreateMailboxMessage provides a mock function with given fields: ctx, principal, req
func (_m *MockStore) CreateMailboxMessage(ctx context.Context, principal domain.UserPrincipal, req domain.CreateMailboxRequest) (domain.MailboxMessage, error) {
	ret := _m.Called(ctx, principal, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateMailboxMessage")
	}

	var r0 domain.MailboxMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserPrincipal, domain.CreateMailboxRequest) (domain.MailboxMessage, error)); ok {
		return rf(ctx, principal, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserPrincipal, domain.CreateMailboxRequest) domain.MailboxMessage); ok {
		r0 = rf(ctx, principal, req)
	} else {
		r0 = ret.Get(0).(domain.MailboxMessage)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.UserPrincipal, domain.CreateMailboxRequest) error); ok {
		r1 = rf(ctx, principal, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_CreateMailboxMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMailboxMessage'
type MockStore_CreateMailboxMessage_Call struct {
	*mock.Call
}

// CreateMailboxMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - principal domain.UserPrincipal
//   - req domain.CreateMailboxRequest
func (_e *MockStore_Expecter) CreateMailboxMessage(ctx interface{}, principal interface{}, req interface{}) *MockStore_CreateMailboxMessage_Call {
	return &MockStore_CreateMailboxMessage_Call{Call: _e.mock.On("CreateMailboxMessage", ctx, principal, req)}
}

func (_c *MockStore_CreateMailboxMessage_Call) Run(run func(ctx context.Context, principal domain.UserPrincipal, req domain.CreateMailboxRequest)) *MockStore_CreateMailboxMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.UserPrincipal), args[2].(domain.CreateMailboxRequest))
	})
	return _c
}

func (_c *MockStore_CreateMailboxMessage_Call) Return(_a0 domain.MailboxMessage, _a1 error) *MockStore_CreateMailboxMessage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_CreateMailboxMessage_Call) RunAndReturn(run func(context.Context, domain.UserPrincipal, domain.CreateMailboxRequest) (domain.MailboxMessage, error)) *MockStore_CreateMailboxMessage_Call {
	_c.Call.Return(run)
	return _c
}

// CreateNodeAgent provides a mock function with given fields: ctx, principal, req
func (_m *MockStore) CreateNodeAgent(ctx context.Context, principal domain.UserPrincipal, req domain.CreateAgentRequest) (domain.Agent, domain.MailboxMessage, error) {
	ret := _m.Called(ctx, principal, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateNodeAgent")
	}

	var r0 domain.Agent
	var r1 domain.MailboxMessage
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserPrincipal, domain.CreateAgentRequest) (domain.Agent, domain.MailboxMessage, error)); ok {
		return rf(ctx, principal, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserPrincipal, domain.CreateAgentRequest) domain.Agent); ok {
		r0 = rf(ctx, principal, req)
	} else {
		r0 = ret.Get(0).(domain.Agent)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.UserPrincipal, domain.CreateAgentRequest) domain.MailboxMessage); ok {
		r1 = rf(ctx, principal, req)
	} else {
		r1 = ret.Get(1).(domain.MailboxMessage)
	}

	if rf, ok := ret.Get(2).(func(context.Context, domain.UserPrincipal, domain.CreateAgentRequest) error); ok {
		r2 = rf(ctx, principal, req)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockStore_CreateNodeAgent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateNodeAgent'
type MockStore_CreateNodeAgent_Call struct {
	*mock.Call
}

// CreateNodeAgent is a helper method to define mock.On call
//   - ctx context.Context
//   - principal domain.UserPrincipal
//   - req domain.CreateAgentRequest
func (_e *MockStore_Expecter) CreateNodeAgent(ctx interface{}, principal interface{}, req interface{}) *MockStore_CreateNodeAgent_Call {
	return &MockStore_CreateNodeAgent_Call{Call: _e.mock.On("CreateNodeAgent", ctx, principal, req)}
}

func (_c *MockStore_CreateNodeAgent_Call) Run(run func(ctx context.Context, principal domain.UserPrincipal, req domain.CreateAgentRequest)) *MockStore_CreateNodeAgent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.UserPrincipal), args[2].(domain.CreateAgentRequest))
	})
	return _c
}

func (_c *MockStore_CreateNodeAgent_Call) Return(_a0 domain.Agent, _a1 domain.MailboxMessage, _a2 error) *MockStore_CreateNodeAgent_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockStore_CreateNodeAgent_Call) RunAndReturn(run func(context.Context, domain.UserPrincipal, domain.CreateAgentRequest) (domain.Agent, domain.MailboxMessage, error)) *MockStore_CreateNodeAgent_Call {
	_c.Call.Return(run)
	return _c
}

// CreateNodeAgentSession provides a mock function with given fields: ctx, principal, req
func (_m *MockStore) CreateNodeAgentSession(ctx context.Context, principal domain.UserPrincipal, req domain.CreateSessionRequest) (domain.AgentSession, error) {
	ret := _m.Called(ctx, principal, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateNodeAgentSession")
	}

	var r0 domain.AgentSession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserPrincipal, domain.CreateSessionRequest) (domain.AgentSession, error)); ok {
		return rf(ctx, principal, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserPrincipal, domain.CreateSessionRequest) domain.AgentSession); ok {
		r0 = rf(ctx, principal, req)
	} else {
		r0 = ret.Get(0).(domain.AgentSession)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.UserPrincipal, domain.CreateSessionRequest) error); ok {
		r1 = rf(ctx, principal, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_CreateNodeAgentSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateNodeAgentSession'
type MockStore_CreateNodeAgentSession_Call struct {
	*mock.Call
}

// CreateNodeAgentSession is a helper method to define mock.On call
//   - ctx context.Context
//   - principal domain.UserPrincipal
//   - req domain.CreateSessionRequest
func (_e *MockStore_Expecter) CreateNodeAgentSession(ctx interface{}, principal interface{}, req interface{}) *MockStore_CreateNodeAgentSession_Call {
	return &MockStore_CreateNodeAgentSession_Call{Call: _e.mock.On("CreateNodeAgentSession", ctx, principal, req)}
}

func (_c *MockStore_CreateNodeAgentSession_Call) Run(run func(ctx context.Context, principal domain.UserPrincipal, req domain.CreateSessionRequest)) *MockStore_CreateNodeAgentSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.UserPrincipal), args[2].(domain.CreateSessionRequest))
	})
	return _c
}

func (_c *MockStore_CreateNodeAgentSession_Call) Return(_a0 domain.AgentSession, _a1 error) *MockStore_CreateNodeAgentSession_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_CreateNodeAgentSession_Call) RunAndReturn(run func(context.Context, domain.UserPrincipal, domain.CreateSessionRequest) (domain.AgentSession, error)) *MockStore_CreateNodeAgentSession_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRegistrationToken provides a mock function with given fields: ctx, ownerUserID, tokenHash, expiresAt
func (_m *MockStore) CreateRegistrationToken(ctx context.Context, ownerUserID string, tokenHash string, expiresAt *time.Time) error {
	ret := _m.Called(ctx, ownerUserID, tokenHash, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for CreateRegistrationToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *time.Time) error); ok {
		r0 = rf(ctx, ownerUserID, tokenHash, expiresAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_CreateRegistrationToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRegistrationToken'
type MockStore_CreateRegistrationToken_Call struct {
	*mock.Call
}

// CreateRegistrationToken is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerUserID string
//   - tokenHash string
//   - expiresAt *time.Time
func (_e *MockStore_Expecter) CreateRegistrationToken(ctx interface{}, ownerUserID interface{}, tokenHash interface{}, expiresAt interface{}) *MockStore_CreateRegistrationToken_Call {
	return &MockStore_CreateRegistrationToken_Call{Call: _e.mock.On("CreateRegistrationToken", ctx, ownerUserID, tokenHash, expiresAt)}
}

func (_c *MockStore_CreateRegistrationToken_Call) Run(run func(ctx context.Context, ownerUserID string, tokenHash string, expiresAt *time.Time)) *MockStore_CreateRegistrationToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*time.Time))
	})
	return _c
}

func (_c *MockStore_CreateRegistrationToken_Call) Return(_a0 error) *MockStore_CreateRegistrationToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_CreateRegistrationToken_Call) RunAndReturn(run func(context.Context, string, string, *time.Time) error) *MockStore_CreateRegistrationToken_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSecret provides a mock function with given fields: ctx, principal, req, encrypted
func (_m *MockStore) CreateSecret(ctx context.Context, principal domain.UserPrincipal, req domain.CreateSecretRequest, encrypted domain.SecretVersion) (domain.Secret, domain.SecretVersion, error) {
	ret := _m.Called(ctx, principal, req, encrypted)

	if len(ret) == 0 {
		panic("no return value specified for CreateSecret")
	}

	var r0 domain.Secret
	var r1 domain.SecretVersion
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserPrincipal, domain.CreateSecretRequest, domain.SecretVersion) (domain.Secret, domain.SecretVersion, error)); ok {
		return rf(ctx, principal, req, encrypted)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserPrincipal, domain.CreateSecretRequest, domain.SecretVersion) domain.Secret); ok {
		r0 = rf(ctx, principal, req, encrypted)
	} else {
		r0 = ret.Get(0).(domain.Secret)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.UserPrincipal, domain.CreateSecretRequest, domain.SecretVersion) domain.SecretVersion); ok {
		r1 = rf(ctx, principal, req, encrypted)
	} else {
		r1 = ret.Get(1).(domain.SecretVersion)
	}

	if rf, ok := ret.Get(2).(func(context.Context, domain.UserPrincipal, domain.CreateSecretRequest, domain.SecretVersion) error); ok {
		r2 = rf(ctx, principal, req, encrypted)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockStore_CreateSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSecret'
type MockStore_CreateSecret_Call struct {
	*mock.Call
}

// CreateSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - principal domain.UserPrincipal
//   - req domain.CreateSecretRequest
//   - encrypted domain.SecretVersion
func (_e *MockStore_Expecter) CreateSecret(ctx interface{}, principal interface{}, req interface{}, encrypted interface{}) *MockStore_CreateSecret_Call {
	return &MockStore_CreateSecret_Call{Call: _e.mock.On("CreateSecret", ctx, principal, req, encrypted)}
}

func (_c *MockStore_CreateSecret_Call) Run(run func(ctx context.Context, principal domain.UserPrincipal, req domain.CreateSecretRequest, encrypted domain.SecretVersion)) *MockStore_CreateSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.UserPrincipal), args[2].(domain.CreateSecretRequest), args[3].(domain.SecretVersion))
	})
	return _c
}

func (_c *MockStore_CreateSecret_Call) Return(_a0 domain.Secret, _a1 domain.SecretVersion, _a2 error) *MockStore_CreateSecret_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockStore_CreateSecret_Call) RunAndReturn(run func(context.Context, domain.UserPrincipal, domain.CreateSecretRequest, domain.SecretVersion) (domain.Secret, domain.SecretVersion, error)) *MockStore_CreateSecret_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUserAPIKey provides a mock function with given fields: ctx, principal, name, keyHash, prefix
func (_m *MockStore) CreateUserAPIKey(ctx context.Context, principal domain.UserPrincipal, name string, keyHash string, prefix string) (domain.UserAPIKey, error) {
	ret := _m.Called(ctx, principal, name, keyHash, prefix)

	if len(ret) == 0 {
		panic("no return value specified for CreateUserAPIKey")
	}

	var r0 domain.UserAPIKey
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserPrincipal, string, string, string) (domain.UserAPIKey, error)); ok {
		return rf(ctx, principal, name, keyHash, prefix)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserPrincipal, string, string, string) domain.UserAPIKey); ok {
		r0 = rf(ctx, principal, name, keyHash, prefix)
	} else {
		r0 = ret.Get(0).(domain.UserAPIKey)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.UserPrincipal, string, string, string) error); ok {
		r1 = rf(ctx, principal, name, keyHash, prefix)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_CreateUserAPIKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUserAPIKey'
type MockStore_CreateUserAPIKey_Call struct {
	*mock.Call
}

// CreateUserAPIKey is a helper method to define mock.On call
//   - ctx context.Context
//   - principal domain.UserPrincipal
//   - name string
//   - keyHash string
//   - prefix string
func (_e *MockStore_Expecter) CreateUserAPIKey(ctx interface{}, principal interface{}, name interface{}, keyHash interface{}, prefix interface{}) *MockStore_CreateUserAPIKey_Call {
	return &MockStore_CreateUserAPIKey_Call{Call: _e.mock.On("CreateUserAPIKey", ctx, principal, name, keyHash, prefix)}
}

func (_c *MockStore_CreateUserAPIKey_Call) Run(run func(ctx context.Context, principal domain.UserPrincipal, name string, keyHash string, prefix string)) *MockStore_CreateUserAPIKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.UserPrincipal), args[2].(string), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *MockStore_CreateUserAPIKey_Call) Return(_a0 domain.UserAPIKey, _a1 error) *MockStore_CreateUserAPIKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_CreateUserAPIKey_Call) RunAndReturn(run func(context.Context, domain.UserPrincipal, string, string, string) (domain.UserAPIKey, error)) *MockStore_CreateUserAPIKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetAgent provides a mock function with given fields: ctx, principal, agentID
func (_m *MockStore) GetAgent(ctx context.Context, principal domain.UserPrincipal, agentID string) (domain.Agent, error) {
	ret := _m.Called(ctx, principal, agentID)

	if len(ret) == 0 {
		panic("no return value specified for GetAgent")
	}

	var r0 domain.Agent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserPrincipal, string) (domain.Agent, error)); ok {
		return rf(ctx, principal, agentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserPrincipal, string) domain.Agent); ok {
		r0 = rf(ctx, principal, agentID)
	} else {
		r0 = ret.Get(0).(domain.Agent)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.UserPrincipal, string) error); ok {
		r1 = rf(ctx, principal, agentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_GetAgent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAgent'
type MockStore_GetAgent_Call struct {
	*mock.Call
}

// GetAgent is a helper method to define mock.On call
//   - ctx context.Context
//   - principal domain.UserPrincipal
//   - agentID string
func (_e *MockStore_Expecter) GetAgent(ctx interface{}, principal interface{}, agentID interface{}) *MockStore_GetAgent_Call {
	return &MockStore_GetAgent_Call{Call: _e.mock.On("GetAgent", ctx, principal, agentID)}
}

func (_c *MockStore_GetAgent_Call) Run(run func(ctx context.Context, principal domain.UserPrincipal, agentID string)) *MockStore_GetAgent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.UserPrincipal), args[2].(string))
	})
	return _c
}

func (_c *MockStore_GetAgent_Call) Return(_a0 domain.Agent, _a1 error) *MockStore_GetAgent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_GetAgent_Call) RunAndReturn(run func(context.Context, domain.UserPrincipal, string) (domain.Agent, error)) *MockStore_GetAgent_Call {
	_c.Call.Return(run)
	return _c
}

// GetNode provides a mock function with given fields: ctx, principal, nodeID
func (_m *MockStore) GetNode(ctx context.Context, principal domain.UserPrincipal, nodeID string) (domain.Node, error) {
	ret := _m.Called(ctx, principal, nodeID)

	if len(ret) == 0 {
		panic("no return value specified for GetNode")
	}

	var r0 domain.Node
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserPrincipal, string) (domain.Node, error)); ok {
		return rf(ctx, principal, nodeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserPrincipal, string) domain.Node); ok {
		r0 = rf(ctx, principal, nodeID)
	} else {
		r0 = ret.Get(0).(domain.Node)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.UserPrincipal, string) error); ok {
		r1 = rf(ctx, principal, nodeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_GetNode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNode'
type MockStore_GetNode_Call struct {
	*mock.Call
}

// GetNode is a helper method to define mock.On call
//   - ctx context.Context
//   - principal domain.UserPrincipal
//   - nodeID string
func (_e *MockStore_Expecter) GetNode(ctx interface{}, principal interface{}, nodeID interface{}) *MockStore_GetNode_Call {
	return &MockStore_GetNode_Call{Call: _e.mock.On("GetNode", ctx, principal, nodeID)}
}

func (_c *MockStore_GetNode_Call) Run(run func(ctx context.Context, principal domain.UserPrincipal, nodeID string)) *MockStore_GetNode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.UserPrincipal), args[2].(string))
	})
	return _c
}

func (_c *MockStore_GetNode_Call) Return(_a0 domain.Node, _a1 error) *MockStore_GetNode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_GetNode_Call) RunAndReturn(run func(context.Context, domain.UserPrincipal, string) (domain.Node, error)) *MockStore_GetNode_Call {
	_c.Call.Return(run)
	return _c
}

// GetSecret provides a mock function with given fields: ctx, principal, secretID
func (_m *MockStore) GetSecret(ctx context.Context, principal domain.UserPrincipal, secretID string) (domain.Secret, error) {
	ret := _m.Called(ctx, principal, secretID)

	if len(ret) == 0 {
		panic("no return value specified for GetSecret")
	}

	var r0 domain.Secret
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserPrincipal, string) (domain.Secret, error)); ok {
		return rf(ctx, principal, secretID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserPrincipal, string) domain.Secret); ok {
		r0 = rf(ctx, principal, secretID)
	} else {
		r0 = ret.Get(0).(domain.Secret)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.UserPrincipal, string) error); ok {
		r1 = rf(ctx, principal, secretID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_GetSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSecret'
type MockStore_GetSecret_Call struct {
	*mock.Call
}

// GetSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - principal domain.UserPrincipal
//   - secretID string
func (_e *MockStore_Expecter) GetSecret(ctx interface{}, principal interface{}, secretID interface{}) *MockStore_GetSecret_Call {
	return &MockStore_GetSecret_Call{Call: _e.mock.On("GetSecret", ctx, principal, secretID)}
}

func (_c *MockStore_GetSecret_Call) Run(run func(ctx context.Context, principal domain.UserPrincipal, secretID string)) *MockStore_GetSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.UserPrincipal), args[2].(string))
	})
	return _c
}

func (_c *MockStore_GetSecret_Call) Return(_a0 domain.Secret, _a1 error) *MockStore_GetSecret_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_GetSecret_Call) RunAndReturn(run func(context.Context, domain.UserPrincipal, string) (domain.Secret, error)) *MockStore_GetSecret_Call {
	_c.Call.Return(run)
	return _c
}

// GetSession provides a mock function with given fields: ctx, principal, sessionID
func (_m *MockStore) GetSession(ctx context.Context, principal domain.UserPrincipal, sessionID string) (domain.AgentSession, error) {
	ret := _m.Called(ctx, principal, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for GetSession")
	}

	var r0 domain.AgentSession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserPrincipal, string) (domain.AgentSession, error)); ok {
		return rf(ctx, principal, sessionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserPrincipal, string) domain.AgentSession); ok {
		r0 = rf(ctx, principal, sessionID)
	} else {
		r0 = ret.Get(0).(domain.AgentSession)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.UserPrincipal, string) error); ok {
		r1 = rf(ctx, principal, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_GetSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSession'
type MockStore_GetSession_Call struct {
	*mock.Call
}

// GetSession is a helper method to define mock.On call
//   - ctx context.Context
//   - principal domain.UserPrincipal
//   - sessionID string
func (_e *MockStore_Expecter) GetSession(ctx interface{}, principal interface{}, sessionID interface{}) *MockStore_GetSession_Call {
	return &MockStore_GetSession_Call{Call: _e.mock.On("GetSession", ctx, principal, sessionID)}
}

func (_c *MockStore_GetSession_Call) Run(run func(ctx context.Context, principal domain.UserPrincipal, sessionID string)) *MockStore_GetSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.UserPrincipal), args[2].(string))
	})
	return _c
}

func (_c *MockStore_GetSession_Call) Return(_a0 domain.AgentSession, _a1 error) *MockStore_GetSession_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_GetSession_Call) RunAndReturn(run func(context.Context, domain.UserPrincipal, string) (domain.AgentSession, error)) *MockStore_GetSession_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function with given fields: ctx, userID
func (_m *MockStore) GetUser(ctx context.Context, userID string) (domain.User, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.User, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.User); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type MockStore_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockStore_Expecter) GetUser(ctx interface{}, userID interface{}) *MockStore_GetUser_Call {
	return &MockStore_GetUser_Call{Call: _e.mock.On("GetUser", ctx, userID)}
}

func (_c *MockStore_GetUser_Call) Run(run func(ctx context.Context, userID string)) *MockStore_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStore_GetUser_Call) Return(_a0 domain.User, _a1 error) *MockStore_GetUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_GetUser_Call) RunAndReturn(run func(context.Context, string) (domain.User, error)) *MockStore_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByEmail provides a mock function with given fields: ctx, email
func (_m *MockStore) GetUserByEmail(ctx context.Context, email string) (domain.User, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.User); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_GetUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByEmail'
type MockStore_GetUserByEmail_Call struct {
	*mock.Call
}

// GetUserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockStore_Expecter) GetUserByEmail(ctx interface{}, email interface{}) *MockStore_GetUserByEmail_Call {
	return &MockStore_GetUserByEmail_Call{Call: _e.mock.On("GetUserByEmail", ctx, email)}
}

func (_c *MockStore_GetUserByEmail_Call) Run(run func(ctx context.Context, email string)) *MockStore_GetUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStore_GetUserByEmail_Call) Return(_a0 domain.User, _a1 error) *MockStore_GetUserByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_GetUserByEmail_Call) RunAndReturn(run func(context.Context, string) (domain.User, error)) *MockStore_GetUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// ListAgentSessions provides a mock function with given fields: ctx, principal, agentID
func (_m *MockStore) ListAgentSessions(ctx context.Context, principal domain.UserPrincipal, agentID string) ([]domain.AgentSession, error) {
	ret := _m.Called(ctx, principal, agentID)

	if len(ret) == 0 {
		panic("no return value specified for ListAgentSessions")
	}

	var r0 []domain.AgentSession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserPrincipal, string) ([]domain.AgentSession, error)); ok {
		return rf(ctx, principal, agentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserPrincipal, string) []domain.AgentSession); ok {
		r0 = rf(ctx, principal, agentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.AgentSession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.UserPrincipal, string) error); ok {
		r1 = rf(ctx, principal, agentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_ListAgentSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAgentSessions'
type MockStore_ListAgentSessions_Call struct {
	*mock.Call
}

// ListAgentSessions is a helper method to define mock.On call
//   - ctx context.Context
//   - principal domain.UserPrincipal
//   - agentID string
func (_e *MockStore_Expecter) ListAgentSessions(ctx interface{}, principal interface{}, agentID interface{}) *MockStore_ListAgentSessions_Call {
	return &MockStore_ListAgentSessions_Call{Call: _e.mock.On("ListAgentSessions", ctx, principal, agentID)}
}

func (_c *MockStore_ListAgentSessions_Call) Run(run func(ctx context.Context, principal domain.UserPrincipal, agentID string)) *MockStore_ListAgentSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.UserPrincipal), args[2].(string))
	})
	return _c
}

func (_c *MockStore_ListAgentSessions_Call) Return(_a0 []domain.AgentSession, _a1 error) *MockStore_ListAgentSessions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_ListAgentSessions_Call) RunAndReturn(run func(context.Context, domain.UserPrincipal, string) ([]domain.AgentSession, error)) *MockStore_ListAgentSessions_Call {
	_c.Call.Return(run)
	return _c
}

// ListAgents provides a mock function with given fields: ctx, principal
func (_m *MockStore) ListAgents(ctx context.Context, principal domain.UserPrincipal) ([]domain.Agent, error) {
	ret := _m.Called(ctx, principal)

	if len(ret) == 0 {
		panic("no return value specified for ListAgents")
	}

	var r0 []domain.Agent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserPrincipal) ([]domain.Agent, error)); ok {
		return rf(ctx, principal)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserPrincipal) []domain.Agent); ok {
		r0 = rf(ctx, principal)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Agent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.UserPrincipal) error); ok {
		r1 = rf(ctx, principal)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_ListAgents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAgents'
type MockStore_ListAgents_Call struct {
	*mock.Call
}

// ListAgents is a helper method to define mock.On call
//   - ctx context.Context
//   - principal domain.UserPrincipal
func (_e *MockStore_Expecter) ListAgents(ctx interface{}, principal interface{}) *MockStore_ListAgents_Call {
	return &MockStore_ListAgents_Call{Call: _e.mock.On("ListAgents", ctx, principal)}
}

func (_c *MockStore_ListAgents_Call) Run(run func(ctx context.Context, principal domain.UserPrincipal)) *MockStore_ListAgents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.UserPrincipal))
	})
	return _c
}

func (_c *MockStore_ListAgents_Call) Return(_a0 []domain.Agent, _a1 error) *MockStore_ListAgents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_ListAgents_Call) RunAndReturn(run func(context.Context, domain.UserPrincipal) ([]domain.Agent, error)) *MockStore_ListAgents_Call {
	_c.Call.Return(run)
	return _c
}

// ListMailbox provides a mock function with given fields: ctx, filter
func (_m *MockStore) ListMailbox(ctx context.Context, filter domain.MailboxFilter) ([]domain.MailboxMessage, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListMailbox")
	}

	var r0 []domain.MailboxMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.MailboxFilter) ([]domain.MailboxMessage, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.MailboxFilter) []domain.MailboxMessage); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.MailboxMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.MailboxFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_ListMailbox_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListMailbox'
type MockStore_ListMailbox_Call struct {
	*mock.Call
}

// ListMailbox is a helper method to define mock.On call
//   - ctx context.Context
//   - filter domain.MailboxFilter
func (_e *MockStore_Expecter) ListMailbox(ctx interface{}, filter interface{}) *MockStore_ListMailbox_Call {
	return &MockStore_ListMailbox_Call{Call: _e.mock.On("ListMailbox", ctx, filter)}
}

func (_c *MockStore_ListMailbox_Call) Run(run func(ctx context.Context, filter domain.MailboxFilter)) *MockStore_ListMailbox_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.MailboxFilter))
	})
	return _c
}

func (_c *MockStore_ListMailbox_Call) Return(_a0 []domain.MailboxMessage, _a1 error) *MockStore_ListMailbox_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_ListMailbox_Call) RunAndReturn(run func(context.Context, domain.MailboxFilter) ([]domain.MailboxMessage, error)) *MockStore_ListMailbox_Call {
	_c.Call.Return(run)
	return _c
}

// ListNodeAgents provides a mock function with given fields: ctx, principal, nodeID
func (_m *MockStore) ListNodeAgents(ctx context.Context, principal domain.UserPrincipal, nodeID string) ([]domain.Agent, error) {
	ret := _m.Called(ctx, principal, nodeID)

	if len(ret) == 0 {
		panic("no return value specified for ListNodeAgents")
	}

	var r0 []domain.Agent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserPrincipal, string) ([]domain.Agent, error)); ok {
		return rf(ctx, principal, nodeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserPrincipal, string) []domain.Agent); ok {
		r0 = rf(ctx, principal, nodeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Agent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.UserPrincipal, string) error); ok {
		r1 = rf(ctx, principal, nodeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_ListNodeAgents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListNodeAgents'
type MockStore_ListNodeAgents_Call struct {
	*mock.Call
}

// ListNodeAgents is a helper method to define mock.On call
//   - ctx context.Context
//   - principal domain.UserPrincipal
//   - nodeID string
func (_e *MockStore_Expecter) ListNodeAgents(ctx interface{}, principal interface{}, nodeID interface{}) *MockStore_ListNodeAgents_Call {
	return &MockStore_ListNodeAgents_Call{Call: _e.mock.On("ListNodeAgents", ctx, principal, nodeID)}
}

func (_c *MockStore_ListNodeAgents_Call) Run(run func(ctx context.Context, principal domain.UserPrincipal, nodeID string)) *MockStore_ListNodeAgents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.UserPrincipal), args[2].(string))
	})
	return _c
}

func (_c *MockStore_ListNodeAgents_Call) Return(_a0 []domain.Agent, _a1 error) *MockStore_ListNodeAgents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_ListNodeAgents_Call) RunAndReturn(run func(context.Context, domain.UserPrincipal, string) ([]domain.Agent, error)) *MockStore_ListNodeAgents_Call {
	_c.Call.Return(run)
	return _c
}

// ListNodes provides a mock function with given fields: ctx, principal
func (_m *MockStore) ListNodes(ctx context.Context, principal domain.UserPrincipal) ([]domain.Node, error) {
	ret := _m.Called(ctx, principal)

	if len(ret) == 0 {
		panic("no return value specified for ListNodes")
	}

	var r0 []domain.Node
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserPrincipal) ([]domain.Node, error)); ok {
		return rf(ctx, principal)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserPrincipal) []domain.Node); ok {
		r0 = rf(ctx, principal)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Node)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.UserPrincipal) error); ok {
		r1 = rf(ctx, principal)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_ListNodes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListNodes'
type MockStore_ListNodes_Call struct {
	*mock.Call
}

// ListNodes is a helper method to define mock.On call
//   - ctx context.Context
//   - principal domain.UserPrincipal
func (_e *MockStore_Expecter) ListNodes(ctx interface{}, principal interface{}) *MockStore_ListNodes_Call {
	return &MockStore_ListNodes_Call{Call: _e.mock.On("ListNodes", ctx, principal)}
}

func (_c *MockStore_ListNodes_Call) Run(run func(ctx context.Context, principal domain.UserPrincipal)) *MockStore_ListNodes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.UserPrincipal))
	})
	return _c
}

func (_c *MockStore_ListNodes_Call) Return(_a0 []domain.Node, _a1 error) *MockStore_ListNodes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_ListNodes_Call) RunAndReturn(run func(context.Context, domain.UserPrincipal) ([]domain.Node, error)) *MockStore_ListNodes_Call {
	_c.Call.Return(run)
	return _c
}

// ListSecrets provides a mock function with given fields: ctx, principal
func (_m *MockStore) ListSecrets(ctx context.Context, principal domain.UserPrincipal) ([]domain.Secret, error) {
	ret := _m.Called(ctx, principal)

	if len(ret) == 0 {
		panic("no return value specified for ListSecrets")
	}

	var r0 []domain.Secret
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserPrincipal) ([]domain.Secret, error)); ok {
		return rf(ctx, principal)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserPrincipal) []domain.Secret); ok {
		r0 = rf(ctx, principal)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Secret)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.UserPrincipal) error); ok {
		r1 = rf(ctx, principal)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_ListSecrets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSecrets'
type MockStore_ListSecrets_Call struct {
	*mock.Call
}

// ListSecrets is a helper method to define mock.On call
//   - ctx context.Context
//   - principal domain.UserPrincipal
func (_e *MockStore_Expecter) ListSecrets(ctx interface{}, principal interface{}) *MockStore_ListSecrets_Call {
	return &MockStore_ListSecrets_Call{Call: _e.mock.On("ListSecrets", ctx, principal)}
}

func (_c *MockStore_ListSecrets_Call) Run(run func(ctx context.Context, principal domain.UserPrincipal)) *MockStore_ListSecrets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.UserPrincipal))
	})
	return _c
}

func (_c *MockStore_ListSecrets_Call) Return(_a0 []domain.Secret, _a1 error) *MockStore_ListSecrets_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_ListSecrets_Call) RunAndReturn(run func(context.Context, domain.UserPrincipal) ([]domain.Secret, error)) *MockStore_ListSecrets_Call {
	_c.Call.Return(run)
	return _c
}

// ListSessionMessages provides a mock function with given fields: ctx, principal, sessionID
func (_m *MockStore) ListSessionMessages(ctx context.Context, principal domain.UserPrincipal, sessionID string) ([]domain.MailboxMessage, error) {
	ret := _m.Called(ctx, principal, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for ListSessionMessages")
	}

	var r0 []domain.MailboxMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserPrincipal, string) ([]domain.MailboxMessage, error)); ok {
		return rf(ctx, principal, sessionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserPrincipal, string) []domain.MailboxMessage); ok {
		r0 = rf(ctx, principal, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.MailboxMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.UserPrincipal, string) error); ok {
		r1 = rf(ctx, principal, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_ListSessionMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSessionMessages'
type MockStore_ListSessionMessages_Call struct {
	*mock.Call
}

// ListSessionMessages is a helper method to define mock.On call
//   - ctx context.Context
//   - principal domain.UserPrincipal
//   - sessionID string
func (_e *MockStore_Expecter) ListSessionMessages(ctx interface{}, principal interface{}, sessionID interface{}) *MockStore_ListSessionMessages_Call {
	return &MockStore_ListSessionMessages_Call{Call: _e.mock.On("ListSessionMessages", ctx, principal, sessionID)}
}

func (_c *MockStore_ListSessionMessages_Call) Run(run func(ctx context.Context, principal domain.UserPrincipal, sessionID string)) *MockStore_ListSessionMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.UserPrincipal), args[2].(string))
	})
	return _c
}

func (_c *MockStore_ListSessionMessages_Call) Return(_a0 []domain.MailboxMessage, _a1 error) *MockStore_ListSessionMessages_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_ListSessionMessages_Call) RunAndReturn(run func(context.Context, domain.UserPrincipal, string) ([]domain.MailboxMessage, error)) *MockStore_ListSessionMessages_Call {
	_c.Call.Return(run)
	return _c
}

// ListUserAPIKeys provides a mock function with given fields: ctx, principal
func (_m *MockStore) ListUserAPIKeys(ctx context.Context, principal domain.UserPrincipal) ([]domain.UserAPIKey, error) {
	ret := _m.Called(ctx, principal)

	if len(ret) == 0 {
		panic("no return value specified for ListUserAPIKeys")
	}

	var r0 []domain.UserAPIKey
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserPrincipal) ([]domain.UserAPIKey, error)); ok {
		return rf(ctx, principal)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserPrincipal) []domain.UserAPIKey); ok {
		r0 = rf(ctx, principal)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.UserAPIKey)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.UserPrincipal) error); ok {
		r1 = rf(ctx, principal)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_ListUserAPIKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUserAPIKeys'
type MockStore_ListUserAPIKeys_Call struct {
	*mock.Call
}

// ListUserAPIKeys is a helper method to define mock.On call
//   - ctx context.Context
//   - principal domain.UserPrincipal
func (_e *MockStore_Expecter) ListUserAPIKeys(ctx interface{}, principal interface{}) *MockStore_ListUserAPIKeys_Call {
	return &MockStore_ListUserAPIKeys_Call{Call: _e.mock.On("ListUserAPIKeys", ctx, principal)}
}

func (_c *MockStore_ListUserAPIKeys_Call) Run(run func(ctx context.Context, principal domain.UserPrincipal)) *MockStore_ListUserAPIKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.UserPrincipal))
	})
	return _c
}

func (_c *MockStore_ListUserAPIKeys_Call) Return(_a0 []domain.UserAPIKey, _a1 error) *MockStore_ListUserAPIKeys_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_ListUserAPIKeys_Call) RunAndReturn(run func(context.Context, domain.UserPrincipal) ([]domain.UserAPIKey, error)) *MockStore_ListUserAPIKeys_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeUserAPIKey provides a mock function with given fields: ctx, principal, keyID
func (_m *MockStore) RevokeUserAPIKey(ctx context.Context, principal domain.UserPrincipal, keyID string) error {
	ret := _m.Called(ctx, principal, keyID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeUserAPIKey")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserPrincipal, string) error); ok {
		r0 = rf(ctx, principal, keyID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_RevokeUserAPIKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeUserAPIKey'
type MockStore_RevokeUserAPIKey_Call struct {
	*mock.Call
}

// RevokeUserAPIKey is a helper method to define mock.On call
//   - ctx context.Context
//   - principal domain.UserPrincipal
//   - keyID string
func (_e *MockStore_Expecter) RevokeUserAPIKey(ctx interface{}, principal interface{}, keyID interface{}) *MockStore_RevokeUserAPIKey_Call {
	return &MockStore_RevokeUserAPIKey_Call{Call: _e.mock.On("RevokeUserAPIKey", ctx, principal, keyID)}
}

func (_c *MockStore_RevokeUserAPIKey_Call) Run(run func(ctx context.Context, principal domain.UserPrincipal, keyID string)) *MockStore_RevokeUserAPIKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.UserPrincipal), args[2].(string))
	})
	return _c
}

func (_c *MockStore_RevokeUserAPIKey_Call) Return(_a0 error) *MockStore_RevokeUserAPIKey_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_RevokeUserAPIKey_Call) RunAndReturn(run func(context.Context, domain.UserPrincipal, string) error) *MockStore_RevokeUserAPIKey_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
