// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockSecretIssuer is an autogenerated mock type for the SecretIssuer type
type MockSecretIssuer struct {
	mock.Mock
}

type MockSecretIssuer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSecretIssuer) EXPECT() *MockSecretIssuer_Expecter {
	return &MockSecretIssuer_Expecter{mock: &_m.Mock}
}

// Hash provides a mock function with given fields: secret
func (_m *MockSecretIssuer) Hash(secret string) string {
	ret := _m.Called(secret)

	if len(ret) == 0 {
		panic("no return value specified for Hash")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(secret)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockSecretIssuer_Hash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hash'
type MockSecretIssuer_Hash_Call struct {
	*mock.Call
}

// Hash is a helper method to define mock.On call
//   - secret string
func (_e *MockSecretIssuer_Expecter) Hash(secret interface{}) *MockSecretIssuer_Hash_Call {
	return &MockSecretIssuer_Hash_Call{Call: _e.mock.On("Hash", secret)}
}

func (_c *MockSecretIssuer_Hash_Call) Run(run func(secret string)) *MockSecretIssuer_Hash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockSecretIssuer_Hash_Call) Return(_a0 string) *MockSecretIssuer_Hash_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSecretIssuer_Hash_Call) RunAndReturn(run func(string) string) *MockSecretIssuer_Hash_Call {
	_c.Call.Return(run)
	return _c
}

// New provides a mock function with given fields: prefix
func (_m *MockSecretIssuer) New(prefix string) (string, error) {
	ret := _m.Called(prefix)

	if len(ret) == 0 {
		panic("no return value specified for New")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(prefix)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(prefix)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(prefix)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSecretIssuer_New_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'New'
type MockSecretIssuer_New_Call struct {
	*mock.Call
}

// New is a helper method to define mock.On call
//   - prefix string
func (_e *MockSecretIssuer_Expecter) New(prefix interface{}) *MockSecretIssuer_New_Call {
	return &MockSecretIssuer_New_Call{Call: _e.mock.On("New", prefix)}
}

func (_c *MockSecretIssuer_New_Call) Run(run func(prefix string)) *MockSecretIssuer_New_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockSecretIssuer_New_Call) Return(_a0 string, _a1 error) *MockSecretIssuer_New_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSecretIssuer_New_Call) RunAndReturn(run func(string) (string, error)) *MockSecretIssuer_New_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSecretIssuer creates a new instance of MockSecretIssuer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSecretIssuer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSecretIssuer {
	mock := &MockSecretIssuer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
