// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/pax-beehive/pax-manager/internal/manager/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

type MockStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStore) EXPECT() *MockStore_Expecter {
	return &MockStore_Expecter{mock: &_m.Mock}
}

// MarkMessageResult provides a mock function with given fields: ctx, agentID, messageID, req
func (_m *MockStore) MarkMessageResult(ctx context.Context, agentID string, messageID string, req domain.MessageResultRequest) error {
	ret := _m.Called(ctx, agentID, messageID, req)

	if len(ret) == 0 {
		panic("no return value specified for MarkMessageResult")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, domain.MessageResultRequest) error); ok {
		r0 = rf(ctx, agentID, messageID, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_MarkMessageResult_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkMessageResult'
type MockStore_MarkMessageResult_Call struct {
	*mock.Call
}

// MarkMessageResult is a helper method to define mock.On call
//   - ctx context.Context
//   - agentID string
//   - messageID string
//   - req domain.MessageResultRequest
func (_e *MockStore_Expecter) MarkMessageResult(ctx interface{}, agentID interface{}, messageID interface{}, req interface{}) *MockStore_MarkMessageResult_Call {
	return &MockStore_MarkMessageResult_Call{Call: _e.mock.On("MarkMessageResult", ctx, agentID, messageID, req)}
}

func (_c *MockStore_MarkMessageResult_Call) Run(run func(ctx context.Context, agentID string, messageID string, req domain.MessageResultRequest)) *MockStore_MarkMessageResult_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(domain.MessageResultRequest))
	})
	return _c
}

func (_c *MockStore_MarkMessageResult_Call) Return(_a0 error) *MockStore_MarkMessageResult_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_MarkMessageResult_Call) RunAndReturn(run func(context.Context, string, string, domain.MessageResultRequest) error) *MockStore_MarkMessageResult_Call {
	_c.Call.Return(run)
	return _c
}

// PullMailbox provides a mock function with given fields: ctx, agentID, offset, limit
func (_m *MockStore) PullMailbox(ctx context.Context, agentID string, offset int64, limit int) (domain.MailboxPull, error) {
	ret := _m.Called(ctx, agentID, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for PullMailbox")
	}

	var r0 domain.MailboxPull
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int) (domain.MailboxPull, error)); ok {
		return rf(ctx, agentID, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int) domain.MailboxPull); ok {
		r0 = rf(ctx, agentID, offset, limit)
	} else {
		r0 = ret.Get(0).(domain.MailboxPull)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64, int) error); ok {
		r1 = rf(ctx, agentID, offset, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_PullMailbox_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PullMailbox'
type MockStore_PullMailbox_Call struct {
	*mock.Call
}

// PullMailbox is a helper method to define mock.On call
//   - ctx context.Context
//   - agentID string
//   - offset int64
//   - limit int
func (_e *MockStore_Expecter) PullMailbox(ctx interface{}, agentID interface{}, offset interface{}, limit interface{}) *MockStore_PullMailbox_Call {
	return &MockStore_PullMailbox_Call{Call: _e.mock.On("PullMailbox", ctx, agentID, offset, limit)}
}

func (_c *MockStore_PullMailbox_Call) Run(run func(ctx context.Context, agentID string, offset int64, limit int)) *MockStore_PullMailbox_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64), args[3].(int))
	})
	return _c
}

func (_c *MockStore_PullMailbox_Call) Return(_a0 domain.MailboxPull, _a1 error) *MockStore_PullMailbox_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_PullMailbox_Call) RunAndReturn(run func(context.Context, string, int64, int) (domain.MailboxPull, error)) *MockStore_PullMailbox_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterAgent provides a mock function with given fields: ctx, owner, req, apiKeyHash
func (_m *MockStore) RegisterAgent(ctx context.Context, owner domain.User, req domain.RegisterAgentRequest, apiKeyHash string) (domain.Agent, error) {
	ret := _m.Called(ctx, owner, req, apiKeyHash)

	if len(ret) == 0 {
		panic("no return value specified for RegisterAgent")
	}

	var r0 domain.Agent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.User, domain.RegisterAgentRequest, string) (domain.Agent, error)); ok {
		return rf(ctx, owner, req, apiKeyHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.User, domain.RegisterAgentRequest, string) domain.Agent); ok {
		r0 = rf(ctx, owner, req, apiKeyHash)
	} else {
		r0 = ret.Get(0).(domain.Agent)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.User, domain.RegisterAgentRequest, string) error); ok {
		r1 = rf(ctx, owner, req, apiKeyHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_RegisterAgent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterAgent'
type MockStore_RegisterAgent_Call struct {
	*mock.Call
}

// RegisterAgent is a helper method to define mock.On call
//   - ctx context.Context
//   - owner domain.User
//   - req domain.RegisterAgentRequest
//   - apiKeyHash string
func (_e *MockStore_Expecter) RegisterAgent(ctx interface{}, owner interface{}, req interface{}, apiKeyHash interface{}) *MockStore_RegisterAgent_Call {
	return &MockStore_RegisterAgent_Call{Call: _e.mock.On("RegisterAgent", ctx, owner, req, apiKeyHash)}
}

func (_c *MockStore_RegisterAgent_Call) Run(run func(ctx context.Context, owner domain.User, req domain.RegisterAgentRequest, apiKeyHash string)) *MockStore_RegisterAgent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.User), args[2].(domain.RegisterAgentRequest), args[3].(string))
	})
	return _c
}

func (_c *MockStore_RegisterAgent_Call) Return(_a0 domain.Agent, _a1 error) *MockStore_RegisterAgent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_RegisterAgent_Call) RunAndReturn(run func(context.Context, domain.User, domain.RegisterAgentRequest, string) (domain.Agent, error)) *MockStore_RegisterAgent_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOffset provides a mock function with given fields: ctx, agentID, offset
func (_m *MockStore) UpdateOffset(ctx context.Context, agentID string, offset int64) error {
	ret := _m.Called(ctx, agentID, offset)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOffset")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) error); ok {
		r0 = rf(ctx, agentID, offset)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_UpdateOffset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOffset'
type MockStore_UpdateOffset_Call struct {
	*mock.Call
}

// UpdateOffset is a helper method to define mock.On call
//   - ctx context.Context
//   - agentID string
//   - offset int64
func (_e *MockStore_Expecter) UpdateOffset(ctx interface{}, agentID interface{}, offset interface{}) *MockStore_UpdateOffset_Call {
	return &MockStore_UpdateOffset_Call{Call: _e.mock.On("UpdateOffset", ctx, agentID, offset)}
}

func (_c *MockStore_UpdateOffset_Call) Run(run func(ctx context.Context, agentID string, offset int64)) *MockStore_UpdateOffset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64))
	})
	return _c
}

func (_c *MockStore_UpdateOffset_Call) Return(_a0 error) *MockStore_UpdateOffset_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_UpdateOffset_Call) RunAndReturn(run func(context.Context, string, int64) error) *MockStore_UpdateOffset_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertAgentStatus provides a mock function with given fields: ctx, report
func (_m *MockStore) UpsertAgentStatus(ctx context.Context, report domain.AgentStatusReport) error {
	ret := _m.Called(ctx, report)

	if len(ret) == 0 {
		panic("no return value specified for UpsertAgentStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.AgentStatusReport) error); ok {
		r0 = rf(ctx, report)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_UpsertAgentStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertAgentStatus'
type MockStore_UpsertAgentStatus_Call struct {
	*mock.Call
}

// UpsertAgentStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - report domain.AgentStatusReport
func (_e *MockStore_Expecter) UpsertAgentStatus(ctx interface{}, report interface{}) *MockStore_UpsertAgentStatus_Call {
	return &MockStore_UpsertAgentStatus_Call{Call: _e.mock.On("UpsertAgentStatus", ctx, report)}
}

func (_c *MockStore_UpsertAgentStatus_Call) Run(run func(ctx context.Context, report domain.AgentStatusReport)) *MockStore_UpsertAgentStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.AgentStatusReport))
	})
	return _c
}

func (_c *MockStore_UpsertAgentStatus_Call) Return(_a0 error) *MockStore_UpsertAgentStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_UpsertAgentStatus_Call) RunAndReturn(run func(context.Context, domain.AgentStatusReport) error) *MockStore_UpsertAgentStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
