// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockAdminPolicy is an autogenerated mock type for the AdminPolicy type
type MockAdminPolicy struct {
	mock.Mock
}

type MockAdminPolicy_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAdminPolicy) EXPECT() *MockAdminPolicy_Expecter {
	return &MockAdminPolicy_Expecter{mock: &_m.Mock}
}

// IsAdmin provides a mock function with given fields: email
func (_m *MockAdminPolicy) IsAdmin(email string) bool {
	ret := _m.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for IsAdmin")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(email)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockAdminPolicy_IsAdmin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsAdmin'
type MockAdminPolicy_IsAdmin_Call struct {
	*mock.Call
}

// IsAdmin is a helper method to define mock.On call
//   - email string
func (_e *MockAdminPolicy_Expecter) IsAdmin(email interface{}) *MockAdminPolicy_IsAdmin_Call {
	return &MockAdminPolicy_IsAdmin_Call{Call: _e.mock.On("IsAdmin", email)}
}

func (_c *MockAdminPolicy_IsAdmin_Call) Run(run func(email string)) *MockAdminPolicy_IsAdmin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockAdminPolicy_IsAdmin_Call) Return(_a0 bool) *MockAdminPolicy_IsAdmin_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAdminPolicy_IsAdmin_Call) RunAndReturn(run func(string) bool) *MockAdminPolicy_IsAdmin_Call {
	_c.Call.Return(run)
	return _c
}

// RoleForEmail provides a mock function with given fields: email
func (_m *MockAdminPolicy) RoleForEmail(email string) string {
	ret := _m.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for RoleForEmail")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(email)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockAdminPolicy_RoleForEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RoleForEmail'
type MockAdminPolicy_RoleForEmail_Call struct {
	*mock.Call
}

// RoleForEmail is a helper method to define mock.On call
//   - email string
func (_e *MockAdminPolicy_Expecter) RoleForEmail(email interface{}) *MockAdminPolicy_RoleForEmail_Call {
	return &MockAdminPolicy_RoleForEmail_Call{Call: _e.mock.On("RoleForEmail", email)}
}

func (_c *MockAdminPolicy_RoleForEmail_Call) Run(run func(email string)) *MockAdminPolicy_RoleForEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockAdminPolicy_RoleForEmail_Call) Return(_a0 string) *MockAdminPolicy_RoleForEmail_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAdminPolicy_RoleForEmail_Call) RunAndReturn(run func(string) string) *MockAdminPolicy_RoleForEmail_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAdminPolicy creates a new instance of MockAdminPolicy. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAdminPolicy(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAdminPolicy {
	mock := &MockAdminPolicy{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
