// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/pax-beehive/pax-manager/internal/manager/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockRegistrationTokenStore is an autogenerated mock type for the RegistrationTokenStore type
type MockRegistrationTokenStore struct {
	mock.Mock
}

type MockRegistrationTokenStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRegistrationTokenStore) EXPECT() *MockRegistrationTokenStore_Expecter {
	return &MockRegistrationTokenStore_Expecter{mock: &_m.Mock}
}

// ResolveRegistrationToken provides a mock function with given fields: ctx, tokenHash
func (_m *MockRegistrationTokenStore) ResolveRegistrationToken(ctx context.Context, tokenHash string) (domain.User, error) {
	ret := _m.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for ResolveRegistrationToken")
	}

	var r0 domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.User, error)); ok {
		return rf(ctx, tokenHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.User); ok {
		r0 = rf(ctx, tokenHash)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tokenHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRegistrationTokenStore_ResolveRegistrationToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveRegistrationToken'
type MockRegistrationTokenStore_ResolveRegistrationToken_Call struct {
	*mock.Call
}

// ResolveRegistrationToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *MockRegistrationTokenStore_Expecter) ResolveRegistrationToken(ctx interface{}, tokenHash interface{}) *MockRegistrationTokenStore_ResolveRegistrationToken_Call {
	return &MockRegistrationTokenStore_ResolveRegistrationToken_Call{Call: _e.mock.On("ResolveRegistrationToken", ctx, tokenHash)}
}

func (_c *MockRegistrationTokenStore_ResolveRegistrationToken_Call) Run(run func(ctx context.Context, tokenHash string)) *MockRegistrationTokenStore_ResolveRegistrationToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRegistrationTokenStore_ResolveRegistrationToken_Call) Return(_a0 domain.User, _a1 error) *MockRegistrationTokenStore_ResolveRegistrationToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRegistrationTokenStore_ResolveRegistrationToken_Call) RunAndReturn(run func(context.Context, string) (domain.User, error)) *MockRegistrationTokenStore_ResolveRegistrationToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRegistrationTokenStore creates a new instance of MockRegistrationTokenStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRegistrationTokenStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRegistrationTokenStore {
	mock := &MockRegistrationTokenStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
