// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/pax-beehive/pax-manager/internal/manager/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockUserStore is an autogenerated mock type for the UserStore type
type MockUserStore struct {
	mock.Mock
}

type MockUserStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserStore) EXPECT() *MockUserStore_Expecter {
	return &MockUserStore_Expecter{mock: &_m.Mock}
}

// EnsureUser provides a mock function with given fields: ctx, email, displayName, role
func (_m *MockUserStore) EnsureUser(ctx context.Context, email string, displayName string, role string) (domain.User, error) {
	ret := _m.Called(ctx, email, displayName, role)

	if len(ret) == 0 {
		panic("no return value specified for EnsureUser")
	}

	var r0 domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (domain.User, error)); ok {
		return rf(ctx, email, displayName, role)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) domain.User); ok {
		r0 = rf(ctx, email, displayName, role)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, email, displayName, role)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserStore_EnsureUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureUser'
type MockUserStore_EnsureUser_Call struct {
	*mock.Call
}

// EnsureUser is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - displayName string
//   - role string
func (_e *MockUserStore_Expecter) EnsureUser(ctx interface{}, email interface{}, displayName interface{}, role interface{}) *MockUserStore_EnsureUser_Call {
	return &MockUserStore_EnsureUser_Call{Call: _e.mock.On("EnsureUser", ctx, email, displayName, role)}
}

func (_c *MockUserStore_EnsureUser_Call) Run(run func(ctx context.Context, email string, displayName string, role string)) *MockUserStore_EnsureUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockUserStore_EnsureUser_Call) Return(_a0 domain.User, _a1 error) *MockUserStore_EnsureUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserStore_EnsureUser_Call) RunAndReturn(run func(context.Context, string, string, string) (domain.User, error)) *MockUserStore_EnsureUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserStore creates a new instance of MockUserStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserStore {
	mock := &MockUserStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
