// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	auth "github.com/pax-beehive/pax-manager/internal/manager/auth"
	mock "github.com/stretchr/testify/mock"
)

// MockUserIdentityVerifier is an autogenerated mock type for the UserIdentityVerifier type
type MockUserIdentityVerifier struct {
	mock.Mock
}

type MockUserIdentityVerifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserIdentityVerifier) EXPECT() *MockUserIdentityVerifier_Expecter {
	return &MockUserIdentityVerifier_Expecter{mock: &_m.Mock}
}

// Verify provides a mock function with given fields: ctx, token
func (_m *MockUserIdentityVerifier) Verify(ctx context.Context, token string) (auth.UserIdentity, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 auth.UserIdentity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (auth.UserIdentity, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) auth.UserIdentity); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Get(0).(auth.UserIdentity)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserIdentityVerifier_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type MockUserIdentityVerifier_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockUserIdentityVerifier_Expecter) Verify(ctx interface{}, token interface{}) *MockUserIdentityVerifier_Verify_Call {
	return &MockUserIdentityVerifier_Verify_Call{Call: _e.mock.On("Verify", ctx, token)}
}

func (_c *MockUserIdentityVerifier_Verify_Call) Run(run func(ctx context.Context, token string)) *MockUserIdentityVerifier_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserIdentityVerifier_Verify_Call) Return(_a0 auth.UserIdentity, _a1 error) *MockUserIdentityVerifier_Verify_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserIdentityVerifier_Verify_Call) RunAndReturn(run func(context.Context, string) (auth.UserIdentity, error)) *MockUserIdentityVerifier_Verify_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserIdentityVerifier creates a new instance of MockUserIdentityVerifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserIdentityVerifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserIdentityVerifier {
	mock := &MockUserIdentityVerifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
