// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/pax-beehive/pax-manager/internal/manager/storage/dal/model"
)

func newAgentRegistrationToken(db *gorm.DB, opts ...gen.DOOption) agentRegistrationToken {
	_agentRegistrationToken := agentRegistrationToken{}

	_agentRegistrationToken.agentRegistrationTokenDo.UseDB(db, opts...)
	_agentRegistrationToken.agentRegistrationTokenDo.UseModel(&model.AgentRegistrationToken{})

	tableName := _agentRegistrationToken.agentRegistrationTokenDo.TableName()
	_agentRegistrationToken.ALL = field.NewAsterisk(tableName)
	_agentRegistrationToken.TokenHash = field.NewString(tableName, "token_hash")
	_agentRegistrationToken.OwnerUserID = field.NewString(tableName, "owner_user_id")
	_agentRegistrationToken.ExpiresAt = field.NewTime(tableName, "expires_at")
	_agentRegistrationToken.UsedAt = field.NewTime(tableName, "used_at")
	_agentRegistrationToken.CreatedAt = field.NewTime(tableName, "created_at")

	_agentRegistrationToken.fillFieldMap()

	return _agentRegistrationToken
}

type agentRegistrationToken struct {
	agentRegistrationTokenDo agentRegistrationTokenDo

	ALL         field.Asterisk
	TokenHash   field.String
	OwnerUserID field.String
	ExpiresAt   field.Time
	UsedAt      field.Time
	CreatedAt   field.Time

	fieldMap map[string]field.Expr
}

func (a agentRegistrationToken) Table(newTableName string) *agentRegistrationToken {
	a.agentRegistrationTokenDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a agentRegistrationToken) As(alias string) *agentRegistrationToken {
	a.agentRegistrationTokenDo.DO = *(a.agentRegistrationTokenDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *agentRegistrationToken) updateTableName(table string) *agentRegistrationToken {
	a.ALL = field.NewAsterisk(table)
	a.TokenHash = field.NewString(table, "token_hash")
	a.OwnerUserID = field.NewString(table, "owner_user_id")
	a.ExpiresAt = field.NewTime(table, "expires_at")
	a.UsedAt = field.NewTime(table, "used_at")
	a.CreatedAt = field.NewTime(table, "created_at")

	a.fillFieldMap()

	return a
}

func (a *agentRegistrationToken) WithContext(ctx context.Context) IAgentRegistrationTokenDo {
	return a.agentRegistrationTokenDo.WithContext(ctx)
}

func (a agentRegistrationToken) TableName() string { return a.agentRegistrationTokenDo.TableName() }

func (a agentRegistrationToken) Alias() string { return a.agentRegistrationTokenDo.Alias() }

func (a agentRegistrationToken) Columns(cols ...field.Expr) gen.Columns {
	return a.agentRegistrationTokenDo.Columns(cols...)
}

func (a *agentRegistrationToken) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *agentRegistrationToken) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 5)
	a.fieldMap["token_hash"] = a.TokenHash
	a.fieldMap["owner_user_id"] = a.OwnerUserID
	a.fieldMap["expires_at"] = a.ExpiresAt
	a.fieldMap["used_at"] = a.UsedAt
	a.fieldMap["created_at"] = a.CreatedAt
}

func (a agentRegistrationToken) clone(db *gorm.DB) agentRegistrationToken {
	a.agentRegistrationTokenDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a agentRegistrationToken) replaceDB(db *gorm.DB) agentRegistrationToken {
	a.agentRegistrationTokenDo.ReplaceDB(db)
	return a
}

type agentRegistrationTokenDo struct{ gen.DO }

type IAgentRegistrationTokenDo interface {
	gen.SubQuery
	Debug() IAgentRegistrationTokenDo
	WithContext(ctx context.Context) IAgentRegistrationTokenDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAgentRegistrationTokenDo
	WriteDB() IAgentRegistrationTokenDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAgentRegistrationTokenDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAgentRegistrationTokenDo
	Not(conds ...gen.Condition) IAgentRegistrationTokenDo
	Or(conds ...gen.Condition) IAgentRegistrationTokenDo
	Select(conds ...field.Expr) IAgentRegistrationTokenDo
	Where(conds ...gen.Condition) IAgentRegistrationTokenDo
	Order(conds ...field.Expr) IAgentRegistrationTokenDo
	Distinct(cols ...field.Expr) IAgentRegistrationTokenDo
	Omit(cols ...field.Expr) IAgentRegistrationTokenDo
	Join(table schema.Tabler, on ...field.Expr) IAgentRegistrationTokenDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAgentRegistrationTokenDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAgentRegistrationTokenDo
	Group(cols ...field.Expr) IAgentRegistrationTokenDo
	Having(conds ...gen.Condition) IAgentRegistrationTokenDo
	Limit(limit int) IAgentRegistrationTokenDo
	Offset(offset int) IAgentRegistrationTokenDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAgentRegistrationTokenDo
	Unscoped() IAgentRegistrationTokenDo
	Create(values ...*model.AgentRegistrationToken) error
	CreateInBatches(values []*model.AgentRegistrationToken, batchSize int) error
	Save(values ...*model.AgentRegistrationToken) error
	First() (*model.AgentRegistrationToken, error)
	Take() (*model.AgentRegistrationToken, error)
	Last() (*model.AgentRegistrationToken, error)
	Find() ([]*model.AgentRegistrationToken, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AgentRegistrationToken, err error)
	FindInBatches(result *[]*model.AgentRegistrationToken, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.AgentRegistrationToken) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAgentRegistrationTokenDo
	Assign(attrs ...field.AssignExpr) IAgentRegistrationTokenDo
	Joins(fields ...field.RelationField) IAgentRegistrationTokenDo
	Preload(fields ...field.RelationField) IAgentRegistrationTokenDo
	FirstOrInit() (*model.AgentRegistrationToken, error)
	FirstOrCreate() (*model.AgentRegistrationToken, error)
	FindByPage(offset int, limit int) (result []*model.AgentRegistrationToken, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAgentRegistrationTokenDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a agentRegistrationTokenDo) Debug() IAgentRegistrationTokenDo {
	return a.withDO(a.DO.Debug())
}

func (a agentRegistrationTokenDo) WithContext(ctx context.Context) IAgentRegistrationTokenDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a agentRegistrationTokenDo) ReadDB() IAgentRegistrationTokenDo {
	return a.Clauses(dbresolver.Read)
}

func (a agentRegistrationTokenDo) WriteDB() IAgentRegistrationTokenDo {
	return a.Clauses(dbresolver.Write)
}

func (a agentRegistrationTokenDo) Session(config *gorm.Session) IAgentRegistrationTokenDo {
	return a.withDO(a.DO.Session(config))
}

func (a agentRegistrationTokenDo) Clauses(conds ...clause.Expression) IAgentRegistrationTokenDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a agentRegistrationTokenDo) Returning(value interface{}, columns ...string) IAgentRegistrationTokenDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a agentRegistrationTokenDo) Not(conds ...gen.Condition) IAgentRegistrationTokenDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a agentRegistrationTokenDo) Or(conds ...gen.Condition) IAgentRegistrationTokenDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a agentRegistrationTokenDo) Select(conds ...field.Expr) IAgentRegistrationTokenDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a agentRegistrationTokenDo) Where(conds ...gen.Condition) IAgentRegistrationTokenDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a agentRegistrationTokenDo) Order(conds ...field.Expr) IAgentRegistrationTokenDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a agentRegistrationTokenDo) Distinct(cols ...field.Expr) IAgentRegistrationTokenDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a agentRegistrationTokenDo) Omit(cols ...field.Expr) IAgentRegistrationTokenDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a agentRegistrationTokenDo) Join(table schema.Tabler, on ...field.Expr) IAgentRegistrationTokenDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a agentRegistrationTokenDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAgentRegistrationTokenDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a agentRegistrationTokenDo) RightJoin(table schema.Tabler, on ...field.Expr) IAgentRegistrationTokenDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a agentRegistrationTokenDo) Group(cols ...field.Expr) IAgentRegistrationTokenDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a agentRegistrationTokenDo) Having(conds ...gen.Condition) IAgentRegistrationTokenDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a agentRegistrationTokenDo) Limit(limit int) IAgentRegistrationTokenDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a agentRegistrationTokenDo) Offset(offset int) IAgentRegistrationTokenDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a agentRegistrationTokenDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAgentRegistrationTokenDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a agentRegistrationTokenDo) Unscoped() IAgentRegistrationTokenDo {
	return a.withDO(a.DO.Unscoped())
}

func (a agentRegistrationTokenDo) Create(values ...*model.AgentRegistrationToken) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a agentRegistrationTokenDo) CreateInBatches(values []*model.AgentRegistrationToken, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a agentRegistrationTokenDo) Save(values ...*model.AgentRegistrationToken) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a agentRegistrationTokenDo) First() (*model.AgentRegistrationToken, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AgentRegistrationToken), nil
	}
}

func (a agentRegistrationTokenDo) Take() (*model.AgentRegistrationToken, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AgentRegistrationToken), nil
	}
}

func (a agentRegistrationTokenDo) Last() (*model.AgentRegistrationToken, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AgentRegistrationToken), nil
	}
}

func (a agentRegistrationTokenDo) Find() ([]*model.AgentRegistrationToken, error) {
	result, err := a.DO.Find()
	return result.([]*model.AgentRegistrationToken), err
}

func (a agentRegistrationTokenDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AgentRegistrationToken, err error) {
	buf := make([]*model.AgentRegistrationToken, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a agentRegistrationTokenDo) FindInBatches(result *[]*model.AgentRegistrationToken, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a agentRegistrationTokenDo) Attrs(attrs ...field.AssignExpr) IAgentRegistrationTokenDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a agentRegistrationTokenDo) Assign(attrs ...field.AssignExpr) IAgentRegistrationTokenDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a agentRegistrationTokenDo) Joins(fields ...field.RelationField) IAgentRegistrationTokenDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a agentRegistrationTokenDo) Preload(fields ...field.RelationField) IAgentRegistrationTokenDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a agentRegistrationTokenDo) FirstOrInit() (*model.AgentRegistrationToken, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AgentRegistrationToken), nil
	}
}

func (a agentRegistrationTokenDo) FirstOrCreate() (*model.AgentRegistrationToken, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AgentRegistrationToken), nil
	}
}

func (a agentRegistrationTokenDo) FindByPage(offset int, limit int) (result []*model.AgentRegistrationToken, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a agentRegistrationTokenDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a agentRegistrationTokenDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a agentRegistrationTokenDo) Delete(models ...*model.AgentRegistrationToken) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *agentRegistrationTokenDo) withDO(do gen.Dao) *agentRegistrationTokenDo {
	a.DO = *do.(*gen.DO)
	return a
}
