// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/pax-beehive/pax-manager/internal/manager/storage/dal/model"
)

func newKnowledgeCapsule(db *gorm.DB, opts ...gen.DOOption) knowledgeCapsule {
	_knowledgeCapsule := knowledgeCapsule{}

	_knowledgeCapsule.knowledgeCapsuleDo.UseDB(db, opts...)
	_knowledgeCapsule.knowledgeCapsuleDo.UseModel(&model.KnowledgeCapsule{})

	tableName := _knowledgeCapsule.knowledgeCapsuleDo.TableName()
	_knowledgeCapsule.ALL = field.NewAsterisk(tableName)
	_knowledgeCapsule.CapsuleID = field.NewString(tableName, "capsule_id")
	_knowledgeCapsule.OwnerUserID = field.NewString(tableName, "owner_user_id")
	_knowledgeCapsule.SourceSessionID = field.NewString(tableName, "source_session_id")
	_knowledgeCapsule.SourceAgentID = field.NewString(tableName, "source_agent_id")
	_knowledgeCapsule.SourceNodeID = field.NewString(tableName, "source_node_id")
	_knowledgeCapsule.CreatedByUserID = field.NewString(tableName, "created_by_user_id")
	_knowledgeCapsule.Keyword = field.NewString(tableName, "keyword")
	_knowledgeCapsule.Title = field.NewString(tableName, "title")
	_knowledgeCapsule.Summary = field.NewString(tableName, "summary")
	_knowledgeCapsule.Content = field.NewString(tableName, "content")
	_knowledgeCapsule.SuggestedSkillsJSON = field.NewString(tableName, "suggested_skills_json")
	_knowledgeCapsule.ReferencesJSON = field.NewString(tableName, "references_json")
	_knowledgeCapsule.OpenQuestionsJSON = field.NewString(tableName, "open_questions_json")
	_knowledgeCapsule.RisksJSON = field.NewString(tableName, "risks_json")
	_knowledgeCapsule.RedactionsJSON = field.NewString(tableName, "redactions_json")
	_knowledgeCapsule.Status = field.NewString(tableName, "status")
	_knowledgeCapsule.Truncated = field.NewBool(tableName, "truncated")
	_knowledgeCapsule.OriginalEstimatedChars = field.NewInt64(tableName, "original_estimated_chars")
	_knowledgeCapsule.CreatedAt = field.NewTime(tableName, "created_at")
	_knowledgeCapsule.ArchivedAt = field.NewTime(tableName, "archived_at")

	_knowledgeCapsule.fillFieldMap()

	return _knowledgeCapsule
}

type knowledgeCapsule struct {
	knowledgeCapsuleDo knowledgeCapsuleDo

	ALL                    field.Asterisk
	CapsuleID              field.String
	OwnerUserID            field.String
	SourceSessionID        field.String
	SourceAgentID          field.String
	SourceNodeID           field.String
	CreatedByUserID        field.String
	Keyword                field.String
	Title                  field.String
	Summary                field.String
	Content                field.String
	SuggestedSkillsJSON    field.String
	ReferencesJSON         field.String
	OpenQuestionsJSON      field.String
	RisksJSON              field.String
	RedactionsJSON         field.String
	Status                 field.String
	Truncated              field.Bool
	OriginalEstimatedChars field.Int64
	CreatedAt              field.Time
	ArchivedAt             field.Time

	fieldMap map[string]field.Expr
}

func (k knowledgeCapsule) Table(newTableName string) *knowledgeCapsule {
	k.knowledgeCapsuleDo.UseTable(newTableName)
	return k.updateTableName(newTableName)
}

func (k knowledgeCapsule) As(alias string) *knowledgeCapsule {
	k.knowledgeCapsuleDo.DO = *(k.knowledgeCapsuleDo.As(alias).(*gen.DO))
	return k.updateTableName(alias)
}

func (k *knowledgeCapsule) updateTableName(table string) *knowledgeCapsule {
	k.ALL = field.NewAsterisk(table)
	k.CapsuleID = field.NewString(table, "capsule_id")
	k.OwnerUserID = field.NewString(table, "owner_user_id")
	k.SourceSessionID = field.NewString(table, "source_session_id")
	k.SourceAgentID = field.NewString(table, "source_agent_id")
	k.SourceNodeID = field.NewString(table, "source_node_id")
	k.CreatedByUserID = field.NewString(table, "created_by_user_id")
	k.Keyword = field.NewString(table, "keyword")
	k.Title = field.NewString(table, "title")
	k.Summary = field.NewString(table, "summary")
	k.Content = field.NewString(table, "content")
	k.SuggestedSkillsJSON = field.NewString(table, "suggested_skills_json")
	k.ReferencesJSON = field.NewString(table, "references_json")
	k.OpenQuestionsJSON = field.NewString(table, "open_questions_json")
	k.RisksJSON = field.NewString(table, "risks_json")
	k.RedactionsJSON = field.NewString(table, "redactions_json")
	k.Status = field.NewString(table, "status")
	k.Truncated = field.NewBool(table, "truncated")
	k.OriginalEstimatedChars = field.NewInt64(table, "original_estimated_chars")
	k.CreatedAt = field.NewTime(table, "created_at")
	k.ArchivedAt = field.NewTime(table, "archived_at")

	k.fillFieldMap()

	return k
}

func (k *knowledgeCapsule) WithContext(ctx context.Context) IKnowledgeCapsuleDo {
	return k.knowledgeCapsuleDo.WithContext(ctx)
}

func (k knowledgeCapsule) TableName() string { return k.knowledgeCapsuleDo.TableName() }

func (k knowledgeCapsule) Alias() string { return k.knowledgeCapsuleDo.Alias() }

func (k knowledgeCapsule) Columns(cols ...field.Expr) gen.Columns {
	return k.knowledgeCapsuleDo.Columns(cols...)
}

func (k *knowledgeCapsule) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := k.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (k *knowledgeCapsule) fillFieldMap() {
	k.fieldMap = make(map[string]field.Expr, 20)
	k.fieldMap["capsule_id"] = k.CapsuleID
	k.fieldMap["owner_user_id"] = k.OwnerUserID
	k.fieldMap["source_session_id"] = k.SourceSessionID
	k.fieldMap["source_agent_id"] = k.SourceAgentID
	k.fieldMap["source_node_id"] = k.SourceNodeID
	k.fieldMap["created_by_user_id"] = k.CreatedByUserID
	k.fieldMap["keyword"] = k.Keyword
	k.fieldMap["title"] = k.Title
	k.fieldMap["summary"] = k.Summary
	k.fieldMap["content"] = k.Content
	k.fieldMap["suggested_skills_json"] = k.SuggestedSkillsJSON
	k.fieldMap["references_json"] = k.ReferencesJSON
	k.fieldMap["open_questions_json"] = k.OpenQuestionsJSON
	k.fieldMap["risks_json"] = k.RisksJSON
	k.fieldMap["redactions_json"] = k.RedactionsJSON
	k.fieldMap["status"] = k.Status
	k.fieldMap["truncated"] = k.Truncated
	k.fieldMap["original_estimated_chars"] = k.OriginalEstimatedChars
	k.fieldMap["created_at"] = k.CreatedAt
	k.fieldMap["archived_at"] = k.ArchivedAt
}

func (k knowledgeCapsule) clone(db *gorm.DB) knowledgeCapsule {
	k.knowledgeCapsuleDo.ReplaceConnPool(db.Statement.ConnPool)
	return k
}

func (k knowledgeCapsule) replaceDB(db *gorm.DB) knowledgeCapsule {
	k.knowledgeCapsuleDo.ReplaceDB(db)
	return k
}

type knowledgeCapsuleDo struct{ gen.DO }

type IKnowledgeCapsuleDo interface {
	gen.SubQuery
	Debug() IKnowledgeCapsuleDo
	WithContext(ctx context.Context) IKnowledgeCapsuleDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IKnowledgeCapsuleDo
	WriteDB() IKnowledgeCapsuleDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IKnowledgeCapsuleDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IKnowledgeCapsuleDo
	Not(conds ...gen.Condition) IKnowledgeCapsuleDo
	Or(conds ...gen.Condition) IKnowledgeCapsuleDo
	Select(conds ...field.Expr) IKnowledgeCapsuleDo
	Where(conds ...gen.Condition) IKnowledgeCapsuleDo
	Order(conds ...field.Expr) IKnowledgeCapsuleDo
	Distinct(cols ...field.Expr) IKnowledgeCapsuleDo
	Omit(cols ...field.Expr) IKnowledgeCapsuleDo
	Join(table schema.Tabler, on ...field.Expr) IKnowledgeCapsuleDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IKnowledgeCapsuleDo
	RightJoin(table schema.Tabler, on ...field.Expr) IKnowledgeCapsuleDo
	Group(cols ...field.Expr) IKnowledgeCapsuleDo
	Having(conds ...gen.Condition) IKnowledgeCapsuleDo
	Limit(limit int) IKnowledgeCapsuleDo
	Offset(offset int) IKnowledgeCapsuleDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IKnowledgeCapsuleDo
	Unscoped() IKnowledgeCapsuleDo
	Create(values ...*model.KnowledgeCapsule) error
	CreateInBatches(values []*model.KnowledgeCapsule, batchSize int) error
	Save(values ...*model.KnowledgeCapsule) error
	First() (*model.KnowledgeCapsule, error)
	Take() (*model.KnowledgeCapsule, error)
	Last() (*model.KnowledgeCapsule, error)
	Find() ([]*model.KnowledgeCapsule, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.KnowledgeCapsule, err error)
	FindInBatches(result *[]*model.KnowledgeCapsule, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.KnowledgeCapsule) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IKnowledgeCapsuleDo
	Assign(attrs ...field.AssignExpr) IKnowledgeCapsuleDo
	Joins(fields ...field.RelationField) IKnowledgeCapsuleDo
	Preload(fields ...field.RelationField) IKnowledgeCapsuleDo
	FirstOrInit() (*model.KnowledgeCapsule, error)
	FirstOrCreate() (*model.KnowledgeCapsule, error)
	FindByPage(offset int, limit int) (result []*model.KnowledgeCapsule, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IKnowledgeCapsuleDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (k knowledgeCapsuleDo) Debug() IKnowledgeCapsuleDo {
	return k.withDO(k.DO.Debug())
}

func (k knowledgeCapsuleDo) WithContext(ctx context.Context) IKnowledgeCapsuleDo {
	return k.withDO(k.DO.WithContext(ctx))
}

func (k knowledgeCapsuleDo) ReadDB() IKnowledgeCapsuleDo {
	return k.Clauses(dbresolver.Read)
}

func (k knowledgeCapsuleDo) WriteDB() IKnowledgeCapsuleDo {
	return k.Clauses(dbresolver.Write)
}

func (k knowledgeCapsuleDo) Session(config *gorm.Session) IKnowledgeCapsuleDo {
	return k.withDO(k.DO.Session(config))
}

func (k knowledgeCapsuleDo) Clauses(conds ...clause.Expression) IKnowledgeCapsuleDo {
	return k.withDO(k.DO.Clauses(conds...))
}

func (k knowledgeCapsuleDo) Returning(value interface{}, columns ...string) IKnowledgeCapsuleDo {
	return k.withDO(k.DO.Returning(value, columns...))
}

func (k knowledgeCapsuleDo) Not(conds ...gen.Condition) IKnowledgeCapsuleDo {
	return k.withDO(k.DO.Not(conds...))
}

func (k knowledgeCapsuleDo) Or(conds ...gen.Condition) IKnowledgeCapsuleDo {
	return k.withDO(k.DO.Or(conds...))
}

func (k knowledgeCapsuleDo) Select(conds ...field.Expr) IKnowledgeCapsuleDo {
	return k.withDO(k.DO.Select(conds...))
}

func (k knowledgeCapsuleDo) Where(conds ...gen.Condition) IKnowledgeCapsuleDo {
	return k.withDO(k.DO.Where(conds...))
}

func (k knowledgeCapsuleDo) Order(conds ...field.Expr) IKnowledgeCapsuleDo {
	return k.withDO(k.DO.Order(conds...))
}

func (k knowledgeCapsuleDo) Distinct(cols ...field.Expr) IKnowledgeCapsuleDo {
	return k.withDO(k.DO.Distinct(cols...))
}

func (k knowledgeCapsuleDo) Omit(cols ...field.Expr) IKnowledgeCapsuleDo {
	return k.withDO(k.DO.Omit(cols...))
}

func (k knowledgeCapsuleDo) Join(table schema.Tabler, on ...field.Expr) IKnowledgeCapsuleDo {
	return k.withDO(k.DO.Join(table, on...))
}

func (k knowledgeCapsuleDo) LeftJoin(table schema.Tabler, on ...field.Expr) IKnowledgeCapsuleDo {
	return k.withDO(k.DO.LeftJoin(table, on...))
}

func (k knowledgeCapsuleDo) RightJoin(table schema.Tabler, on ...field.Expr) IKnowledgeCapsuleDo {
	return k.withDO(k.DO.RightJoin(table, on...))
}

func (k knowledgeCapsuleDo) Group(cols ...field.Expr) IKnowledgeCapsuleDo {
	return k.withDO(k.DO.Group(cols...))
}

func (k knowledgeCapsuleDo) Having(conds ...gen.Condition) IKnowledgeCapsuleDo {
	return k.withDO(k.DO.Having(conds...))
}

func (k knowledgeCapsuleDo) Limit(limit int) IKnowledgeCapsuleDo {
	return k.withDO(k.DO.Limit(limit))
}

func (k knowledgeCapsuleDo) Offset(offset int) IKnowledgeCapsuleDo {
	return k.withDO(k.DO.Offset(offset))
}

func (k knowledgeCapsuleDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IKnowledgeCapsuleDo {
	return k.withDO(k.DO.Scopes(funcs...))
}

func (k knowledgeCapsuleDo) Unscoped() IKnowledgeCapsuleDo {
	return k.withDO(k.DO.Unscoped())
}

func (k knowledgeCapsuleDo) Create(values ...*model.KnowledgeCapsule) error {
	if len(values) == 0 {
		return nil
	}
	return k.DO.Create(values)
}

func (k knowledgeCapsuleDo) CreateInBatches(values []*model.KnowledgeCapsule, batchSize int) error {
	return k.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (k knowledgeCapsuleDo) Save(values ...*model.KnowledgeCapsule) error {
	if len(values) == 0 {
		return nil
	}
	return k.DO.Save(values)
}

func (k knowledgeCapsuleDo) First() (*model.KnowledgeCapsule, error) {
	if result, err := k.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.KnowledgeCapsule), nil
	}
}

func (k knowledgeCapsuleDo) Take() (*model.KnowledgeCapsule, error) {
	if result, err := k.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.KnowledgeCapsule), nil
	}
}

func (k knowledgeCapsuleDo) Last() (*model.KnowledgeCapsule, error) {
	if result, err := k.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.KnowledgeCapsule), nil
	}
}

func (k knowledgeCapsuleDo) Find() ([]*model.KnowledgeCapsule, error) {
	result, err := k.DO.Find()
	return result.([]*model.KnowledgeCapsule), err
}

func (k knowledgeCapsuleDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.KnowledgeCapsule, err error) {
	buf := make([]*model.KnowledgeCapsule, 0, batchSize)
	err = k.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (k knowledgeCapsuleDo) FindInBatches(result *[]*model.KnowledgeCapsule, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return k.DO.FindInBatches(result, batchSize, fc)
}

func (k knowledgeCapsuleDo) Attrs(attrs ...field.AssignExpr) IKnowledgeCapsuleDo {
	return k.withDO(k.DO.Attrs(attrs...))
}

func (k knowledgeCapsuleDo) Assign(attrs ...field.AssignExpr) IKnowledgeCapsuleDo {
	return k.withDO(k.DO.Assign(attrs...))
}

func (k knowledgeCapsuleDo) Joins(fields ...field.RelationField) IKnowledgeCapsuleDo {
	for _, _f := range fields {
		k = *k.withDO(k.DO.Joins(_f))
	}
	return &k
}

func (k knowledgeCapsuleDo) Preload(fields ...field.RelationField) IKnowledgeCapsuleDo {
	for _, _f := range fields {
		k = *k.withDO(k.DO.Preload(_f))
	}
	return &k
}

func (k knowledgeCapsuleDo) FirstOrInit() (*model.KnowledgeCapsule, error) {
	if result, err := k.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.KnowledgeCapsule), nil
	}
}

func (k knowledgeCapsuleDo) FirstOrCreate() (*model.KnowledgeCapsule, error) {
	if result, err := k.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.KnowledgeCapsule), nil
	}
}

func (k knowledgeCapsuleDo) FindByPage(offset int, limit int) (result []*model.KnowledgeCapsule, count int64, err error) {
	result, err = k.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = k.Offset(-1).Limit(-1).Count()
	return
}

func (k knowledgeCapsuleDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = k.Count()
	if err != nil {
		return
	}

	err = k.Offset(offset).Limit(limit).Scan(result)
	return
}

func (k knowledgeCapsuleDo) Scan(result interface{}) (err error) {
	return k.DO.Scan(result)
}

func (k knowledgeCapsuleDo) Delete(models ...*model.KnowledgeCapsule) (result gen.ResultInfo, err error) {
	return k.DO.Delete(models)
}

func (k *knowledgeCapsuleDo) withDO(do gen.Dao) *knowledgeCapsuleDo {
	k.DO = *do.(*gen.DO)
	return k
}
