// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/pax-beehive/pax-manager/internal/manager/storage/dal/model"
)

func newMailbox(db *gorm.DB, opts ...gen.DOOption) mailbox {
	_mailbox := mailbox{}

	_mailbox.mailboxDo.UseDB(db, opts...)
	_mailbox.mailboxDo.UseModel(&model.Mailbox{})

	tableName := _mailbox.mailboxDo.TableName()
	_mailbox.ALL = field.NewAsterisk(tableName)
	_mailbox.ID = field.NewInt64(tableName, "id")
	_mailbox.MessageID = field.NewString(tableName, "message_id")
	_mailbox.UserID = field.NewString(tableName, "user_id")
	_mailbox.OwnerUserID = field.NewString(tableName, "owner_user_id")
	_mailbox.AgentID = field.NewString(tableName, "agent_id")
	_mailbox.SessionID = field.NewString(tableName, "session_id")
	_mailbox.Message = field.NewString(tableName, "message")
	_mailbox.MessageType = field.NewString(tableName, "message_type")
	_mailbox.Payload = field.NewString(tableName, "payload")
	_mailbox.Status = field.NewString(tableName, "status")
	_mailbox.DeliveredAt = field.NewTime(tableName, "delivered_at")
	_mailbox.CompletedAt = field.NewTime(tableName, "completed_at")
	_mailbox.Result = field.NewString(tableName, "result")
	_mailbox.Error = field.NewString(tableName, "error")
	_mailbox.CreatedAt = field.NewTime(tableName, "created_at")
	_mailbox.ExpiresAt = field.NewTime(tableName, "expires_at")
	_mailbox.NodeID = field.NewString(tableName, "node_id")
	_mailbox.Direction = field.NewString(tableName, "direction")
	_mailbox.ParentMessageID = field.NewString(tableName, "parent_message_id")
	_mailbox.TurnID = field.NewString(tableName, "turn_id")
	_mailbox.ResponseID = field.NewString(tableName, "response_id")
	_mailbox.Events = field.NewString(tableName, "events")
	_mailbox.FileChanges = field.NewString(tableName, "file_changes")
	_mailbox.TokenUsage = field.NewString(tableName, "token_usage")

	_mailbox.fillFieldMap()

	return _mailbox
}

type mailbox struct {
	mailboxDo mailboxDo

	ALL             field.Asterisk
	ID              field.Int64
	MessageID       field.String
	UserID          field.String
	OwnerUserID     field.String
	AgentID         field.String
	SessionID       field.String
	Message         field.String
	MessageType     field.String
	Payload         field.String
	Status          field.String
	DeliveredAt     field.Time
	CompletedAt     field.Time
	Result          field.String
	Error           field.String
	CreatedAt       field.Time
	ExpiresAt       field.Time
	NodeID          field.String
	Direction       field.String
	ParentMessageID field.String
	TurnID          field.String
	ResponseID      field.String
	Events          field.String
	FileChanges     field.String
	TokenUsage      field.String

	fieldMap map[string]field.Expr
}

func (m mailbox) Table(newTableName string) *mailbox {
	m.mailboxDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m mailbox) As(alias string) *mailbox {
	m.mailboxDo.DO = *(m.mailboxDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *mailbox) updateTableName(table string) *mailbox {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewInt64(table, "id")
	m.MessageID = field.NewString(table, "message_id")
	m.UserID = field.NewString(table, "user_id")
	m.OwnerUserID = field.NewString(table, "owner_user_id")
	m.AgentID = field.NewString(table, "agent_id")
	m.SessionID = field.NewString(table, "session_id")
	m.Message = field.NewString(table, "message")
	m.MessageType = field.NewString(table, "message_type")
	m.Payload = field.NewString(table, "payload")
	m.Status = field.NewString(table, "status")
	m.DeliveredAt = field.NewTime(table, "delivered_at")
	m.CompletedAt = field.NewTime(table, "completed_at")
	m.Result = field.NewString(table, "result")
	m.Error = field.NewString(table, "error")
	m.CreatedAt = field.NewTime(table, "created_at")
	m.ExpiresAt = field.NewTime(table, "expires_at")
	m.NodeID = field.NewString(table, "node_id")
	m.Direction = field.NewString(table, "direction")
	m.ParentMessageID = field.NewString(table, "parent_message_id")
	m.TurnID = field.NewString(table, "turn_id")
	m.ResponseID = field.NewString(table, "response_id")
	m.Events = field.NewString(table, "events")
	m.FileChanges = field.NewString(table, "file_changes")
	m.TokenUsage = field.NewString(table, "token_usage")

	m.fillFieldMap()

	return m
}

func (m *mailbox) WithContext(ctx context.Context) IMailboxDo { return m.mailboxDo.WithContext(ctx) }

func (m mailbox) TableName() string { return m.mailboxDo.TableName() }

func (m mailbox) Alias() string { return m.mailboxDo.Alias() }

func (m mailbox) Columns(cols ...field.Expr) gen.Columns { return m.mailboxDo.Columns(cols...) }

func (m *mailbox) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *mailbox) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 24)
	m.fieldMap["id"] = m.ID
	m.fieldMap["message_id"] = m.MessageID
	m.fieldMap["user_id"] = m.UserID
	m.fieldMap["owner_user_id"] = m.OwnerUserID
	m.fieldMap["agent_id"] = m.AgentID
	m.fieldMap["session_id"] = m.SessionID
	m.fieldMap["message"] = m.Message
	m.fieldMap["message_type"] = m.MessageType
	m.fieldMap["payload"] = m.Payload
	m.fieldMap["status"] = m.Status
	m.fieldMap["delivered_at"] = m.DeliveredAt
	m.fieldMap["completed_at"] = m.CompletedAt
	m.fieldMap["result"] = m.Result
	m.fieldMap["error"] = m.Error
	m.fieldMap["created_at"] = m.CreatedAt
	m.fieldMap["expires_at"] = m.ExpiresAt
	m.fieldMap["node_id"] = m.NodeID
	m.fieldMap["direction"] = m.Direction
	m.fieldMap["parent_message_id"] = m.ParentMessageID
	m.fieldMap["turn_id"] = m.TurnID
	m.fieldMap["response_id"] = m.ResponseID
	m.fieldMap["events"] = m.Events
	m.fieldMap["file_changes"] = m.FileChanges
	m.fieldMap["token_usage"] = m.TokenUsage
}

func (m mailbox) clone(db *gorm.DB) mailbox {
	m.mailboxDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m mailbox) replaceDB(db *gorm.DB) mailbox {
	m.mailboxDo.ReplaceDB(db)
	return m
}

type mailboxDo struct{ gen.DO }

type IMailboxDo interface {
	gen.SubQuery
	Debug() IMailboxDo
	WithContext(ctx context.Context) IMailboxDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMailboxDo
	WriteDB() IMailboxDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMailboxDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMailboxDo
	Not(conds ...gen.Condition) IMailboxDo
	Or(conds ...gen.Condition) IMailboxDo
	Select(conds ...field.Expr) IMailboxDo
	Where(conds ...gen.Condition) IMailboxDo
	Order(conds ...field.Expr) IMailboxDo
	Distinct(cols ...field.Expr) IMailboxDo
	Omit(cols ...field.Expr) IMailboxDo
	Join(table schema.Tabler, on ...field.Expr) IMailboxDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMailboxDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMailboxDo
	Group(cols ...field.Expr) IMailboxDo
	Having(conds ...gen.Condition) IMailboxDo
	Limit(limit int) IMailboxDo
	Offset(offset int) IMailboxDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMailboxDo
	Unscoped() IMailboxDo
	Create(values ...*model.Mailbox) error
	CreateInBatches(values []*model.Mailbox, batchSize int) error
	Save(values ...*model.Mailbox) error
	First() (*model.Mailbox, error)
	Take() (*model.Mailbox, error)
	Last() (*model.Mailbox, error)
	Find() ([]*model.Mailbox, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Mailbox, err error)
	FindInBatches(result *[]*model.Mailbox, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Mailbox) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMailboxDo
	Assign(attrs ...field.AssignExpr) IMailboxDo
	Joins(fields ...field.RelationField) IMailboxDo
	Preload(fields ...field.RelationField) IMailboxDo
	FirstOrInit() (*model.Mailbox, error)
	FirstOrCreate() (*model.Mailbox, error)
	FindByPage(offset int, limit int) (result []*model.Mailbox, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMailboxDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m mailboxDo) Debug() IMailboxDo {
	return m.withDO(m.DO.Debug())
}

func (m mailboxDo) WithContext(ctx context.Context) IMailboxDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m mailboxDo) ReadDB() IMailboxDo {
	return m.Clauses(dbresolver.Read)
}

func (m mailboxDo) WriteDB() IMailboxDo {
	return m.Clauses(dbresolver.Write)
}

func (m mailboxDo) Session(config *gorm.Session) IMailboxDo {
	return m.withDO(m.DO.Session(config))
}

func (m mailboxDo) Clauses(conds ...clause.Expression) IMailboxDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m mailboxDo) Returning(value interface{}, columns ...string) IMailboxDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m mailboxDo) Not(conds ...gen.Condition) IMailboxDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m mailboxDo) Or(conds ...gen.Condition) IMailboxDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m mailboxDo) Select(conds ...field.Expr) IMailboxDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m mailboxDo) Where(conds ...gen.Condition) IMailboxDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m mailboxDo) Order(conds ...field.Expr) IMailboxDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m mailboxDo) Distinct(cols ...field.Expr) IMailboxDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m mailboxDo) Omit(cols ...field.Expr) IMailboxDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m mailboxDo) Join(table schema.Tabler, on ...field.Expr) IMailboxDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m mailboxDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMailboxDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m mailboxDo) RightJoin(table schema.Tabler, on ...field.Expr) IMailboxDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m mailboxDo) Group(cols ...field.Expr) IMailboxDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m mailboxDo) Having(conds ...gen.Condition) IMailboxDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m mailboxDo) Limit(limit int) IMailboxDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m mailboxDo) Offset(offset int) IMailboxDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m mailboxDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMailboxDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m mailboxDo) Unscoped() IMailboxDo {
	return m.withDO(m.DO.Unscoped())
}

func (m mailboxDo) Create(values ...*model.Mailbox) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m mailboxDo) CreateInBatches(values []*model.Mailbox, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m mailboxDo) Save(values ...*model.Mailbox) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m mailboxDo) First() (*model.Mailbox, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Mailbox), nil
	}
}

func (m mailboxDo) Take() (*model.Mailbox, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Mailbox), nil
	}
}

func (m mailboxDo) Last() (*model.Mailbox, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Mailbox), nil
	}
}

func (m mailboxDo) Find() ([]*model.Mailbox, error) {
	result, err := m.DO.Find()
	return result.([]*model.Mailbox), err
}

func (m mailboxDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Mailbox, err error) {
	buf := make([]*model.Mailbox, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m mailboxDo) FindInBatches(result *[]*model.Mailbox, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m mailboxDo) Attrs(attrs ...field.AssignExpr) IMailboxDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m mailboxDo) Assign(attrs ...field.AssignExpr) IMailboxDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m mailboxDo) Joins(fields ...field.RelationField) IMailboxDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m mailboxDo) Preload(fields ...field.RelationField) IMailboxDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m mailboxDo) FirstOrInit() (*model.Mailbox, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Mailbox), nil
	}
}

func (m mailboxDo) FirstOrCreate() (*model.Mailbox, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Mailbox), nil
	}
}

func (m mailboxDo) FindByPage(offset int, limit int) (result []*model.Mailbox, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m mailboxDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m mailboxDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m mailboxDo) Delete(models ...*model.Mailbox) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *mailboxDo) withDO(do gen.Dao) *mailboxDo {
	m.DO = *do.(*gen.DO)
	return m
}
