// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/pax-beehive/pax-manager/internal/manager/storage/dal/model"
)

func newMessagePart(db *gorm.DB, opts ...gen.DOOption) messagePart {
	_messagePart := messagePart{}

	_messagePart.messagePartDo.UseDB(db, opts...)
	_messagePart.messagePartDo.UseModel(&model.MessagePart{})

	tableName := _messagePart.messagePartDo.TableName()
	_messagePart.ALL = field.NewAsterisk(tableName)
	_messagePart.ID = field.NewInt64(tableName, "id")
	_messagePart.MessageID = field.NewString(tableName, "message_id")
	_messagePart.PartIndex = field.NewInt32(tableName, "part_index")
	_messagePart.PartType = field.NewString(tableName, "part_type")
	_messagePart.Text = field.NewString(tableName, "text")
	_messagePart.PayloadJSON = field.NewString(tableName, "payload_json")
	_messagePart.ArtifactURI = field.NewString(tableName, "artifact_uri")
	_messagePart.CreatedAt = field.NewTime(tableName, "created_at")
	_messagePart.UpdatedAt = field.NewTime(tableName, "updated_at")

	_messagePart.fillFieldMap()

	return _messagePart
}

type messagePart struct {
	messagePartDo messagePartDo

	ALL         field.Asterisk
	ID          field.Int64
	MessageID   field.String
	PartIndex   field.Int32
	PartType    field.String
	Text        field.String
	PayloadJSON field.String
	ArtifactURI field.String
	CreatedAt   field.Time
	UpdatedAt   field.Time

	fieldMap map[string]field.Expr
}

func (m messagePart) Table(newTableName string) *messagePart {
	m.messagePartDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m messagePart) As(alias string) *messagePart {
	m.messagePartDo.DO = *(m.messagePartDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *messagePart) updateTableName(table string) *messagePart {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewInt64(table, "id")
	m.MessageID = field.NewString(table, "message_id")
	m.PartIndex = field.NewInt32(table, "part_index")
	m.PartType = field.NewString(table, "part_type")
	m.Text = field.NewString(table, "text")
	m.PayloadJSON = field.NewString(table, "payload_json")
	m.ArtifactURI = field.NewString(table, "artifact_uri")
	m.CreatedAt = field.NewTime(table, "created_at")
	m.UpdatedAt = field.NewTime(table, "updated_at")

	m.fillFieldMap()

	return m
}

func (m *messagePart) WithContext(ctx context.Context) IMessagePartDo {
	return m.messagePartDo.WithContext(ctx)
}

func (m messagePart) TableName() string { return m.messagePartDo.TableName() }

func (m messagePart) Alias() string { return m.messagePartDo.Alias() }

func (m messagePart) Columns(cols ...field.Expr) gen.Columns { return m.messagePartDo.Columns(cols...) }

func (m *messagePart) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *messagePart) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 9)
	m.fieldMap["id"] = m.ID
	m.fieldMap["message_id"] = m.MessageID
	m.fieldMap["part_index"] = m.PartIndex
	m.fieldMap["part_type"] = m.PartType
	m.fieldMap["text"] = m.Text
	m.fieldMap["payload_json"] = m.PayloadJSON
	m.fieldMap["artifact_uri"] = m.ArtifactURI
	m.fieldMap["created_at"] = m.CreatedAt
	m.fieldMap["updated_at"] = m.UpdatedAt
}

func (m messagePart) clone(db *gorm.DB) messagePart {
	m.messagePartDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m messagePart) replaceDB(db *gorm.DB) messagePart {
	m.messagePartDo.ReplaceDB(db)
	return m
}

type messagePartDo struct{ gen.DO }

type IMessagePartDo interface {
	gen.SubQuery
	Debug() IMessagePartDo
	WithContext(ctx context.Context) IMessagePartDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMessagePartDo
	WriteDB() IMessagePartDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMessagePartDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMessagePartDo
	Not(conds ...gen.Condition) IMessagePartDo
	Or(conds ...gen.Condition) IMessagePartDo
	Select(conds ...field.Expr) IMessagePartDo
	Where(conds ...gen.Condition) IMessagePartDo
	Order(conds ...field.Expr) IMessagePartDo
	Distinct(cols ...field.Expr) IMessagePartDo
	Omit(cols ...field.Expr) IMessagePartDo
	Join(table schema.Tabler, on ...field.Expr) IMessagePartDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMessagePartDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMessagePartDo
	Group(cols ...field.Expr) IMessagePartDo
	Having(conds ...gen.Condition) IMessagePartDo
	Limit(limit int) IMessagePartDo
	Offset(offset int) IMessagePartDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMessagePartDo
	Unscoped() IMessagePartDo
	Create(values ...*model.MessagePart) error
	CreateInBatches(values []*model.MessagePart, batchSize int) error
	Save(values ...*model.MessagePart) error
	First() (*model.MessagePart, error)
	Take() (*model.MessagePart, error)
	Last() (*model.MessagePart, error)
	Find() ([]*model.MessagePart, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MessagePart, err error)
	FindInBatches(result *[]*model.MessagePart, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.MessagePart) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMessagePartDo
	Assign(attrs ...field.AssignExpr) IMessagePartDo
	Joins(fields ...field.RelationField) IMessagePartDo
	Preload(fields ...field.RelationField) IMessagePartDo
	FirstOrInit() (*model.MessagePart, error)
	FirstOrCreate() (*model.MessagePart, error)
	FindByPage(offset int, limit int) (result []*model.MessagePart, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMessagePartDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m messagePartDo) Debug() IMessagePartDo {
	return m.withDO(m.DO.Debug())
}

func (m messagePartDo) WithContext(ctx context.Context) IMessagePartDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m messagePartDo) ReadDB() IMessagePartDo {
	return m.Clauses(dbresolver.Read)
}

func (m messagePartDo) WriteDB() IMessagePartDo {
	return m.Clauses(dbresolver.Write)
}

func (m messagePartDo) Session(config *gorm.Session) IMessagePartDo {
	return m.withDO(m.DO.Session(config))
}

func (m messagePartDo) Clauses(conds ...clause.Expression) IMessagePartDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m messagePartDo) Returning(value interface{}, columns ...string) IMessagePartDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m messagePartDo) Not(conds ...gen.Condition) IMessagePartDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m messagePartDo) Or(conds ...gen.Condition) IMessagePartDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m messagePartDo) Select(conds ...field.Expr) IMessagePartDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m messagePartDo) Where(conds ...gen.Condition) IMessagePartDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m messagePartDo) Order(conds ...field.Expr) IMessagePartDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m messagePartDo) Distinct(cols ...field.Expr) IMessagePartDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m messagePartDo) Omit(cols ...field.Expr) IMessagePartDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m messagePartDo) Join(table schema.Tabler, on ...field.Expr) IMessagePartDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m messagePartDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMessagePartDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m messagePartDo) RightJoin(table schema.Tabler, on ...field.Expr) IMessagePartDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m messagePartDo) Group(cols ...field.Expr) IMessagePartDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m messagePartDo) Having(conds ...gen.Condition) IMessagePartDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m messagePartDo) Limit(limit int) IMessagePartDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m messagePartDo) Offset(offset int) IMessagePartDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m messagePartDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMessagePartDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m messagePartDo) Unscoped() IMessagePartDo {
	return m.withDO(m.DO.Unscoped())
}

func (m messagePartDo) Create(values ...*model.MessagePart) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m messagePartDo) CreateInBatches(values []*model.MessagePart, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m messagePartDo) Save(values ...*model.MessagePart) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m messagePartDo) First() (*model.MessagePart, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.MessagePart), nil
	}
}

func (m messagePartDo) Take() (*model.MessagePart, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.MessagePart), nil
	}
}

func (m messagePartDo) Last() (*model.MessagePart, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.MessagePart), nil
	}
}

func (m messagePartDo) Find() ([]*model.MessagePart, error) {
	result, err := m.DO.Find()
	return result.([]*model.MessagePart), err
}

func (m messagePartDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MessagePart, err error) {
	buf := make([]*model.MessagePart, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m messagePartDo) FindInBatches(result *[]*model.MessagePart, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m messagePartDo) Attrs(attrs ...field.AssignExpr) IMessagePartDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m messagePartDo) Assign(attrs ...field.AssignExpr) IMessagePartDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m messagePartDo) Joins(fields ...field.RelationField) IMessagePartDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m messagePartDo) Preload(fields ...field.RelationField) IMessagePartDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m messagePartDo) FirstOrInit() (*model.MessagePart, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.MessagePart), nil
	}
}

func (m messagePartDo) FirstOrCreate() (*model.MessagePart, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.MessagePart), nil
	}
}

func (m messagePartDo) FindByPage(offset int, limit int) (result []*model.MessagePart, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m messagePartDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m messagePartDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m messagePartDo) Delete(models ...*model.MessagePart) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *messagePartDo) withDO(do gen.Dao) *messagePartDo {
	m.DO = *do.(*gen.DO)
	return m
}
