// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/pax-beehive/pax-manager/internal/manager/storage/dal/model"
)

func newNodeRegistrationSession(db *gorm.DB, opts ...gen.DOOption) nodeRegistrationSession {
	_nodeRegistrationSession := nodeRegistrationSession{}

	_nodeRegistrationSession.nodeRegistrationSessionDo.UseDB(db, opts...)
	_nodeRegistrationSession.nodeRegistrationSessionDo.UseModel(&model.NodeRegistrationSession{})

	tableName := _nodeRegistrationSession.nodeRegistrationSessionDo.TableName()
	_nodeRegistrationSession.ALL = field.NewAsterisk(tableName)
	_nodeRegistrationSession.RegistrationID = field.NewString(tableName, "registration_id")
	_nodeRegistrationSession.PairCode = field.NewString(tableName, "pair_code")
	_nodeRegistrationSession.PollTokenHash = field.NewString(tableName, "poll_token_hash")
	_nodeRegistrationSession.Status = field.NewString(tableName, "status")
	_nodeRegistrationSession.OwnerUserID = field.NewString(tableName, "owner_user_id")
	_nodeRegistrationSession.NodeID = field.NewString(tableName, "node_id")
	_nodeRegistrationSession.RequestedName = field.NewString(tableName, "requested_name")
	_nodeRegistrationSession.RequestedHostname = field.NewString(tableName, "requested_hostname")
	_nodeRegistrationSession.RequestedMachineType = field.NewString(tableName, "requested_machine_type")
	_nodeRegistrationSession.RequestedOs = field.NewString(tableName, "requested_os")
	_nodeRegistrationSession.RequestedArch = field.NewString(tableName, "requested_arch")
	_nodeRegistrationSession.RequestedPaxdVersion = field.NewString(tableName, "requested_paxd_version")
	_nodeRegistrationSession.RequestedAPIEndpoint = field.NewString(tableName, "requested_api_endpoint")
	_nodeRegistrationSession.RequestedMetadata = field.NewString(tableName, "requested_metadata")
	_nodeRegistrationSession.ExpiresAt = field.NewTime(tableName, "expires_at")
	_nodeRegistrationSession.CreatedAt = field.NewTime(tableName, "created_at")
	_nodeRegistrationSession.ApprovedAt = field.NewTime(tableName, "approved_at")
	_nodeRegistrationSession.ConsumedAt = field.NewTime(tableName, "consumed_at")

	_nodeRegistrationSession.fillFieldMap()

	return _nodeRegistrationSession
}

type nodeRegistrationSession struct {
	nodeRegistrationSessionDo nodeRegistrationSessionDo

	ALL                  field.Asterisk
	RegistrationID       field.String
	PairCode             field.String
	PollTokenHash        field.String
	Status               field.String
	OwnerUserID          field.String
	NodeID               field.String
	RequestedName        field.String
	RequestedHostname    field.String
	RequestedMachineType field.String
	RequestedOs          field.String
	RequestedArch        field.String
	RequestedPaxdVersion field.String
	RequestedAPIEndpoint field.String
	RequestedMetadata    field.String
	ExpiresAt            field.Time
	CreatedAt            field.Time
	ApprovedAt           field.Time
	ConsumedAt           field.Time

	fieldMap map[string]field.Expr
}

func (n nodeRegistrationSession) Table(newTableName string) *nodeRegistrationSession {
	n.nodeRegistrationSessionDo.UseTable(newTableName)
	return n.updateTableName(newTableName)
}

func (n nodeRegistrationSession) As(alias string) *nodeRegistrationSession {
	n.nodeRegistrationSessionDo.DO = *(n.nodeRegistrationSessionDo.As(alias).(*gen.DO))
	return n.updateTableName(alias)
}

func (n *nodeRegistrationSession) updateTableName(table string) *nodeRegistrationSession {
	n.ALL = field.NewAsterisk(table)
	n.RegistrationID = field.NewString(table, "registration_id")
	n.PairCode = field.NewString(table, "pair_code")
	n.PollTokenHash = field.NewString(table, "poll_token_hash")
	n.Status = field.NewString(table, "status")
	n.OwnerUserID = field.NewString(table, "owner_user_id")
	n.NodeID = field.NewString(table, "node_id")
	n.RequestedName = field.NewString(table, "requested_name")
	n.RequestedHostname = field.NewString(table, "requested_hostname")
	n.RequestedMachineType = field.NewString(table, "requested_machine_type")
	n.RequestedOs = field.NewString(table, "requested_os")
	n.RequestedArch = field.NewString(table, "requested_arch")
	n.RequestedPaxdVersion = field.NewString(table, "requested_paxd_version")
	n.RequestedAPIEndpoint = field.NewString(table, "requested_api_endpoint")
	n.RequestedMetadata = field.NewString(table, "requested_metadata")
	n.ExpiresAt = field.NewTime(table, "expires_at")
	n.CreatedAt = field.NewTime(table, "created_at")
	n.ApprovedAt = field.NewTime(table, "approved_at")
	n.ConsumedAt = field.NewTime(table, "consumed_at")

	n.fillFieldMap()

	return n
}

func (n *nodeRegistrationSession) WithContext(ctx context.Context) INodeRegistrationSessionDo {
	return n.nodeRegistrationSessionDo.WithContext(ctx)
}

func (n nodeRegistrationSession) TableName() string { return n.nodeRegistrationSessionDo.TableName() }

func (n nodeRegistrationSession) Alias() string { return n.nodeRegistrationSessionDo.Alias() }

func (n nodeRegistrationSession) Columns(cols ...field.Expr) gen.Columns {
	return n.nodeRegistrationSessionDo.Columns(cols...)
}

func (n *nodeRegistrationSession) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := n.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (n *nodeRegistrationSession) fillFieldMap() {
	n.fieldMap = make(map[string]field.Expr, 18)
	n.fieldMap["registration_id"] = n.RegistrationID
	n.fieldMap["pair_code"] = n.PairCode
	n.fieldMap["poll_token_hash"] = n.PollTokenHash
	n.fieldMap["status"] = n.Status
	n.fieldMap["owner_user_id"] = n.OwnerUserID
	n.fieldMap["node_id"] = n.NodeID
	n.fieldMap["requested_name"] = n.RequestedName
	n.fieldMap["requested_hostname"] = n.RequestedHostname
	n.fieldMap["requested_machine_type"] = n.RequestedMachineType
	n.fieldMap["requested_os"] = n.RequestedOs
	n.fieldMap["requested_arch"] = n.RequestedArch
	n.fieldMap["requested_paxd_version"] = n.RequestedPaxdVersion
	n.fieldMap["requested_api_endpoint"] = n.RequestedAPIEndpoint
	n.fieldMap["requested_metadata"] = n.RequestedMetadata
	n.fieldMap["expires_at"] = n.ExpiresAt
	n.fieldMap["created_at"] = n.CreatedAt
	n.fieldMap["approved_at"] = n.ApprovedAt
	n.fieldMap["consumed_at"] = n.ConsumedAt
}

func (n nodeRegistrationSession) clone(db *gorm.DB) nodeRegistrationSession {
	n.nodeRegistrationSessionDo.ReplaceConnPool(db.Statement.ConnPool)
	return n
}

func (n nodeRegistrationSession) replaceDB(db *gorm.DB) nodeRegistrationSession {
	n.nodeRegistrationSessionDo.ReplaceDB(db)
	return n
}

type nodeRegistrationSessionDo struct{ gen.DO }

type INodeRegistrationSessionDo interface {
	gen.SubQuery
	Debug() INodeRegistrationSessionDo
	WithContext(ctx context.Context) INodeRegistrationSessionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() INodeRegistrationSessionDo
	WriteDB() INodeRegistrationSessionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) INodeRegistrationSessionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) INodeRegistrationSessionDo
	Not(conds ...gen.Condition) INodeRegistrationSessionDo
	Or(conds ...gen.Condition) INodeRegistrationSessionDo
	Select(conds ...field.Expr) INodeRegistrationSessionDo
	Where(conds ...gen.Condition) INodeRegistrationSessionDo
	Order(conds ...field.Expr) INodeRegistrationSessionDo
	Distinct(cols ...field.Expr) INodeRegistrationSessionDo
	Omit(cols ...field.Expr) INodeRegistrationSessionDo
	Join(table schema.Tabler, on ...field.Expr) INodeRegistrationSessionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) INodeRegistrationSessionDo
	RightJoin(table schema.Tabler, on ...field.Expr) INodeRegistrationSessionDo
	Group(cols ...field.Expr) INodeRegistrationSessionDo
	Having(conds ...gen.Condition) INodeRegistrationSessionDo
	Limit(limit int) INodeRegistrationSessionDo
	Offset(offset int) INodeRegistrationSessionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) INodeRegistrationSessionDo
	Unscoped() INodeRegistrationSessionDo
	Create(values ...*model.NodeRegistrationSession) error
	CreateInBatches(values []*model.NodeRegistrationSession, batchSize int) error
	Save(values ...*model.NodeRegistrationSession) error
	First() (*model.NodeRegistrationSession, error)
	Take() (*model.NodeRegistrationSession, error)
	Last() (*model.NodeRegistrationSession, error)
	Find() ([]*model.NodeRegistrationSession, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.NodeRegistrationSession, err error)
	FindInBatches(result *[]*model.NodeRegistrationSession, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.NodeRegistrationSession) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) INodeRegistrationSessionDo
	Assign(attrs ...field.AssignExpr) INodeRegistrationSessionDo
	Joins(fields ...field.RelationField) INodeRegistrationSessionDo
	Preload(fields ...field.RelationField) INodeRegistrationSessionDo
	FirstOrInit() (*model.NodeRegistrationSession, error)
	FirstOrCreate() (*model.NodeRegistrationSession, error)
	FindByPage(offset int, limit int) (result []*model.NodeRegistrationSession, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) INodeRegistrationSessionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (n nodeRegistrationSessionDo) Debug() INodeRegistrationSessionDo {
	return n.withDO(n.DO.Debug())
}

func (n nodeRegistrationSessionDo) WithContext(ctx context.Context) INodeRegistrationSessionDo {
	return n.withDO(n.DO.WithContext(ctx))
}

func (n nodeRegistrationSessionDo) ReadDB() INodeRegistrationSessionDo {
	return n.Clauses(dbresolver.Read)
}

func (n nodeRegistrationSessionDo) WriteDB() INodeRegistrationSessionDo {
	return n.Clauses(dbresolver.Write)
}

func (n nodeRegistrationSessionDo) Session(config *gorm.Session) INodeRegistrationSessionDo {
	return n.withDO(n.DO.Session(config))
}

func (n nodeRegistrationSessionDo) Clauses(conds ...clause.Expression) INodeRegistrationSessionDo {
	return n.withDO(n.DO.Clauses(conds...))
}

func (n nodeRegistrationSessionDo) Returning(value interface{}, columns ...string) INodeRegistrationSessionDo {
	return n.withDO(n.DO.Returning(value, columns...))
}

func (n nodeRegistrationSessionDo) Not(conds ...gen.Condition) INodeRegistrationSessionDo {
	return n.withDO(n.DO.Not(conds...))
}

func (n nodeRegistrationSessionDo) Or(conds ...gen.Condition) INodeRegistrationSessionDo {
	return n.withDO(n.DO.Or(conds...))
}

func (n nodeRegistrationSessionDo) Select(conds ...field.Expr) INodeRegistrationSessionDo {
	return n.withDO(n.DO.Select(conds...))
}

func (n nodeRegistrationSessionDo) Where(conds ...gen.Condition) INodeRegistrationSessionDo {
	return n.withDO(n.DO.Where(conds...))
}

func (n nodeRegistrationSessionDo) Order(conds ...field.Expr) INodeRegistrationSessionDo {
	return n.withDO(n.DO.Order(conds...))
}

func (n nodeRegistrationSessionDo) Distinct(cols ...field.Expr) INodeRegistrationSessionDo {
	return n.withDO(n.DO.Distinct(cols...))
}

func (n nodeRegistrationSessionDo) Omit(cols ...field.Expr) INodeRegistrationSessionDo {
	return n.withDO(n.DO.Omit(cols...))
}

func (n nodeRegistrationSessionDo) Join(table schema.Tabler, on ...field.Expr) INodeRegistrationSessionDo {
	return n.withDO(n.DO.Join(table, on...))
}

func (n nodeRegistrationSessionDo) LeftJoin(table schema.Tabler, on ...field.Expr) INodeRegistrationSessionDo {
	return n.withDO(n.DO.LeftJoin(table, on...))
}

func (n nodeRegistrationSessionDo) RightJoin(table schema.Tabler, on ...field.Expr) INodeRegistrationSessionDo {
	return n.withDO(n.DO.RightJoin(table, on...))
}

func (n nodeRegistrationSessionDo) Group(cols ...field.Expr) INodeRegistrationSessionDo {
	return n.withDO(n.DO.Group(cols...))
}

func (n nodeRegistrationSessionDo) Having(conds ...gen.Condition) INodeRegistrationSessionDo {
	return n.withDO(n.DO.Having(conds...))
}

func (n nodeRegistrationSessionDo) Limit(limit int) INodeRegistrationSessionDo {
	return n.withDO(n.DO.Limit(limit))
}

func (n nodeRegistrationSessionDo) Offset(offset int) INodeRegistrationSessionDo {
	return n.withDO(n.DO.Offset(offset))
}

func (n nodeRegistrationSessionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) INodeRegistrationSessionDo {
	return n.withDO(n.DO.Scopes(funcs...))
}

func (n nodeRegistrationSessionDo) Unscoped() INodeRegistrationSessionDo {
	return n.withDO(n.DO.Unscoped())
}

func (n nodeRegistrationSessionDo) Create(values ...*model.NodeRegistrationSession) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Create(values)
}

func (n nodeRegistrationSessionDo) CreateInBatches(values []*model.NodeRegistrationSession, batchSize int) error {
	return n.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (n nodeRegistrationSessionDo) Save(values ...*model.NodeRegistrationSession) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Save(values)
}

func (n nodeRegistrationSessionDo) First() (*model.NodeRegistrationSession, error) {
	if result, err := n.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.NodeRegistrationSession), nil
	}
}

func (n nodeRegistrationSessionDo) Take() (*model.NodeRegistrationSession, error) {
	if result, err := n.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.NodeRegistrationSession), nil
	}
}

func (n nodeRegistrationSessionDo) Last() (*model.NodeRegistrationSession, error) {
	if result, err := n.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.NodeRegistrationSession), nil
	}
}

func (n nodeRegistrationSessionDo) Find() ([]*model.NodeRegistrationSession, error) {
	result, err := n.DO.Find()
	return result.([]*model.NodeRegistrationSession), err
}

func (n nodeRegistrationSessionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.NodeRegistrationSession, err error) {
	buf := make([]*model.NodeRegistrationSession, 0, batchSize)
	err = n.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (n nodeRegistrationSessionDo) FindInBatches(result *[]*model.NodeRegistrationSession, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return n.DO.FindInBatches(result, batchSize, fc)
}

func (n nodeRegistrationSessionDo) Attrs(attrs ...field.AssignExpr) INodeRegistrationSessionDo {
	return n.withDO(n.DO.Attrs(attrs...))
}

func (n nodeRegistrationSessionDo) Assign(attrs ...field.AssignExpr) INodeRegistrationSessionDo {
	return n.withDO(n.DO.Assign(attrs...))
}

func (n nodeRegistrationSessionDo) Joins(fields ...field.RelationField) INodeRegistrationSessionDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Joins(_f))
	}
	return &n
}

func (n nodeRegistrationSessionDo) Preload(fields ...field.RelationField) INodeRegistrationSessionDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Preload(_f))
	}
	return &n
}

func (n nodeRegistrationSessionDo) FirstOrInit() (*model.NodeRegistrationSession, error) {
	if result, err := n.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.NodeRegistrationSession), nil
	}
}

func (n nodeRegistrationSessionDo) FirstOrCreate() (*model.NodeRegistrationSession, error) {
	if result, err := n.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.NodeRegistrationSession), nil
	}
}

func (n nodeRegistrationSessionDo) FindByPage(offset int, limit int) (result []*model.NodeRegistrationSession, count int64, err error) {
	result, err = n.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = n.Offset(-1).Limit(-1).Count()
	return
}

func (n nodeRegistrationSessionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = n.Count()
	if err != nil {
		return
	}

	err = n.Offset(offset).Limit(limit).Scan(result)
	return
}

func (n nodeRegistrationSessionDo) Scan(result interface{}) (err error) {
	return n.DO.Scan(result)
}

func (n nodeRegistrationSessionDo) Delete(models ...*model.NodeRegistrationSession) (result gen.ResultInfo, err error) {
	return n.DO.Delete(models)
}

func (n *nodeRegistrationSessionDo) withDO(do gen.Dao) *nodeRegistrationSessionDo {
	n.DO = *do.(*gen.DO)
	return n
}
