// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/pax-beehive/pax-manager/internal/manager/storage/dal/model"
)

func newNodeMessageOffset(db *gorm.DB, opts ...gen.DOOption) nodeMessageOffset {
	_nodeMessageOffset := nodeMessageOffset{}

	_nodeMessageOffset.nodeMessageOffsetDo.UseDB(db, opts...)
	_nodeMessageOffset.nodeMessageOffsetDo.UseModel(&model.NodeMessageOffset{})

	tableName := _nodeMessageOffset.nodeMessageOffsetDo.TableName()
	_nodeMessageOffset.ALL = field.NewAsterisk(tableName)
	_nodeMessageOffset.NodeID = field.NewString(tableName, "node_id")
	_nodeMessageOffset.LastOffset = field.NewInt64(tableName, "last_offset")
	_nodeMessageOffset.UpdatedAt = field.NewTime(tableName, "updated_at")

	_nodeMessageOffset.fillFieldMap()

	return _nodeMessageOffset
}

type nodeMessageOffset struct {
	nodeMessageOffsetDo nodeMessageOffsetDo

	ALL        field.Asterisk
	NodeID     field.String
	LastOffset field.Int64
	UpdatedAt  field.Time

	fieldMap map[string]field.Expr
}

func (n nodeMessageOffset) Table(newTableName string) *nodeMessageOffset {
	n.nodeMessageOffsetDo.UseTable(newTableName)
	return n.updateTableName(newTableName)
}

func (n nodeMessageOffset) As(alias string) *nodeMessageOffset {
	n.nodeMessageOffsetDo.DO = *(n.nodeMessageOffsetDo.As(alias).(*gen.DO))
	return n.updateTableName(alias)
}

func (n *nodeMessageOffset) updateTableName(table string) *nodeMessageOffset {
	n.ALL = field.NewAsterisk(table)
	n.NodeID = field.NewString(table, "node_id")
	n.LastOffset = field.NewInt64(table, "last_offset")
	n.UpdatedAt = field.NewTime(table, "updated_at")

	n.fillFieldMap()

	return n
}

func (n *nodeMessageOffset) WithContext(ctx context.Context) INodeMessageOffsetDo {
	return n.nodeMessageOffsetDo.WithContext(ctx)
}

func (n nodeMessageOffset) TableName() string { return n.nodeMessageOffsetDo.TableName() }

func (n nodeMessageOffset) Alias() string { return n.nodeMessageOffsetDo.Alias() }

func (n nodeMessageOffset) Columns(cols ...field.Expr) gen.Columns {
	return n.nodeMessageOffsetDo.Columns(cols...)
}

func (n *nodeMessageOffset) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := n.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (n *nodeMessageOffset) fillFieldMap() {
	n.fieldMap = make(map[string]field.Expr, 3)
	n.fieldMap["node_id"] = n.NodeID
	n.fieldMap["last_offset"] = n.LastOffset
	n.fieldMap["updated_at"] = n.UpdatedAt
}

func (n nodeMessageOffset) clone(db *gorm.DB) nodeMessageOffset {
	n.nodeMessageOffsetDo.ReplaceConnPool(db.Statement.ConnPool)
	return n
}

func (n nodeMessageOffset) replaceDB(db *gorm.DB) nodeMessageOffset {
	n.nodeMessageOffsetDo.ReplaceDB(db)
	return n
}

type nodeMessageOffsetDo struct{ gen.DO }

type INodeMessageOffsetDo interface {
	gen.SubQuery
	Debug() INodeMessageOffsetDo
	WithContext(ctx context.Context) INodeMessageOffsetDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() INodeMessageOffsetDo
	WriteDB() INodeMessageOffsetDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) INodeMessageOffsetDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) INodeMessageOffsetDo
	Not(conds ...gen.Condition) INodeMessageOffsetDo
	Or(conds ...gen.Condition) INodeMessageOffsetDo
	Select(conds ...field.Expr) INodeMessageOffsetDo
	Where(conds ...gen.Condition) INodeMessageOffsetDo
	Order(conds ...field.Expr) INodeMessageOffsetDo
	Distinct(cols ...field.Expr) INodeMessageOffsetDo
	Omit(cols ...field.Expr) INodeMessageOffsetDo
	Join(table schema.Tabler, on ...field.Expr) INodeMessageOffsetDo
	LeftJoin(table schema.Tabler, on ...field.Expr) INodeMessageOffsetDo
	RightJoin(table schema.Tabler, on ...field.Expr) INodeMessageOffsetDo
	Group(cols ...field.Expr) INodeMessageOffsetDo
	Having(conds ...gen.Condition) INodeMessageOffsetDo
	Limit(limit int) INodeMessageOffsetDo
	Offset(offset int) INodeMessageOffsetDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) INodeMessageOffsetDo
	Unscoped() INodeMessageOffsetDo
	Create(values ...*model.NodeMessageOffset) error
	CreateInBatches(values []*model.NodeMessageOffset, batchSize int) error
	Save(values ...*model.NodeMessageOffset) error
	First() (*model.NodeMessageOffset, error)
	Take() (*model.NodeMessageOffset, error)
	Last() (*model.NodeMessageOffset, error)
	Find() ([]*model.NodeMessageOffset, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.NodeMessageOffset, err error)
	FindInBatches(result *[]*model.NodeMessageOffset, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.NodeMessageOffset) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) INodeMessageOffsetDo
	Assign(attrs ...field.AssignExpr) INodeMessageOffsetDo
	Joins(fields ...field.RelationField) INodeMessageOffsetDo
	Preload(fields ...field.RelationField) INodeMessageOffsetDo
	FirstOrInit() (*model.NodeMessageOffset, error)
	FirstOrCreate() (*model.NodeMessageOffset, error)
	FindByPage(offset int, limit int) (result []*model.NodeMessageOffset, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) INodeMessageOffsetDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (n nodeMessageOffsetDo) Debug() INodeMessageOffsetDo {
	return n.withDO(n.DO.Debug())
}

func (n nodeMessageOffsetDo) WithContext(ctx context.Context) INodeMessageOffsetDo {
	return n.withDO(n.DO.WithContext(ctx))
}

func (n nodeMessageOffsetDo) ReadDB() INodeMessageOffsetDo {
	return n.Clauses(dbresolver.Read)
}

func (n nodeMessageOffsetDo) WriteDB() INodeMessageOffsetDo {
	return n.Clauses(dbresolver.Write)
}

func (n nodeMessageOffsetDo) Session(config *gorm.Session) INodeMessageOffsetDo {
	return n.withDO(n.DO.Session(config))
}

func (n nodeMessageOffsetDo) Clauses(conds ...clause.Expression) INodeMessageOffsetDo {
	return n.withDO(n.DO.Clauses(conds...))
}

func (n nodeMessageOffsetDo) Returning(value interface{}, columns ...string) INodeMessageOffsetDo {
	return n.withDO(n.DO.Returning(value, columns...))
}

func (n nodeMessageOffsetDo) Not(conds ...gen.Condition) INodeMessageOffsetDo {
	return n.withDO(n.DO.Not(conds...))
}

func (n nodeMessageOffsetDo) Or(conds ...gen.Condition) INodeMessageOffsetDo {
	return n.withDO(n.DO.Or(conds...))
}

func (n nodeMessageOffsetDo) Select(conds ...field.Expr) INodeMessageOffsetDo {
	return n.withDO(n.DO.Select(conds...))
}

func (n nodeMessageOffsetDo) Where(conds ...gen.Condition) INodeMessageOffsetDo {
	return n.withDO(n.DO.Where(conds...))
}

func (n nodeMessageOffsetDo) Order(conds ...field.Expr) INodeMessageOffsetDo {
	return n.withDO(n.DO.Order(conds...))
}

func (n nodeMessageOffsetDo) Distinct(cols ...field.Expr) INodeMessageOffsetDo {
	return n.withDO(n.DO.Distinct(cols...))
}

func (n nodeMessageOffsetDo) Omit(cols ...field.Expr) INodeMessageOffsetDo {
	return n.withDO(n.DO.Omit(cols...))
}

func (n nodeMessageOffsetDo) Join(table schema.Tabler, on ...field.Expr) INodeMessageOffsetDo {
	return n.withDO(n.DO.Join(table, on...))
}

func (n nodeMessageOffsetDo) LeftJoin(table schema.Tabler, on ...field.Expr) INodeMessageOffsetDo {
	return n.withDO(n.DO.LeftJoin(table, on...))
}

func (n nodeMessageOffsetDo) RightJoin(table schema.Tabler, on ...field.Expr) INodeMessageOffsetDo {
	return n.withDO(n.DO.RightJoin(table, on...))
}

func (n nodeMessageOffsetDo) Group(cols ...field.Expr) INodeMessageOffsetDo {
	return n.withDO(n.DO.Group(cols...))
}

func (n nodeMessageOffsetDo) Having(conds ...gen.Condition) INodeMessageOffsetDo {
	return n.withDO(n.DO.Having(conds...))
}

func (n nodeMessageOffsetDo) Limit(limit int) INodeMessageOffsetDo {
	return n.withDO(n.DO.Limit(limit))
}

func (n nodeMessageOffsetDo) Offset(offset int) INodeMessageOffsetDo {
	return n.withDO(n.DO.Offset(offset))
}

func (n nodeMessageOffsetDo) Scopes(funcs ...func(gen.Dao) gen.Dao) INodeMessageOffsetDo {
	return n.withDO(n.DO.Scopes(funcs...))
}

func (n nodeMessageOffsetDo) Unscoped() INodeMessageOffsetDo {
	return n.withDO(n.DO.Unscoped())
}

func (n nodeMessageOffsetDo) Create(values ...*model.NodeMessageOffset) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Create(values)
}

func (n nodeMessageOffsetDo) CreateInBatches(values []*model.NodeMessageOffset, batchSize int) error {
	return n.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (n nodeMessageOffsetDo) Save(values ...*model.NodeMessageOffset) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Save(values)
}

func (n nodeMessageOffsetDo) First() (*model.NodeMessageOffset, error) {
	if result, err := n.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.NodeMessageOffset), nil
	}
}

func (n nodeMessageOffsetDo) Take() (*model.NodeMessageOffset, error) {
	if result, err := n.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.NodeMessageOffset), nil
	}
}

func (n nodeMessageOffsetDo) Last() (*model.NodeMessageOffset, error) {
	if result, err := n.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.NodeMessageOffset), nil
	}
}

func (n nodeMessageOffsetDo) Find() ([]*model.NodeMessageOffset, error) {
	result, err := n.DO.Find()
	return result.([]*model.NodeMessageOffset), err
}

func (n nodeMessageOffsetDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.NodeMessageOffset, err error) {
	buf := make([]*model.NodeMessageOffset, 0, batchSize)
	err = n.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (n nodeMessageOffsetDo) FindInBatches(result *[]*model.NodeMessageOffset, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return n.DO.FindInBatches(result, batchSize, fc)
}

func (n nodeMessageOffsetDo) Attrs(attrs ...field.AssignExpr) INodeMessageOffsetDo {
	return n.withDO(n.DO.Attrs(attrs...))
}

func (n nodeMessageOffsetDo) Assign(attrs ...field.AssignExpr) INodeMessageOffsetDo {
	return n.withDO(n.DO.Assign(attrs...))
}

func (n nodeMessageOffsetDo) Joins(fields ...field.RelationField) INodeMessageOffsetDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Joins(_f))
	}
	return &n
}

func (n nodeMessageOffsetDo) Preload(fields ...field.RelationField) INodeMessageOffsetDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Preload(_f))
	}
	return &n
}

func (n nodeMessageOffsetDo) FirstOrInit() (*model.NodeMessageOffset, error) {
	if result, err := n.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.NodeMessageOffset), nil
	}
}

func (n nodeMessageOffsetDo) FirstOrCreate() (*model.NodeMessageOffset, error) {
	if result, err := n.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.NodeMessageOffset), nil
	}
}

func (n nodeMessageOffsetDo) FindByPage(offset int, limit int) (result []*model.NodeMessageOffset, count int64, err error) {
	result, err = n.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = n.Offset(-1).Limit(-1).Count()
	return
}

func (n nodeMessageOffsetDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = n.Count()
	if err != nil {
		return
	}

	err = n.Offset(offset).Limit(limit).Scan(result)
	return
}

func (n nodeMessageOffsetDo) Scan(result interface{}) (err error) {
	return n.DO.Scan(result)
}

func (n nodeMessageOffsetDo) Delete(models ...*model.NodeMessageOffset) (result gen.ResultInfo, err error) {
	return n.DO.Delete(models)
}

func (n *nodeMessageOffsetDo) withDO(do gen.Dao) *nodeMessageOffsetDo {
	n.DO = *do.(*gen.DO)
	return n
}
