// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/pax-beehive/pax-manager/internal/manager/storage/dal/model"
)

func newTransportJournal(db *gorm.DB, opts ...gen.DOOption) transportJournal {
	_transportJournal := transportJournal{}

	_transportJournal.transportJournalDo.UseDB(db, opts...)
	_transportJournal.transportJournalDo.UseModel(&model.TransportJournal{})

	tableName := _transportJournal.transportJournalDo.TableName()
	_transportJournal.ALL = field.NewAsterisk(tableName)
	_transportJournal.ID = field.NewInt64(tableName, "id")
	_transportJournal.AgentID = field.NewString(tableName, "agent_id")
	_transportJournal.Stream = field.NewString(tableName, "stream")
	_transportJournal.Seq = field.NewInt64(tableName, "seq")
	_transportJournal.LocalDirection = field.NewString(tableName, "local_direction")
	_transportJournal.PayloadJSON = field.NewString(tableName, "payload_json")
	_transportJournal.Status = field.NewString(tableName, "status")
	_transportJournal.Error = field.NewString(tableName, "error")
	_transportJournal.RetryCount = field.NewInt32(tableName, "retry_count")
	_transportJournal.CreatedAt = field.NewTime(tableName, "created_at")
	_transportJournal.UpdatedAt = field.NewTime(tableName, "updated_at")
	_transportJournal.SentAt = field.NewTime(tableName, "sent_at")
	_transportJournal.ReceivedAt = field.NewTime(tableName, "received_at")
	_transportJournal.AckedAt = field.NewTime(tableName, "acked_at")
	_transportJournal.AppliedAt = field.NewTime(tableName, "applied_at")

	_transportJournal.fillFieldMap()

	return _transportJournal
}

type transportJournal struct {
	transportJournalDo transportJournalDo

	ALL            field.Asterisk
	ID             field.Int64
	AgentID        field.String
	Stream         field.String
	Seq            field.Int64
	LocalDirection field.String
	PayloadJSON    field.String
	Status         field.String
	Error          field.String
	RetryCount     field.Int32
	CreatedAt      field.Time
	UpdatedAt      field.Time
	SentAt         field.Time
	ReceivedAt     field.Time
	AckedAt        field.Time
	AppliedAt      field.Time

	fieldMap map[string]field.Expr
}

func (t transportJournal) Table(newTableName string) *transportJournal {
	t.transportJournalDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t transportJournal) As(alias string) *transportJournal {
	t.transportJournalDo.DO = *(t.transportJournalDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *transportJournal) updateTableName(table string) *transportJournal {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt64(table, "id")
	t.AgentID = field.NewString(table, "agent_id")
	t.Stream = field.NewString(table, "stream")
	t.Seq = field.NewInt64(table, "seq")
	t.LocalDirection = field.NewString(table, "local_direction")
	t.PayloadJSON = field.NewString(table, "payload_json")
	t.Status = field.NewString(table, "status")
	t.Error = field.NewString(table, "error")
	t.RetryCount = field.NewInt32(table, "retry_count")
	t.CreatedAt = field.NewTime(table, "created_at")
	t.UpdatedAt = field.NewTime(table, "updated_at")
	t.SentAt = field.NewTime(table, "sent_at")
	t.ReceivedAt = field.NewTime(table, "received_at")
	t.AckedAt = field.NewTime(table, "acked_at")
	t.AppliedAt = field.NewTime(table, "applied_at")

	t.fillFieldMap()

	return t
}

func (t *transportJournal) WithContext(ctx context.Context) ITransportJournalDo {
	return t.transportJournalDo.WithContext(ctx)
}

func (t transportJournal) TableName() string { return t.transportJournalDo.TableName() }

func (t transportJournal) Alias() string { return t.transportJournalDo.Alias() }

func (t transportJournal) Columns(cols ...field.Expr) gen.Columns {
	return t.transportJournalDo.Columns(cols...)
}

func (t *transportJournal) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *transportJournal) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 15)
	t.fieldMap["id"] = t.ID
	t.fieldMap["agent_id"] = t.AgentID
	t.fieldMap["stream"] = t.Stream
	t.fieldMap["seq"] = t.Seq
	t.fieldMap["local_direction"] = t.LocalDirection
	t.fieldMap["payload_json"] = t.PayloadJSON
	t.fieldMap["status"] = t.Status
	t.fieldMap["error"] = t.Error
	t.fieldMap["retry_count"] = t.RetryCount
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
	t.fieldMap["sent_at"] = t.SentAt
	t.fieldMap["received_at"] = t.ReceivedAt
	t.fieldMap["acked_at"] = t.AckedAt
	t.fieldMap["applied_at"] = t.AppliedAt
}

func (t transportJournal) clone(db *gorm.DB) transportJournal {
	t.transportJournalDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t transportJournal) replaceDB(db *gorm.DB) transportJournal {
	t.transportJournalDo.ReplaceDB(db)
	return t
}

type transportJournalDo struct{ gen.DO }

type ITransportJournalDo interface {
	gen.SubQuery
	Debug() ITransportJournalDo
	WithContext(ctx context.Context) ITransportJournalDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITransportJournalDo
	WriteDB() ITransportJournalDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITransportJournalDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITransportJournalDo
	Not(conds ...gen.Condition) ITransportJournalDo
	Or(conds ...gen.Condition) ITransportJournalDo
	Select(conds ...field.Expr) ITransportJournalDo
	Where(conds ...gen.Condition) ITransportJournalDo
	Order(conds ...field.Expr) ITransportJournalDo
	Distinct(cols ...field.Expr) ITransportJournalDo
	Omit(cols ...field.Expr) ITransportJournalDo
	Join(table schema.Tabler, on ...field.Expr) ITransportJournalDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITransportJournalDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITransportJournalDo
	Group(cols ...field.Expr) ITransportJournalDo
	Having(conds ...gen.Condition) ITransportJournalDo
	Limit(limit int) ITransportJournalDo
	Offset(offset int) ITransportJournalDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITransportJournalDo
	Unscoped() ITransportJournalDo
	Create(values ...*model.TransportJournal) error
	CreateInBatches(values []*model.TransportJournal, batchSize int) error
	Save(values ...*model.TransportJournal) error
	First() (*model.TransportJournal, error)
	Take() (*model.TransportJournal, error)
	Last() (*model.TransportJournal, error)
	Find() ([]*model.TransportJournal, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TransportJournal, err error)
	FindInBatches(result *[]*model.TransportJournal, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TransportJournal) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITransportJournalDo
	Assign(attrs ...field.AssignExpr) ITransportJournalDo
	Joins(fields ...field.RelationField) ITransportJournalDo
	Preload(fields ...field.RelationField) ITransportJournalDo
	FirstOrInit() (*model.TransportJournal, error)
	FirstOrCreate() (*model.TransportJournal, error)
	FindByPage(offset int, limit int) (result []*model.TransportJournal, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITransportJournalDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t transportJournalDo) Debug() ITransportJournalDo {
	return t.withDO(t.DO.Debug())
}

func (t transportJournalDo) WithContext(ctx context.Context) ITransportJournalDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t transportJournalDo) ReadDB() ITransportJournalDo {
	return t.Clauses(dbresolver.Read)
}

func (t transportJournalDo) WriteDB() ITransportJournalDo {
	return t.Clauses(dbresolver.Write)
}

func (t transportJournalDo) Session(config *gorm.Session) ITransportJournalDo {
	return t.withDO(t.DO.Session(config))
}

func (t transportJournalDo) Clauses(conds ...clause.Expression) ITransportJournalDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t transportJournalDo) Returning(value interface{}, columns ...string) ITransportJournalDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t transportJournalDo) Not(conds ...gen.Condition) ITransportJournalDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t transportJournalDo) Or(conds ...gen.Condition) ITransportJournalDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t transportJournalDo) Select(conds ...field.Expr) ITransportJournalDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t transportJournalDo) Where(conds ...gen.Condition) ITransportJournalDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t transportJournalDo) Order(conds ...field.Expr) ITransportJournalDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t transportJournalDo) Distinct(cols ...field.Expr) ITransportJournalDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t transportJournalDo) Omit(cols ...field.Expr) ITransportJournalDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t transportJournalDo) Join(table schema.Tabler, on ...field.Expr) ITransportJournalDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t transportJournalDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITransportJournalDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t transportJournalDo) RightJoin(table schema.Tabler, on ...field.Expr) ITransportJournalDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t transportJournalDo) Group(cols ...field.Expr) ITransportJournalDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t transportJournalDo) Having(conds ...gen.Condition) ITransportJournalDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t transportJournalDo) Limit(limit int) ITransportJournalDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t transportJournalDo) Offset(offset int) ITransportJournalDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t transportJournalDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITransportJournalDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t transportJournalDo) Unscoped() ITransportJournalDo {
	return t.withDO(t.DO.Unscoped())
}

func (t transportJournalDo) Create(values ...*model.TransportJournal) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t transportJournalDo) CreateInBatches(values []*model.TransportJournal, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t transportJournalDo) Save(values ...*model.TransportJournal) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t transportJournalDo) First() (*model.TransportJournal, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TransportJournal), nil
	}
}

func (t transportJournalDo) Take() (*model.TransportJournal, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TransportJournal), nil
	}
}

func (t transportJournalDo) Last() (*model.TransportJournal, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TransportJournal), nil
	}
}

func (t transportJournalDo) Find() ([]*model.TransportJournal, error) {
	result, err := t.DO.Find()
	return result.([]*model.TransportJournal), err
}

func (t transportJournalDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TransportJournal, err error) {
	buf := make([]*model.TransportJournal, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t transportJournalDo) FindInBatches(result *[]*model.TransportJournal, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t transportJournalDo) Attrs(attrs ...field.AssignExpr) ITransportJournalDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t transportJournalDo) Assign(attrs ...field.AssignExpr) ITransportJournalDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t transportJournalDo) Joins(fields ...field.RelationField) ITransportJournalDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t transportJournalDo) Preload(fields ...field.RelationField) ITransportJournalDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t transportJournalDo) FirstOrInit() (*model.TransportJournal, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TransportJournal), nil
	}
}

func (t transportJournalDo) FirstOrCreate() (*model.TransportJournal, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TransportJournal), nil
	}
}

func (t transportJournalDo) FindByPage(offset int, limit int) (result []*model.TransportJournal, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t transportJournalDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t transportJournalDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t transportJournalDo) Delete(models ...*model.TransportJournal) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *transportJournalDo) withDO(do gen.Dao) *transportJournalDo {
	t.DO = *do.(*gen.DO)
	return t
}
