// Code generated by hertz generator.

package handler

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"

	api "github.com/pax-beehive/pax-manager/internal/transport/http/model/paxmanager/api"
)

// CreateUserAPIKey .
// @router /api/user/api-keys [POST]
func CreateUserAPIKey(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.CreateUserAPIKeyRequest
	err = c.BindJSON(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	serviceFromContext(c).CreateUserAPIKey(ctx, c, &req)
}
