// Code generated by hertz generator.

package handler

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	api "github.com/pax-beehive/pax-manager/internal/transport/http/model/paxmanager/api"
)

// ListProjectTargets .
// @router /api/v1/user/:user_id/projects/:project_id/targets [GET]
func ListProjectTargets(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.ListProjectTargetsRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.ProjectTargetListResponse)

	c.JSON(consts.StatusOK, resp)
}
