// Code generated by hertz generator.

package handler

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	api "github.com/pax-beehive/pax-manager/internal/transport/http/model/paxmanager/api"
)

// ListSessionMessages .
// @router /api/user/sessions/:sessionId/messages [GET]
func ListSessionMessages(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.ListSessionMessagesRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	serviceFromContext(c).ListSessionMessages(ctx, c, &req)
}
