// Code generated by hertz generator.

package handler

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"

	api "github.com/pax-beehive/pax-manager/internal/transport/http/model/paxmanager/api"
)

// ListUserAuditEvents .
// @router /api/v1/user/:user_id/audit-events [GET]
func ListUserAuditEvents(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.ListUserAuditEventsRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.AuditEventListResponse)

	c.JSON(consts.StatusOK, resp)
}
