// Code generated by hertz generator.

package handler

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"

	api "github.com/pax-beehive/pax-manager/internal/transport/http/model/paxmanager/api"
)

// PullNodeAgentSessionMailbox .
// @router /api/v1/node/agents/:agent_id/sessions/:session_id/mailbox [GET]
func PullNodeAgentSessionMailbox(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.PullNodeAgentSessionMailboxRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	serviceFromContext(c).HandleGenerated(ctx, c, "PullNodeAgentSessionMailbox")
}
