// Code generated by hertz generator.

package handler

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"

	api "github.com/pax-beehive/pax-manager/internal/transport/http/model/paxmanager/api"
)

// PullSessionMailbox .
// @router /api/agent/sessions/:sessionId/mailbox [GET]
func PullSessionMailbox(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.PullSessionMailboxRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	if req.GetSessionID() == "" {
		sessionID := c.Param("sessionId")
		req.SessionID = &sessionID
	}

	serviceFromContext(c).PullSessionMailbox(ctx, c, &req)
}
