// Code generated by hertz generator.

package handler

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"

	api "github.com/pax-beehive/pax-manager/internal/transport/http/model/paxmanager/api"
)

// RegisterNode .
// @router /api/v1/node/register [POST]
func RegisterNode(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.RegisterNodeRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	serviceFromContext(c).HandleGenerated(ctx, c, "RegisterNode")
}
