// Code generated by hertz generator.

package handler

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"

	api "github.com/pax-beehive/pax-manager/internal/transport/http/model/paxmanager/api"
)

// UpdateNode .
// @router /api/v1/user/:user_id/nodes/:node_id [PATCH]
func UpdateNode(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.UpdateNodeRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	serviceFromContext(c).HandleGenerated(ctx, c, "UpdateNode")
}
