package manager

func addArtifactPublicationPaths(doc map[string]any) {
	paths, ok := doc["paths"].(map[string]any)
	if !ok {
		paths = map[string]any{}
		doc["paths"] = paths
	}
	publicationPathParam := map[string]any{
		"name":        "publication_id",
		"in":          "path",
		"required":    true,
		"schema":      map[string]string{"type": "string"},
		"description": "Artifact publication identifier generated by paxd.",
	}
	paths[openAPINodeArtifactPublication] = map[string]any{
		"put": map[string]any{
			"tags":        []string{"node"},
			"summary":     "Register an agent artifact publication",
			"description": "Idempotently registers a publication for an agent session owned by the authenticated node.",
			"security":    []map[string][]string{{"nodeBearer": {}}},
			"parameters":  []map[string]any{publicationPathParam},
			"responses": map[string]any{
				"200": map[string]string{"description": "Registered publication."},
				"400": map[string]string{"description": "Invalid publication metadata."},
				"401": map[string]string{"description": "Node authentication failed."},
				"404": map[string]string{"description": "Agent or session not found on this node."},
				"409": map[string]string{
					"description": "Publication identifier is already bound to another source.",
				},
			},
		},
	}
	paths[openAPIUserArtifactPublication] = map[string]any{
		"get": map[string]any{
			"tags":        []string{"user"},
			"summary":     "Get an artifact publication",
			"description": "Returns publication state when it belongs to the authenticated user.",
			"security":    []map[string][]string{{"cloudflareAccess": {}}},
			"parameters": []map[string]any{
				{
					"name":        "user_id",
					"in":          "path",
					"required":    true,
					"schema":      map[string]string{"type": "string"},
					"description": "User identifier or self.",
				},
				publicationPathParam,
			},
			"responses": map[string]any{
				"200": map[string]string{"description": "Artifact publication."},
				"401": map[string]string{"description": "User authentication failed."},
				"404": map[string]string{"description": "Artifact publication not found."},
			},
		},
	}
}
