package manager

import (
	hertzserver "github.com/cloudwego/hertz/pkg/app/server"
)

// Code generated by cmd/openapi-gen from api/pax_manager.thrift; DO NOT EDIT.
func registerIDLRoutes(h *hertzserver.Hertz) {
	h.GET("/health", Health)
	h.POST("/api/agent/register", RegisterAgent)
	h.POST("/api/agent/status", AgentAuth(), ReportAgentStatus)
	h.GET("/api/agent/mailbox", AgentAuth(), PullMailbox)
	h.GET("/api/agent/sessions/:sessionId/mailbox", AgentAuth(), PullSessionMailbox)
	h.POST("/api/agent/messages/offset", AgentAuth(), UpdateMailboxOffset)
	h.POST("/api/agent/messages/:messageId/result", AgentAuth(), ReportMessageResult)
	h.GET("/api/user/agents", ListAgents)
	h.GET("/api/user/agents/:agentId", GetAgent)
	h.GET("/api/user/agents/:agentId/sessions", ListAgentSessions)
	h.GET("/api/user/agents/:agentId/sessions/:sessionId", GetAgentSession)
	h.GET("/api/user/agents/:agentId/messages", ListAgentMessages)
	h.POST("/api/user/agents/:agentId/messages", CreateAgentMessage)
	h.GET("/api/user/agents/:agentId/sessions/:sessionId/messages", ListAgentSessionMessages)
	h.POST("/api/user/agents/:agentId/sessions/:sessionId/messages", CreateSessionMessage)
	h.GET("/api/user/api-keys", ListUserAPIKeys)
	h.POST("/api/user/api-keys", CreateUserAPIKey)
	h.DELETE("/api/user/api-keys/:keyId", RevokeUserAPIKey)
	h.POST("/api/user/agent-registration-tokens", CreateAgentRegistrationToken)
}
