package manager

const (
	routeLegacyHealth         = "/health"
	routeLegacyAgentRegister  = "/api/agent/register"
	routeLegacyAgentStatus    = "/api/agent/status"
	routeLegacyAgentMailbox   = "/api/agent/mailbox"
	routeLegacySessionMailbox = "/api/agent/sessions/:sessionId/mailbox"
	routeLegacyAgentOffset    = "/api/agent/messages/offset"
	routeLegacyMessageResult  = "/api/agent/messages/:messageId/result"

	routeLegacyListAgents         = "/api/user/agents"
	routeLegacyGetAgent           = "/api/user/agents/:agentId"
	routeUserAgents               = "/api/v1/user/:user_id/agents"
	routeUserAgent                = "/api/v1/user/:user_id/agents/:agent_id"
	routeLegacyListAgentSessions  = "/api/user/agents/:agentId/sessions"
	routeLegacyGetAgentSession    = "/api/user/agents/:agentId/sessions/:sessionId"
	routeLegacyAgentMessages      = "/api/user/agents/:agentId/messages"
	routeLegacySessionMessages    = "/api/user/agents/:agentId/sessions/:sessionId/messages"
	routeLegacyUserAPIKeys        = "/api/user/api-keys"
	routeLegacyUserAPIKey         = "/api/user/api-keys/:keyId"
	routeLegacyRegistrationTokens = "/api/user/agent-registration-tokens"

	routeLegacySessionHistory = "/api/user/agents/:agentId/sessions/:sessionId/history"
	routeSessionHistory       = "/api/v1/user/:user_id/agents/:agent_id/sessions/:session_id/history"
	routeUserSessionHistory   = "/api/v1/user/:user_id/sessions/:session_id/history"

	routeCreateKnowledgeCapsule  = "/api/v1/user/:user_id/sessions/:session_id/knowledge-capsules"
	routeListKnowledgeCapsules   = "/api/v1/user/:user_id/knowledge-capsules"
	routeGetKnowledgeCapsule     = "/api/v1/user/:user_id/knowledge-capsules/:capsule_id"
	routeArchiveKnowledgeCapsule = "/api/v1/user/:user_id/knowledge-capsules/:capsule_id/archive"
	routeInjectKnowledgeCapsule  = "/api/v1/user/:user_id/sessions/:session_id/knowledge-injections"
	routeListKnowledgeInjections = "/api/v1/user/:user_id/sessions/:session_id/knowledge-injections"

	routeCreateEnvelope  = "/api/v1/user/:user_id/envelopes"
	routeListEnvelopes   = "/api/v1/user/:user_id/envelopes"
	routeGetEnvelope     = "/api/v1/user/:user_id/envelopes/:envelope_id"
	routeAcceptEnvelope  = "/api/v1/user/:user_id/envelopes/:envelope_id/accept"
	routeArchiveEnvelope = "/api/v1/user/:user_id/envelopes/:envelope_id/archive"

	routeCreateFriend = "/api/v1/user/:user_id/friends"
	routeListFriends  = "/api/v1/user/:user_id/friends"
	routeGetFriend    = "/api/v1/user/:user_id/friends/:friend_id"
	routeAcceptFriend = "/api/v1/user/:user_id/friends/:friend_id/accept"
	routeAliasFriend  = "/api/v1/user/:user_id/friends/:friend_id/alias"
	routeRemoveFriend = "/api/v1/user/:user_id/friends/:friend_id/remove"
	routeBlockFriend  = "/api/v1/user/:user_id/friends/:friend_id/block"

	routeCreateTeam          = "/api/v1/user/:user_id/teams"
	routeListTeams           = "/api/v1/user/:user_id/teams"
	routeGetTeam             = "/api/v1/user/:user_id/teams/:team_id"
	routeArchiveTeam         = "/api/v1/user/:user_id/teams/:team_id/archive"
	routeListTeamMembers     = "/api/v1/user/:user_id/teams/:team_id/members"
	routeUpdateTeamMember    = "/api/v1/user/:user_id/teams/:team_id/members/:member_user_id/role"
	routeRemoveTeamMember    = "/api/v1/user/:user_id/teams/:team_id/members/:member_user_id"
	routeLeaveTeam           = "/api/v1/user/:user_id/teams/:team_id/leave"
	routeCreateTeamInvite    = "/api/v1/user/:user_id/teams/:team_id/invites"
	routeCancelTeamInvite    = "/api/v1/user/:user_id/teams/:team_id/invites/:invite_id/cancel"
	routeListTeamSentInvites = "/api/v1/user/:user_id/teams/:team_id/invites"
	routeListTeamInvites     = "/api/v1/user/:user_id/team-invites"
	routeAcceptTeamInvite    = "/api/v1/user/:user_id/team-invites/:invite_id/accept"
	routeDeclineTeamInvite   = "/api/v1/user/:user_id/team-invites/:invite_id/decline"
	routeListTeamAgents      = "/api/v1/user/:user_id/teams/:team_id/agents"
	routeAddTeamAgent        = "/api/v1/user/:user_id/teams/:team_id/agents"
	routeRemoveTeamAgent     = "/api/v1/user/:user_id/teams/:team_id/agents/:agent_id"
	routeListTeamAudit       = "/api/v1/user/:user_id/teams/:team_id/audit"
	routeTeamMemexIndex      = "/api/v1/user/:user_id/teams/:team_id/memex/index"
	routeTeamMemexDocuments  = "/api/v1/user/:user_id/teams/:team_id/memex/documents"
	routeTeamMemexDocument   = "/api/v1/user/:user_id/teams/:team_id/memex/documents/*document_path"
	routeTeamMemexRuns       = "/api/v1/user/:user_id/teams/:team_id/memex/runs"
	routeTeamMemexRun        = "/api/v1/user/:user_id/teams/:team_id/memex/runs/:run_id"

	routeCreateArtifactUpload       = "/api/v1/user/:user_id/artifact-uploads"
	routeCompleteArtifactUpload     = "/api/v1/user/:user_id/artifact-uploads/:upload_id/complete"
	routeCreateUserAttachment       = "/api/v1/user/:user_id/attachments"
	routeCompleteUserAttachment     = "/api/v1/user/:user_id/attachments/:attachment_id/complete"
	routeCreateSessionArtifact      = "/api/v1/user/:user_id/artifacts"
	routeGetSessionArtifact         = "/api/v1/user/:user_id/artifacts/:artifact_id"
	routeArtifactContent            = "/api/v1/user/:user_id/artifacts/:artifact_id/content/:content_ref"
	routeAttachSessionArtifact      = "/api/v1/user/:user_id/artifacts/:artifact_id/attachments"
	routeListSessionArtifacts       = "/api/v1/user/:user_id/sessions/:session_id/artifacts"
	routePutArtifactPublication     = "/api/v1/node/artifact-publications/:publication_id"
	routePrepareArtifactPublication = "/api/v1/node/artifact-publications/:publication_id/prepare"
	routeFailArtifactPublication    = "/api/v1/node/artifact-publications/:publication_id/failed"
	routeCompleteNodeArtifactUpload = "/api/v1/node/artifact-uploads/:upload_id/complete"
	routeGetArtifactPublication     = "/api/v1/user/:user_id/artifact-publications/:publication_id"

	routeOpenAPI     = "/openapi"
	routeOpenAPIJSON = "/openapi.json"
	routeEcho        = "/api/echo"

	routeStartNodeRegistration   = "/api/v1/node/registration/start"
	routePollNodeRegistration    = "/api/v1/node/registration/poll"
	routeGetNodeRegistration     = "/api/v1/user/:user_id/node-registrations/:pair_code"
	routeApproveNodeRegistration = "/api/v1/user/:user_id/node-registrations/:pair_code/approve"

	routeStartPaxlDeviceLogin   = "/api/v1/paxl/device-login/start"
	routePollPaxlDeviceLogin    = "/api/v1/paxl/device-login/poll"
	routeApprovePaxlDeviceLogin = "/api/v1/user/:user_id/paxl/device-logins/:user_code/approve"

	routeLegacyAgentWS                 = "/api/agent/ws"
	routeNodeControlTunnel             = "/api/v1/node/control"
	routeAgentACPTunnel                = "/api/v1/agent/tunnel"
	routeUserACPTunnel                 = "/api/v1/user/:userID/agents/:agentID/tunnel"
	routeUserSessionACPTunnel          = "/api/v1/user/:userID/agents/:agentID/sessions/:sessionID/tunnel"
	routeUserSessionTurnStop           = "/api/v1/user/:userID/agents/:agentID/sessions/:sessionID/turn/stop"
	routeUserSessionTurnQueue          = "/api/v1/user/:userID/agents/:agentID/sessions/:sessionID/turn/queue"
	routeUserSessionTurnSteer          = "/api/v1/user/:userID/agents/:agentID/sessions/:sessionID/turn/steer"
	routeUserSessionEvents             = "/api/v1/user/:userID/agents/:agentID/sessions/:sessionID/events"
	routeUserConversation              = "/api/v1/user/:userID/nodes/:nodeID/agents/:agentID/conversation"
	routeDeliverAgentConversation      = "/api/v1/node/conversation/deliver"
	routeStartAgentConversation        = "/api/v1/node/agents/:agent_id/conversations"
	routeGetAgentOwnerInfo             = "/api/v1/user/:user_id/agent-owner-info"
	routeListRepresentativeAgents      = "/api/v1/user/:user_id/representative-agents"
	routeUpsertRepresentativeAgent     = "/api/v1/user/:user_id/representative-agents"
	routeStartUserAgentInquiry         = "/api/v1/user/:user_id/nodes/:node_id/agents/:agent_id/inquiries"
	routeListAgentConversationMessages = "/api/v1/user/:user_id/conversations/:conversation_id/messages"

	routeDownloadGenericArtifact = "/api/v1/public/artifacts/download"
	routeDownloadPaxdArtifact    = "/api/v1/public/paxd/download"
	routeDownloadPaxlArtifact    = "/api/v1/public/paxl/download"
	routeDownloadPaxdInstaller   = "/api/v1/public/paxd/install.sh"
	routeDownloadPaxlInstaller   = "/api/v1/public/paxl/install.sh"
	routePublishGenericArtifact  = "/api/v1/admin/artifacts"
	routePublishPaxdArtifact     = "/api/v1/admin/paxd/artifacts"

	openAPISessionHistoryPath         = "/api/v1/user/{user_id}/agents/{agent_id}/sessions/{session_id}/history"
	openAPIUserSessionHistoryPath     = "/api/v1/user/{user_id}/sessions/{session_id}/history"
	openAPIUserAgentsPath             = "/api/v1/user/{user_id}/agents"
	openAPIUserAgentPath              = "/api/v1/user/{user_id}/agents/{agent_id}"
	openAPIUserACPTunnelPath          = "/api/v1/user/{user_id}/agents/{agent_id}/tunnel"
	openAPIUserSessionACPTunnelPath   = "/api/v1/user/{user_id}/agents/{agent_id}/sessions/{session_id}/tunnel"
	openAPIUserSessionTurnStopPath    = "/api/v1/user/{user_id}/agents/{agent_id}/sessions/{session_id}/turn/stop"
	openAPIUserSessionTurnQueuePath   = "/api/v1/user/{user_id}/agents/{agent_id}/sessions/{session_id}/turn/queue"
	openAPIUserSessionTurnSteerPath   = "/api/v1/user/{user_id}/agents/{agent_id}/sessions/{session_id}/turn/steer"
	openAPIUserSessionEventsPath      = "/api/v1/user/{user_id}/agents/{agent_id}/sessions/{session_id}/events"
	openAPINodeConversationDeliver    = "/api/v1/node/conversation/deliver"
	openAPINodeArtifactPublication    = "/api/v1/node/artifact-publications/{publication_id}"
	openAPINodeArtifactUploadComplete = "/api/v1/node/artifact-uploads/{upload_id}/complete"
	openAPIUserArtifactPublication    = "/api/v1/user/{user_id}/artifact-publications/{publication_id}"
)
