// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAgentApproval = "agent_approvals"

// AgentApproval mapped from table <agent_approvals>
type AgentApproval struct {
	ApprovalID            string     `gorm:"column:approval_id;type:text;primaryKey" json:"approval_id"`
	OwnerUserID           string     `gorm:"column:owner_user_id;type:text;not null;index:idx_agent_approvals_grant_lookup,priority:1;index:idx_agent_approvals_owner_status,priority:1;index:idx_agent_approvals_request_origin,priority:1;index:idx_agent_approvals_resource,priority:1" json:"owner_user_id"`
	RequestNodeID         *string    `gorm:"column:request_node_id;type:text;index:idx_agent_approvals_request_origin,priority:2" json:"request_node_id"`
	RequestAgentID        *string    `gorm:"column:request_agent_id;type:text;index:idx_agent_approvals_request_origin,priority:3" json:"request_agent_id"`
	RequestSessionID      string     `gorm:"column:request_session_id;type:text;not null;index:idx_agent_approvals_request_origin,priority:4" json:"request_session_id"`
	SourceMessageID       string     `gorm:"column:source_message_id;type:text;not null" json:"source_message_id"`
	GrantNodeID           string     `gorm:"column:grant_node_id;type:text;not null;index:idx_agent_approvals_grant_lookup,priority:2" json:"grant_node_id"`
	GrantAgentID          string     `gorm:"column:grant_agent_id;type:text;not null;index:idx_agent_approvals_grant_lookup,priority:3" json:"grant_agent_id"`
	GrantSessionID        string     `gorm:"column:grant_session_id;type:text;not null;index:idx_agent_approvals_grant_lookup,priority:4" json:"grant_session_id"`
	Domain                string     `gorm:"column:domain;type:text;not null;index:idx_agent_approvals_grant_lookup,priority:5" json:"domain"`
	Operation             string     `gorm:"column:operation;type:text;not null;index:idx_agent_approvals_grant_lookup,priority:6" json:"operation"`
	ResourceType          string     `gorm:"column:resource_type;type:text;not null;index:idx_agent_approvals_resource,priority:2" json:"resource_type"`
	ResourceRef           string     `gorm:"column:resource_ref;type:text;not null;index:idx_agent_approvals_resource,priority:3" json:"resource_ref"`
	Title                 string     `gorm:"column:title;type:text;not null" json:"title"`
	Description           string     `gorm:"column:description;type:text;not null" json:"description"`
	RiskLevel             *string    `gorm:"column:risk_level;type:text;not null;default:unknown" json:"risk_level"`
	ActionFingerprint     string     `gorm:"column:action_fingerprint;type:text;not null;index:idx_agent_approvals_grant_lookup,priority:7" json:"action_fingerprint"`
	RequestBody           *string    `gorm:"column:request_body;type:jsonb;not null;default:{}" json:"request_body"`
	RequestedEffects      *string    `gorm:"column:requested_effects;type:jsonb;not null;default:[]" json:"requested_effects"`
	Options               *string    `gorm:"column:options;type:jsonb;not null;default:[]" json:"options"`
	Status                *string    `gorm:"column:status;type:text;not null;index:idx_agent_approvals_owner_status,priority:2;default:pending" json:"status"`
	Decision              string     `gorm:"column:decision;type:text;not null;index:idx_agent_approvals_grant_lookup,priority:8" json:"decision"`
	DecisionOption        string     `gorm:"column:decision_option;type:text;not null" json:"decision_option"`
	DecisionScope         string     `gorm:"column:decision_scope;type:text;not null" json:"decision_scope"`
	GrantBody             *string    `gorm:"column:grant_body;type:jsonb;not null;default:{}" json:"grant_body"`
	DecidedByUserID       *string    `gorm:"column:decided_by_user_id;type:text" json:"decided_by_user_id"`
	GrantRevokedAt        *time.Time `gorm:"column:grant_revoked_at;type:timestamp with time zone" json:"grant_revoked_at"`
	GrantRevokedByUserID  *string    `gorm:"column:grant_revoked_by_user_id;type:text" json:"grant_revoked_by_user_id"`
	GrantRevocationReason string     `gorm:"column:grant_revocation_reason;type:text;not null" json:"grant_revocation_reason"`
	CreatedAt             *time.Time `gorm:"column:created_at;type:timestamp with time zone;not null;index:idx_agent_approvals_owner_status,priority:3;index:idx_agent_approvals_request_origin,priority:5;index:idx_agent_approvals_resource,priority:4;default:now()" json:"created_at"`
	ExpiresAt             *time.Time `gorm:"column:expires_at;type:timestamp with time zone" json:"expires_at"`
	DecidedAt             *time.Time `gorm:"column:decided_at;type:timestamp with time zone;index:idx_agent_approvals_grant_lookup,priority:9" json:"decided_at"`
	RawPayload            *string    `gorm:"column:raw_payload;type:jsonb;not null;default:{}" json:"raw_payload"`
}

// TableName AgentApproval's table name
func (*AgentApproval) TableName() string {
	return TableNameAgentApproval
}
