// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAgentRegistrationToken = "agent_registration_tokens"

// AgentRegistrationToken mapped from table <agent_registration_tokens>
type AgentRegistrationToken struct {
	TokenHash   string     `gorm:"column:token_hash;type:text;primaryKey" json:"token_hash"`
	OwnerUserID string     `gorm:"column:owner_user_id;type:text;not null;index:idx_registration_tokens_owner,priority:1" json:"owner_user_id"`
	ExpiresAt   *time.Time `gorm:"column:expires_at;type:timestamp with time zone" json:"expires_at"`
	UsedAt      *time.Time `gorm:"column:used_at;type:timestamp with time zone" json:"used_at"`
	CreatedAt   *time.Time `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"created_at"`
}

// TableName AgentRegistrationToken's table name
func (*AgentRegistrationToken) TableName() string {
	return TableNameAgentRegistrationToken
}
