// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameKnowledgeCapsule = "knowledge_capsules"

// KnowledgeCapsule mapped from table <knowledge_capsules>
type KnowledgeCapsule struct {
	CapsuleID              string     `gorm:"column:capsule_id;type:text;primaryKey" json:"capsule_id"`
	OwnerUserID            string     `gorm:"column:owner_user_id;type:text;not null;index:idx_knowledge_capsules_keyword,priority:1;index:idx_knowledge_capsules_owner_status,priority:1;index:idx_knowledge_capsules_source_session,priority:1" json:"owner_user_id"`
	SourceSessionID        string     `gorm:"column:source_session_id;type:text;not null;index:idx_knowledge_capsules_source_session,priority:2" json:"source_session_id"`
	SourceAgentID          string     `gorm:"column:source_agent_id;type:text;not null" json:"source_agent_id"`
	SourceNodeID           string     `gorm:"column:source_node_id;type:text;not null" json:"source_node_id"`
	CreatedByUserID        string     `gorm:"column:created_by_user_id;type:text;not null" json:"created_by_user_id"`
	Keyword                string     `gorm:"column:keyword;type:text;not null;index:idx_knowledge_capsules_keyword,priority:2" json:"keyword"`
	Title                  string     `gorm:"column:title;type:text;not null" json:"title"`
	Summary                string     `gorm:"column:summary;type:text;not null" json:"summary"`
	Content                string     `gorm:"column:content;type:text;not null" json:"content"`
	SuggestedSkillsJSON    *string    `gorm:"column:suggested_skills_json;type:jsonb;not null;default:[]" json:"suggested_skills_json"`
	ReferencesJSON         *string    `gorm:"column:references_json;type:jsonb;not null;default:[]" json:"references_json"`
	OpenQuestionsJSON      *string    `gorm:"column:open_questions_json;type:jsonb;not null;default:[]" json:"open_questions_json"`
	RisksJSON              *string    `gorm:"column:risks_json;type:jsonb;not null;default:[]" json:"risks_json"`
	RedactionsJSON         *string    `gorm:"column:redactions_json;type:jsonb;not null;default:[]" json:"redactions_json"`
	Status                 *string    `gorm:"column:status;type:text;not null;index:idx_knowledge_capsules_owner_status,priority:2;default:active" json:"status"`
	Truncated              bool       `gorm:"column:truncated;type:boolean;not null" json:"truncated"`
	OriginalEstimatedChars int64      `gorm:"column:original_estimated_chars;type:bigint;not null" json:"original_estimated_chars"`
	CreatedAt              *time.Time `gorm:"column:created_at;type:timestamp with time zone;not null;index:idx_knowledge_capsules_keyword,priority:3;index:idx_knowledge_capsules_owner_status,priority:3;index:idx_knowledge_capsules_source_session,priority:3;default:now()" json:"created_at"`
	ArchivedAt             *time.Time `gorm:"column:archived_at;type:timestamp with time zone" json:"archived_at"`
}

// TableName KnowledgeCapsule's table name
func (*KnowledgeCapsule) TableName() string {
	return TableNameKnowledgeCapsule
}
