// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMailbox = "mailbox"

// Mailbox mapped from table <mailbox>
type Mailbox struct {
	ID              int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;index:idx_mailbox_agent,priority:1;index:idx_mailbox_node,priority:1;index:idx_mailbox_owner,priority:1;index:idx_mailbox_session,priority:1" json:"id"`
	MessageID       string     `gorm:"column:message_id;type:text;not null" json:"message_id"`
	UserID          string     `gorm:"column:user_id;type:text;not null" json:"user_id"`
	OwnerUserID     string     `gorm:"column:owner_user_id;type:text;not null;index:idx_mailbox_owner,priority:2" json:"owner_user_id"`
	AgentID         string     `gorm:"column:agent_id;type:text;not null;index:idx_mailbox_agent,priority:2" json:"agent_id"`
	SessionID       *string    `gorm:"column:session_id;type:text;index:idx_mailbox_session,priority:2" json:"session_id"`
	Message         string     `gorm:"column:message;type:text;not null" json:"message"`
	MessageType     *string    `gorm:"column:message_type;type:text;not null;default:chat" json:"message_type"`
	Payload         *string    `gorm:"column:payload;type:jsonb" json:"payload"`
	Status          *string    `gorm:"column:status;type:text;not null;index:idx_mailbox_agent,priority:3;index:idx_mailbox_node,priority:2;default:pending" json:"status"`
	DeliveredAt     *time.Time `gorm:"column:delivered_at;type:timestamp with time zone" json:"delivered_at"`
	CompletedAt     *time.Time `gorm:"column:completed_at;type:timestamp with time zone" json:"completed_at"`
	Result          *string    `gorm:"column:result;type:text" json:"result"`
	Error           *string    `gorm:"column:error;type:text" json:"error"`
	CreatedAt       *time.Time `gorm:"column:created_at;type:timestamp with time zone;not null;index:idx_mailbox_created,priority:1;default:now()" json:"created_at"`
	ExpiresAt       *time.Time `gorm:"column:expires_at;type:timestamp with time zone" json:"expires_at"`
	NodeID          *string    `gorm:"column:node_id;type:text;index:idx_mailbox_node,priority:3" json:"node_id"`
	Direction       *string    `gorm:"column:direction;type:text;not null;default:user_to_node" json:"direction"`
	ParentMessageID *string    `gorm:"column:parent_message_id;type:text" json:"parent_message_id"`
	TurnID          *string    `gorm:"column:turn_id;type:text" json:"turn_id"`
	ResponseID      *string    `gorm:"column:response_id;type:text" json:"response_id"`
	Events          *string    `gorm:"column:events;type:jsonb" json:"events"`
	FileChanges     *string    `gorm:"column:file_changes;type:jsonb;not null;default:[]" json:"file_changes"`
	TokenUsage      *string    `gorm:"column:token_usage;type:jsonb" json:"token_usage"`
}

// TableName Mailbox's table name
func (*Mailbox) TableName() string {
	return TableNameMailbox
}
