// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameNodeMessageOffset = "node_message_offsets"

// NodeMessageOffset mapped from table <node_message_offsets>
type NodeMessageOffset struct {
	NodeID     string     `gorm:"column:node_id;type:text;primaryKey" json:"node_id"`
	LastOffset int64      `gorm:"column:last_offset;type:bigint;not null" json:"last_offset"`
	UpdatedAt  *time.Time `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now()" json:"updated_at"`
}

// TableName NodeMessageOffset's table name
func (*NodeMessageOffset) TableName() string {
	return TableNameNodeMessageOffset
}
