// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameNode = "nodes"

// Node mapped from table <nodes>
type Node struct {
	NodeID        string     `gorm:"column:node_id;type:text;primaryKey" json:"node_id"`
	OwnerUserID   string     `gorm:"column:owner_user_id;type:text;not null;index:idx_nodes_owner,priority:1" json:"owner_user_id"`
	Name          string     `gorm:"column:name;type:text;not null" json:"name"`
	Hostname      string     `gorm:"column:hostname;type:text;not null" json:"hostname"`
	MachineType   string     `gorm:"column:machine_type;type:text;not null" json:"machine_type"`
	Os            *string    `gorm:"column:os;type:text;not null;default:unknown" json:"os"`
	Arch          string     `gorm:"column:arch;type:text;not null" json:"arch"`
	PaxdVersion   string     `gorm:"column:paxd_version;type:text;not null" json:"paxd_version"`
	APIEndpoint   *string    `gorm:"column:api_endpoint;type:text;not null;default:http://localhost:8642" json:"api_endpoint"`
	APIKeyHash    string     `gorm:"column:api_key_hash;type:text;not null" json:"api_key_hash"`
	Status        *string    `gorm:"column:status;type:text;not null;default:offline" json:"status"`
	LastHeartbeat *time.Time `gorm:"column:last_heartbeat;type:timestamp with time zone" json:"last_heartbeat"`
	RegisteredAt  *time.Time `gorm:"column:registered_at;type:timestamp with time zone;not null;default:now()" json:"registered_at"`
	Metadata      *string    `gorm:"column:metadata;type:jsonb" json:"metadata"`
}

// TableName Node's table name
func (*Node) TableName() string {
	return TableNameNode
}
