// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSecret = "secrets"

// Secret mapped from table <secrets>
type Secret struct {
	SecretID         string         `gorm:"column:secret_id;type:text;primaryKey" json:"secret_id"`
	OwnerUserID      string         `gorm:"column:owner_user_id;type:text;not null;index:idx_secrets_owner,priority:1" json:"owner_user_id"`
	Name             string         `gorm:"column:name;type:text;not null" json:"name"`
	Kind             string         `gorm:"column:kind;type:text;not null" json:"kind"`
	Description      string         `gorm:"column:description;type:text;not null" json:"description"`
	Metadata         *string        `gorm:"column:metadata;type:jsonb;not null;default:{}" json:"metadata"`
	CurrentVersionID *string        `gorm:"column:current_version_id;type:text" json:"current_version_id"`
	CurrentVersion   int64          `gorm:"column:current_version;type:bigint;not null" json:"current_version"`
	CreatedAt        *time.Time     `gorm:"column:created_at;type:timestamp with time zone;not null;index:idx_secrets_owner,priority:2;default:now()" json:"created_at"`
	UpdatedAt        *time.Time     `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now()" json:"updated_at"`
	DeletedAt        gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp with time zone" json:"deleted_at"`
}

// TableName Secret's table name
func (*Secret) TableName() string {
	return TableNameSecret
}
