// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSecretAccessEvent = "secret_access_events"

// SecretAccessEvent mapped from table <secret_access_events>
type SecretAccessEvent struct {
	EventID   int64      `gorm:"column:event_id;type:bigint;primaryKey;autoIncrement:true" json:"event_id"`
	SecretID  string     `gorm:"column:secret_id;type:text;not null;index:idx_secret_access_events_secret_created,priority:1" json:"secret_id"`
	VersionID string     `gorm:"column:version_id;type:text;not null" json:"version_id"`
	NodeID    string     `gorm:"column:node_id;type:text;not null" json:"node_id"`
	AgentID   string     `gorm:"column:agent_id;type:text;not null" json:"agent_id"`
	SessionID string     `gorm:"column:session_id;type:text;not null" json:"session_id"`
	Action    string     `gorm:"column:action;type:text;not null" json:"action"`
	Result    string     `gorm:"column:result;type:text;not null" json:"result"`
	CreatedAt *time.Time `gorm:"column:created_at;type:timestamp with time zone;not null;index:idx_secret_access_events_secret_created,priority:2;default:now()" json:"created_at"`
}

// TableName SecretAccessEvent's table name
func (*SecretAccessEvent) TableName() string {
	return TableNameSecretAccessEvent
}
