// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTransportJournal = "transport_journal"

// TransportJournal mapped from table <transport_journal>
type TransportJournal struct {
	ID             int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	AgentID        string     `gorm:"column:agent_id;type:text;not null;index:idx_transport_journal_pending,priority:1" json:"agent_id"`
	Stream         string     `gorm:"column:stream;type:text;not null;index:idx_transport_journal_pending,priority:2" json:"stream"`
	Seq            int64      `gorm:"column:seq;type:bigint;not null;index:idx_transport_journal_pending,priority:3" json:"seq"`
	LocalDirection string     `gorm:"column:local_direction;type:text;not null;index:idx_transport_journal_pending,priority:4" json:"local_direction"`
	PayloadJSON    string     `gorm:"column:payload_json;type:jsonb;not null" json:"payload_json"`
	Status         string     `gorm:"column:status;type:text;not null;index:idx_transport_journal_cleanup,priority:1;index:idx_transport_journal_pending,priority:5" json:"status"`
	Error          *string    `gorm:"column:error;type:text" json:"error"`
	RetryCount     int32      `gorm:"column:retry_count;type:integer;not null" json:"retry_count"`
	CreatedAt      *time.Time `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"created_at"`
	UpdatedAt      *time.Time `gorm:"column:updated_at;type:timestamp with time zone;not null;index:idx_transport_journal_cleanup,priority:2;default:now()" json:"updated_at"`
	SentAt         *time.Time `gorm:"column:sent_at;type:timestamp with time zone" json:"sent_at"`
	ReceivedAt     *time.Time `gorm:"column:received_at;type:timestamp with time zone" json:"received_at"`
	AckedAt        *time.Time `gorm:"column:acked_at;type:timestamp with time zone" json:"acked_at"`
	AppliedAt      *time.Time `gorm:"column:applied_at;type:timestamp with time zone" json:"applied_at"`
}

// TableName TransportJournal's table name
func (*TransportJournal) TableName() string {
	return TableNameTransportJournal
}
