// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	app "github.com/cloudwego/hertz/pkg/app"
	api "github.com/pax-beehive/pax-manager/internal/transport/http/model/paxmanager/api"

	mock "github.com/stretchr/testify/mock"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// AgentAuth provides a mock function with given fields: _a0, _a1
func (_m *MockService) AgentAuth(_a0 context.Context, _a1 *app.RequestContext) {
	_m.Called(_a0, _a1)
}

// MockService_AgentAuth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AgentAuth'
type MockService_AgentAuth_Call struct {
	*mock.Call
}

// AgentAuth is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *app.RequestContext
func (_e *MockService_Expecter) AgentAuth(_a0 interface{}, _a1 interface{}) *MockService_AgentAuth_Call {
	return &MockService_AgentAuth_Call{Call: _e.mock.On("AgentAuth", _a0, _a1)}
}

func (_c *MockService_AgentAuth_Call) Run(run func(_a0 context.Context, _a1 *app.RequestContext)) *MockService_AgentAuth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*app.RequestContext))
	})
	return _c
}

func (_c *MockService_AgentAuth_Call) Return() *MockService_AgentAuth_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_AgentAuth_Call) RunAndReturn(run func(context.Context, *app.RequestContext)) *MockService_AgentAuth_Call {
	_c.Run(run)
	return _c
}

// CreateAgentMessage provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockService) CreateAgentMessage(_a0 context.Context, _a1 *app.RequestContext, _a2 *api.CreateAgentMessageRequest) {
	_m.Called(_a0, _a1, _a2)
}

// MockService_CreateAgentMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAgentMessage'
type MockService_CreateAgentMessage_Call struct {
	*mock.Call
}

// CreateAgentMessage is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *app.RequestContext
//   - _a2 *api.CreateAgentMessageRequest
func (_e *MockService_Expecter) CreateAgentMessage(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockService_CreateAgentMessage_Call {
	return &MockService_CreateAgentMessage_Call{Call: _e.mock.On("CreateAgentMessage", _a0, _a1, _a2)}
}

func (_c *MockService_CreateAgentMessage_Call) Run(run func(_a0 context.Context, _a1 *app.RequestContext, _a2 *api.CreateAgentMessageRequest)) *MockService_CreateAgentMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*app.RequestContext), args[2].(*api.CreateAgentMessageRequest))
	})
	return _c
}

func (_c *MockService_CreateAgentMessage_Call) Return() *MockService_CreateAgentMessage_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_CreateAgentMessage_Call) RunAndReturn(run func(context.Context, *app.RequestContext, *api.CreateAgentMessageRequest)) *MockService_CreateAgentMessage_Call {
	_c.Run(run)
	return _c
}

// CreateAgentRegistrationToken provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockService) CreateAgentRegistrationToken(_a0 context.Context, _a1 *app.RequestContext, _a2 *api.CreateRegistrationTokenRequest) {
	_m.Called(_a0, _a1, _a2)
}

// MockService_CreateAgentRegistrationToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAgentRegistrationToken'
type MockService_CreateAgentRegistrationToken_Call struct {
	*mock.Call
}

// CreateAgentRegistrationToken is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *app.RequestContext
//   - _a2 *api.CreateRegistrationTokenRequest
func (_e *MockService_Expecter) CreateAgentRegistrationToken(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockService_CreateAgentRegistrationToken_Call {
	return &MockService_CreateAgentRegistrationToken_Call{Call: _e.mock.On("CreateAgentRegistrationToken", _a0, _a1, _a2)}
}

func (_c *MockService_CreateAgentRegistrationToken_Call) Run(run func(_a0 context.Context, _a1 *app.RequestContext, _a2 *api.CreateRegistrationTokenRequest)) *MockService_CreateAgentRegistrationToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*app.RequestContext), args[2].(*api.CreateRegistrationTokenRequest))
	})
	return _c
}

func (_c *MockService_CreateAgentRegistrationToken_Call) Return() *MockService_CreateAgentRegistrationToken_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_CreateAgentRegistrationToken_Call) RunAndReturn(run func(context.Context, *app.RequestContext, *api.CreateRegistrationTokenRequest)) *MockService_CreateAgentRegistrationToken_Call {
	_c.Run(run)
	return _c
}

// CreateSessionMessage provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockService) CreateSessionMessage(_a0 context.Context, _a1 *app.RequestContext, _a2 *api.CreateSessionMessageRequest) {
	_m.Called(_a0, _a1, _a2)
}

// MockService_CreateSessionMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSessionMessage'
type MockService_CreateSessionMessage_Call struct {
	*mock.Call
}

// CreateSessionMessage is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *app.RequestContext
//   - _a2 *api.CreateSessionMessageRequest
func (_e *MockService_Expecter) CreateSessionMessage(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockService_CreateSessionMessage_Call {
	return &MockService_CreateSessionMessage_Call{Call: _e.mock.On("CreateSessionMessage", _a0, _a1, _a2)}
}

func (_c *MockService_CreateSessionMessage_Call) Run(run func(_a0 context.Context, _a1 *app.RequestContext, _a2 *api.CreateSessionMessageRequest)) *MockService_CreateSessionMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*app.RequestContext), args[2].(*api.CreateSessionMessageRequest))
	})
	return _c
}

func (_c *MockService_CreateSessionMessage_Call) Return() *MockService_CreateSessionMessage_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_CreateSessionMessage_Call) RunAndReturn(run func(context.Context, *app.RequestContext, *api.CreateSessionMessageRequest)) *MockService_CreateSessionMessage_Call {
	_c.Run(run)
	return _c
}

// CreateUserAPIKey provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockService) CreateUserAPIKey(_a0 context.Context, _a1 *app.RequestContext, _a2 *api.CreateUserAPIKeyRequest) {
	_m.Called(_a0, _a1, _a2)
}

// MockService_CreateUserAPIKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUserAPIKey'
type MockService_CreateUserAPIKey_Call struct {
	*mock.Call
}

// CreateUserAPIKey is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *app.RequestContext
//   - _a2 *api.CreateUserAPIKeyRequest
func (_e *MockService_Expecter) CreateUserAPIKey(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockService_CreateUserAPIKey_Call {
	return &MockService_CreateUserAPIKey_Call{Call: _e.mock.On("CreateUserAPIKey", _a0, _a1, _a2)}
}

func (_c *MockService_CreateUserAPIKey_Call) Run(run func(_a0 context.Context, _a1 *app.RequestContext, _a2 *api.CreateUserAPIKeyRequest)) *MockService_CreateUserAPIKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*app.RequestContext), args[2].(*api.CreateUserAPIKeyRequest))
	})
	return _c
}

func (_c *MockService_CreateUserAPIKey_Call) Return() *MockService_CreateUserAPIKey_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_CreateUserAPIKey_Call) RunAndReturn(run func(context.Context, *app.RequestContext, *api.CreateUserAPIKeyRequest)) *MockService_CreateUserAPIKey_Call {
	_c.Run(run)
	return _c
}

// GetAgent provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockService) GetAgent(_a0 context.Context, _a1 *app.RequestContext, _a2 *api.GetAgentRequest) {
	_m.Called(_a0, _a1, _a2)
}

// MockService_GetAgent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAgent'
type MockService_GetAgent_Call struct {
	*mock.Call
}

// GetAgent is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *app.RequestContext
//   - _a2 *api.GetAgentRequest
func (_e *MockService_Expecter) GetAgent(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockService_GetAgent_Call {
	return &MockService_GetAgent_Call{Call: _e.mock.On("GetAgent", _a0, _a1, _a2)}
}

func (_c *MockService_GetAgent_Call) Run(run func(_a0 context.Context, _a1 *app.RequestContext, _a2 *api.GetAgentRequest)) *MockService_GetAgent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*app.RequestContext), args[2].(*api.GetAgentRequest))
	})
	return _c
}

func (_c *MockService_GetAgent_Call) Return() *MockService_GetAgent_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_GetAgent_Call) RunAndReturn(run func(context.Context, *app.RequestContext, *api.GetAgentRequest)) *MockService_GetAgent_Call {
	_c.Run(run)
	return _c
}

// GetAgentSession provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockService) GetAgentSession(_a0 context.Context, _a1 *app.RequestContext, _a2 *api.GetAgentSessionRequest) {
	_m.Called(_a0, _a1, _a2)
}

// MockService_GetAgentSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAgentSession'
type MockService_GetAgentSession_Call struct {
	*mock.Call
}

// GetAgentSession is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *app.RequestContext
//   - _a2 *api.GetAgentSessionRequest
func (_e *MockService_Expecter) GetAgentSession(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockService_GetAgentSession_Call {
	return &MockService_GetAgentSession_Call{Call: _e.mock.On("GetAgentSession", _a0, _a1, _a2)}
}

func (_c *MockService_GetAgentSession_Call) Run(run func(_a0 context.Context, _a1 *app.RequestContext, _a2 *api.GetAgentSessionRequest)) *MockService_GetAgentSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*app.RequestContext), args[2].(*api.GetAgentSessionRequest))
	})
	return _c
}

func (_c *MockService_GetAgentSession_Call) Return() *MockService_GetAgentSession_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_GetAgentSession_Call) RunAndReturn(run func(context.Context, *app.RequestContext, *api.GetAgentSessionRequest)) *MockService_GetAgentSession_Call {
	_c.Run(run)
	return _c
}

// HandleGenerated provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockService) HandleGenerated(_a0 context.Context, _a1 *app.RequestContext, _a2 string) {
	_m.Called(_a0, _a1, _a2)
}

// MockService_HandleGenerated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleGenerated'
type MockService_HandleGenerated_Call struct {
	*mock.Call
}

// HandleGenerated is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *app.RequestContext
//   - _a2 string
func (_e *MockService_Expecter) HandleGenerated(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockService_HandleGenerated_Call {
	return &MockService_HandleGenerated_Call{Call: _e.mock.On("HandleGenerated", _a0, _a1, _a2)}
}

func (_c *MockService_HandleGenerated_Call) Run(run func(_a0 context.Context, _a1 *app.RequestContext, _a2 string)) *MockService_HandleGenerated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*app.RequestContext), args[2].(string))
	})
	return _c
}

func (_c *MockService_HandleGenerated_Call) Return() *MockService_HandleGenerated_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_HandleGenerated_Call) RunAndReturn(run func(context.Context, *app.RequestContext, string)) *MockService_HandleGenerated_Call {
	_c.Run(run)
	return _c
}

// Health provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockService) Health(_a0 context.Context, _a1 *app.RequestContext, _a2 *api.EmptyRequest) {
	_m.Called(_a0, _a1, _a2)
}

// MockService_Health_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Health'
type MockService_Health_Call struct {
	*mock.Call
}

// Health is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *app.RequestContext
//   - _a2 *api.EmptyRequest
func (_e *MockService_Expecter) Health(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockService_Health_Call {
	return &MockService_Health_Call{Call: _e.mock.On("Health", _a0, _a1, _a2)}
}

func (_c *MockService_Health_Call) Run(run func(_a0 context.Context, _a1 *app.RequestContext, _a2 *api.EmptyRequest)) *MockService_Health_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*app.RequestContext), args[2].(*api.EmptyRequest))
	})
	return _c
}

func (_c *MockService_Health_Call) Return() *MockService_Health_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_Health_Call) RunAndReturn(run func(context.Context, *app.RequestContext, *api.EmptyRequest)) *MockService_Health_Call {
	_c.Run(run)
	return _c
}

// ListAgentMessages provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockService) ListAgentMessages(_a0 context.Context, _a1 *app.RequestContext, _a2 *api.ListAgentMessagesRequest) {
	_m.Called(_a0, _a1, _a2)
}

// MockService_ListAgentMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAgentMessages'
type MockService_ListAgentMessages_Call struct {
	*mock.Call
}

// ListAgentMessages is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *app.RequestContext
//   - _a2 *api.ListAgentMessagesRequest
func (_e *MockService_Expecter) ListAgentMessages(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockService_ListAgentMessages_Call {
	return &MockService_ListAgentMessages_Call{Call: _e.mock.On("ListAgentMessages", _a0, _a1, _a2)}
}

func (_c *MockService_ListAgentMessages_Call) Run(run func(_a0 context.Context, _a1 *app.RequestContext, _a2 *api.ListAgentMessagesRequest)) *MockService_ListAgentMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*app.RequestContext), args[2].(*api.ListAgentMessagesRequest))
	})
	return _c
}

func (_c *MockService_ListAgentMessages_Call) Return() *MockService_ListAgentMessages_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_ListAgentMessages_Call) RunAndReturn(run func(context.Context, *app.RequestContext, *api.ListAgentMessagesRequest)) *MockService_ListAgentMessages_Call {
	_c.Run(run)
	return _c
}

// ListAgentSessionMessages provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockService) ListAgentSessionMessages(_a0 context.Context, _a1 *app.RequestContext, _a2 *api.ListAgentSessionMessagesRequest) {
	_m.Called(_a0, _a1, _a2)
}

// MockService_ListAgentSessionMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAgentSessionMessages'
type MockService_ListAgentSessionMessages_Call struct {
	*mock.Call
}

// ListAgentSessionMessages is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *app.RequestContext
//   - _a2 *api.ListAgentSessionMessagesRequest
func (_e *MockService_Expecter) ListAgentSessionMessages(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockService_ListAgentSessionMessages_Call {
	return &MockService_ListAgentSessionMessages_Call{Call: _e.mock.On("ListAgentSessionMessages", _a0, _a1, _a2)}
}

func (_c *MockService_ListAgentSessionMessages_Call) Run(run func(_a0 context.Context, _a1 *app.RequestContext, _a2 *api.ListAgentSessionMessagesRequest)) *MockService_ListAgentSessionMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*app.RequestContext), args[2].(*api.ListAgentSessionMessagesRequest))
	})
	return _c
}

func (_c *MockService_ListAgentSessionMessages_Call) Return() *MockService_ListAgentSessionMessages_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_ListAgentSessionMessages_Call) RunAndReturn(run func(context.Context, *app.RequestContext, *api.ListAgentSessionMessagesRequest)) *MockService_ListAgentSessionMessages_Call {
	_c.Run(run)
	return _c
}

// ListAgentSessions provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockService) ListAgentSessions(_a0 context.Context, _a1 *app.RequestContext, _a2 *api.ListAgentSessionsRequest) {
	_m.Called(_a0, _a1, _a2)
}

// MockService_ListAgentSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAgentSessions'
type MockService_ListAgentSessions_Call struct {
	*mock.Call
}

// ListAgentSessions is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *app.RequestContext
//   - _a2 *api.ListAgentSessionsRequest
func (_e *MockService_Expecter) ListAgentSessions(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockService_ListAgentSessions_Call {
	return &MockService_ListAgentSessions_Call{Call: _e.mock.On("ListAgentSessions", _a0, _a1, _a2)}
}

func (_c *MockService_ListAgentSessions_Call) Run(run func(_a0 context.Context, _a1 *app.RequestContext, _a2 *api.ListAgentSessionsRequest)) *MockService_ListAgentSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*app.RequestContext), args[2].(*api.ListAgentSessionsRequest))
	})
	return _c
}

func (_c *MockService_ListAgentSessions_Call) Return() *MockService_ListAgentSessions_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_ListAgentSessions_Call) RunAndReturn(run func(context.Context, *app.RequestContext, *api.ListAgentSessionsRequest)) *MockService_ListAgentSessions_Call {
	_c.Run(run)
	return _c
}

// ListAgents provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockService) ListAgents(_a0 context.Context, _a1 *app.RequestContext, _a2 *api.EmptyRequest) {
	_m.Called(_a0, _a1, _a2)
}

// MockService_ListAgents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAgents'
type MockService_ListAgents_Call struct {
	*mock.Call
}

// ListAgents is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *app.RequestContext
//   - _a2 *api.EmptyRequest
func (_e *MockService_Expecter) ListAgents(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockService_ListAgents_Call {
	return &MockService_ListAgents_Call{Call: _e.mock.On("ListAgents", _a0, _a1, _a2)}
}

func (_c *MockService_ListAgents_Call) Run(run func(_a0 context.Context, _a1 *app.RequestContext, _a2 *api.EmptyRequest)) *MockService_ListAgents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*app.RequestContext), args[2].(*api.EmptyRequest))
	})
	return _c
}

func (_c *MockService_ListAgents_Call) Return() *MockService_ListAgents_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_ListAgents_Call) RunAndReturn(run func(context.Context, *app.RequestContext, *api.EmptyRequest)) *MockService_ListAgents_Call {
	_c.Run(run)
	return _c
}

// ListUserAPIKeys provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockService) ListUserAPIKeys(_a0 context.Context, _a1 *app.RequestContext, _a2 *api.EmptyRequest) {
	_m.Called(_a0, _a1, _a2)
}

// MockService_ListUserAPIKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUserAPIKeys'
type MockService_ListUserAPIKeys_Call struct {
	*mock.Call
}

// ListUserAPIKeys is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *app.RequestContext
//   - _a2 *api.EmptyRequest
func (_e *MockService_Expecter) ListUserAPIKeys(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockService_ListUserAPIKeys_Call {
	return &MockService_ListUserAPIKeys_Call{Call: _e.mock.On("ListUserAPIKeys", _a0, _a1, _a2)}
}

func (_c *MockService_ListUserAPIKeys_Call) Run(run func(_a0 context.Context, _a1 *app.RequestContext, _a2 *api.EmptyRequest)) *MockService_ListUserAPIKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*app.RequestContext), args[2].(*api.EmptyRequest))
	})
	return _c
}

func (_c *MockService_ListUserAPIKeys_Call) Return() *MockService_ListUserAPIKeys_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_ListUserAPIKeys_Call) RunAndReturn(run func(context.Context, *app.RequestContext, *api.EmptyRequest)) *MockService_ListUserAPIKeys_Call {
	_c.Run(run)
	return _c
}

// PullMailbox provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockService) PullMailbox(_a0 context.Context, _a1 *app.RequestContext, _a2 *api.PullMailboxRequest) {
	_m.Called(_a0, _a1, _a2)
}

// MockService_PullMailbox_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PullMailbox'
type MockService_PullMailbox_Call struct {
	*mock.Call
}

// PullMailbox is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *app.RequestContext
//   - _a2 *api.PullMailboxRequest
func (_e *MockService_Expecter) PullMailbox(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockService_PullMailbox_Call {
	return &MockService_PullMailbox_Call{Call: _e.mock.On("PullMailbox", _a0, _a1, _a2)}
}

func (_c *MockService_PullMailbox_Call) Run(run func(_a0 context.Context, _a1 *app.RequestContext, _a2 *api.PullMailboxRequest)) *MockService_PullMailbox_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*app.RequestContext), args[2].(*api.PullMailboxRequest))
	})
	return _c
}

func (_c *MockService_PullMailbox_Call) Return() *MockService_PullMailbox_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_PullMailbox_Call) RunAndReturn(run func(context.Context, *app.RequestContext, *api.PullMailboxRequest)) *MockService_PullMailbox_Call {
	_c.Run(run)
	return _c
}

// PullSessionMailbox provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockService) PullSessionMailbox(_a0 context.Context, _a1 *app.RequestContext, _a2 *api.PullSessionMailboxRequest) {
	_m.Called(_a0, _a1, _a2)
}

// MockService_PullSessionMailbox_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PullSessionMailbox'
type MockService_PullSessionMailbox_Call struct {
	*mock.Call
}

// PullSessionMailbox is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *app.RequestContext
//   - _a2 *api.PullSessionMailboxRequest
func (_e *MockService_Expecter) PullSessionMailbox(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockService_PullSessionMailbox_Call {
	return &MockService_PullSessionMailbox_Call{Call: _e.mock.On("PullSessionMailbox", _a0, _a1, _a2)}
}

func (_c *MockService_PullSessionMailbox_Call) Run(run func(_a0 context.Context, _a1 *app.RequestContext, _a2 *api.PullSessionMailboxRequest)) *MockService_PullSessionMailbox_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*app.RequestContext), args[2].(*api.PullSessionMailboxRequest))
	})
	return _c
}

func (_c *MockService_PullSessionMailbox_Call) Return() *MockService_PullSessionMailbox_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_PullSessionMailbox_Call) RunAndReturn(run func(context.Context, *app.RequestContext, *api.PullSessionMailboxRequest)) *MockService_PullSessionMailbox_Call {
	_c.Run(run)
	return _c
}

// RegisterAgent provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockService) RegisterAgent(_a0 context.Context, _a1 *app.RequestContext, _a2 *api.RegisterAgentRequest) {
	_m.Called(_a0, _a1, _a2)
}

// MockService_RegisterAgent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterAgent'
type MockService_RegisterAgent_Call struct {
	*mock.Call
}

// RegisterAgent is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *app.RequestContext
//   - _a2 *api.RegisterAgentRequest
func (_e *MockService_Expecter) RegisterAgent(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockService_RegisterAgent_Call {
	return &MockService_RegisterAgent_Call{Call: _e.mock.On("RegisterAgent", _a0, _a1, _a2)}
}

func (_c *MockService_RegisterAgent_Call) Run(run func(_a0 context.Context, _a1 *app.RequestContext, _a2 *api.RegisterAgentRequest)) *MockService_RegisterAgent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*app.RequestContext), args[2].(*api.RegisterAgentRequest))
	})
	return _c
}

func (_c *MockService_RegisterAgent_Call) Return() *MockService_RegisterAgent_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_RegisterAgent_Call) RunAndReturn(run func(context.Context, *app.RequestContext, *api.RegisterAgentRequest)) *MockService_RegisterAgent_Call {
	_c.Run(run)
	return _c
}

// ReportAgentStatus provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockService) ReportAgentStatus(_a0 context.Context, _a1 *app.RequestContext, _a2 *api.AgentStatusReportRequest) {
	_m.Called(_a0, _a1, _a2)
}

// MockService_ReportAgentStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReportAgentStatus'
type MockService_ReportAgentStatus_Call struct {
	*mock.Call
}

// ReportAgentStatus is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *app.RequestContext
//   - _a2 *api.AgentStatusReportRequest
func (_e *MockService_Expecter) ReportAgentStatus(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockService_ReportAgentStatus_Call {
	return &MockService_ReportAgentStatus_Call{Call: _e.mock.On("ReportAgentStatus", _a0, _a1, _a2)}
}

func (_c *MockService_ReportAgentStatus_Call) Run(run func(_a0 context.Context, _a1 *app.RequestContext, _a2 *api.AgentStatusReportRequest)) *MockService_ReportAgentStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*app.RequestContext), args[2].(*api.AgentStatusReportRequest))
	})
	return _c
}

func (_c *MockService_ReportAgentStatus_Call) Return() *MockService_ReportAgentStatus_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_ReportAgentStatus_Call) RunAndReturn(run func(context.Context, *app.RequestContext, *api.AgentStatusReportRequest)) *MockService_ReportAgentStatus_Call {
	_c.Run(run)
	return _c
}

// ReportMessageResult provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockService) ReportMessageResult(_a0 context.Context, _a1 *app.RequestContext, _a2 *api.ReportMessageResultRequest) {
	_m.Called(_a0, _a1, _a2)
}

// MockService_ReportMessageResult_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReportMessageResult'
type MockService_ReportMessageResult_Call struct {
	*mock.Call
}

// ReportMessageResult is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *app.RequestContext
//   - _a2 *api.ReportMessageResultRequest
func (_e *MockService_Expecter) ReportMessageResult(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockService_ReportMessageResult_Call {
	return &MockService_ReportMessageResult_Call{Call: _e.mock.On("ReportMessageResult", _a0, _a1, _a2)}
}

func (_c *MockService_ReportMessageResult_Call) Run(run func(_a0 context.Context, _a1 *app.RequestContext, _a2 *api.ReportMessageResultRequest)) *MockService_ReportMessageResult_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*app.RequestContext), args[2].(*api.ReportMessageResultRequest))
	})
	return _c
}

func (_c *MockService_ReportMessageResult_Call) Return() *MockService_ReportMessageResult_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_ReportMessageResult_Call) RunAndReturn(run func(context.Context, *app.RequestContext, *api.ReportMessageResultRequest)) *MockService_ReportMessageResult_Call {
	_c.Run(run)
	return _c
}

// RevokeUserAPIKey provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockService) RevokeUserAPIKey(_a0 context.Context, _a1 *app.RequestContext, _a2 *api.RevokeUserAPIKeyRequest) {
	_m.Called(_a0, _a1, _a2)
}

// MockService_RevokeUserAPIKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeUserAPIKey'
type MockService_RevokeUserAPIKey_Call struct {
	*mock.Call
}

// RevokeUserAPIKey is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *app.RequestContext
//   - _a2 *api.RevokeUserAPIKeyRequest
func (_e *MockService_Expecter) RevokeUserAPIKey(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockService_RevokeUserAPIKey_Call {
	return &MockService_RevokeUserAPIKey_Call{Call: _e.mock.On("RevokeUserAPIKey", _a0, _a1, _a2)}
}

func (_c *MockService_RevokeUserAPIKey_Call) Run(run func(_a0 context.Context, _a1 *app.RequestContext, _a2 *api.RevokeUserAPIKeyRequest)) *MockService_RevokeUserAPIKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*app.RequestContext), args[2].(*api.RevokeUserAPIKeyRequest))
	})
	return _c
}

func (_c *MockService_RevokeUserAPIKey_Call) Return() *MockService_RevokeUserAPIKey_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_RevokeUserAPIKey_Call) RunAndReturn(run func(context.Context, *app.RequestContext, *api.RevokeUserAPIKeyRequest)) *MockService_RevokeUserAPIKey_Call {
	_c.Run(run)
	return _c
}

// UpdateMailboxOffset provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockService) UpdateMailboxOffset(_a0 context.Context, _a1 *app.RequestContext, _a2 *api.UpdateMailboxOffsetRequest) {
	_m.Called(_a0, _a1, _a2)
}

// MockService_UpdateMailboxOffset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMailboxOffset'
type MockService_UpdateMailboxOffset_Call struct {
	*mock.Call
}

// UpdateMailboxOffset is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *app.RequestContext
//   - _a2 *api.UpdateMailboxOffsetRequest
func (_e *MockService_Expecter) UpdateMailboxOffset(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockService_UpdateMailboxOffset_Call {
	return &MockService_UpdateMailboxOffset_Call{Call: _e.mock.On("UpdateMailboxOffset", _a0, _a1, _a2)}
}

func (_c *MockService_UpdateMailboxOffset_Call) Run(run func(_a0 context.Context, _a1 *app.RequestContext, _a2 *api.UpdateMailboxOffsetRequest)) *MockService_UpdateMailboxOffset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*app.RequestContext), args[2].(*api.UpdateMailboxOffsetRequest))
	})
	return _c
}

func (_c *MockService_UpdateMailboxOffset_Call) Return() *MockService_UpdateMailboxOffset_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_UpdateMailboxOffset_Call) RunAndReturn(run func(context.Context, *app.RequestContext, *api.UpdateMailboxOffsetRequest)) *MockService_UpdateMailboxOffset_Call {
	_c.Run(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
